src/objects/AMI_Chart__mdt.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AMI Chart</label>
    <pluralLabel>AMI Charts</pluralLabel>
</CustomObject>

src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Development__c</fullName>
        <description>Development for the property</description>
        <inlineHelpText>Development for the property</inlineHelpText>
        <label>Development</label>
        <referenceTo>Development__c</referenceTo>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Development__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MOHCD Project ID</label>
        <type>Text</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Property Auto-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Development__c.object
<CustomObject>
    <fields>
        <fullName>Name_of_Development__c</fullName>
        <label>Name of Development</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Development</label>
    <nameField>
        <displayFormat>DVL-{000000}</displayFormat>
        <label>Development Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>AMI_chart_type__c</fullName>
        <inlineHelpText>Default value &quot;HUD Unadjusted&quot; will be updated upon save.</inlineHelpText>
        <label>AMI chart type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AMI_Chart_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AMI_chart_year__c</fullName>
        <inlineHelpText>Default value latest year will be updated upon save.</inlineHelpText>
        <label>AMI chart year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Building Record Number</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>UID-{0000000}</displayFormat>
        <label>Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/AMI_Chart_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HUD Unadjusted</fullName>
    </customValue>
    <customValue>
        <fullName>HCD/TCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Non-HERA</fullName>
    </customValue>
    <masterLabel>AMI Chart Types</masterLabel>
</GlobalValueSet>

src/classes/UnitTriggerHandlerTest.cls
@isTest
public with sharing class UnitTriggerHandlerTest {
    
    public static testmethod void testInsertUnit() {
    	Development__c dev = new Development__c(Name_of_Development__c = 'Test');
    	dev.Project_ID__c = '123';
        insert dev;
    	
    	Building__c building = new Building__c(Development__c = dev.Id);
    	insert building;
    	
    	test.startTest();
    	Unit__c unit = new Unit__c(Property__c = building.Id);
    	insert unit;
    	Decimal maxAmiYear = [select Year__c from AMI_Chart__mdt order by Year__c desc limit 1].Year__c;
    	
    	unit = [SELECT Id, AMI_chart_type__c, AMI_chart_year__c FROM Unit__c WHERE Id = :unit.Id];
    	system.assert(unit.AMI_chart_year__c == maxAmiYear);
    	system.assert(unit.AMI_chart_type__c == 'HUD Unadjusted');
    	
    	test.stopTest();
    }
}