src/objects/AMI_Chart__mdt.object
<CustomObject>
    <fields>
        <fullName>Year__c</fullName>
        <label>Year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>AMI Chart</label>
    <pluralLabel>AMI Charts</pluralLabel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>AMI_chart_type__c</fullName>
        <inlineHelpText>Default value &quot;HUD Unadjusted&quot; will be updated upon save.</inlineHelpText>
        <label>AMI chart type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>AMI_Chart_Types</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>AMI_chart_year__c</fullName>
        <inlineHelpText>Default value latest year will be updated upon save.</inlineHelpText>
        <label>AMI chart year</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>UID-{0000000}</displayFormat>
        <label>Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/AMI_Chart_Types.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>HUD Unadjusted</fullName>
    </customValue>
    <customValue>
        <fullName>HCD/TCAC</fullName>
    </customValue>
    <customValue>
        <fullName>Non-HERA</fullName>
    </customValue>
    <masterLabel>AMI Chart Types</masterLabel>
</GlobalValueSet>

src/classes/UnitTriggerHandler.cls
public with sharing class UnitTriggerHandler {
    /*
	 * Handle on before insert events
	 */
	public void onBeforeInsert(List<Unit__c> newUnits) {
		handleOnBeforeInsertEvent(newUnits);
	}
	
	public void handleOnBeforeInsertEvent(List<Unit__c> newUnits) {
		Decimal maxAmiYear = [select Year__c from AMI_Chart__mdt order by Year__c desc limit 1].Year__c;
		for (Unit__c unit : newUnits) {
			unit.AMI_chart_type__c = 'HUD Unadjusted';
			unit.AMI_chart_year__c = maxAmiYear;
		}
	}
}