src/objects/AMI__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Num_of_HouseHold__c</fullName>
        <label>Num of HouseHold</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Percent_of_Median__c</fullName>
        <label>Percent of Median</label>
        <precision>3</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>AMI Chart</label>
</CustomObject>

src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Developer for the Building.</description>
        <inlineHelpText>Developer for the Building.</inlineHelpText>
        <label>Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development__c</fullName>
        <description>Development for the property</description>
        <inlineHelpText>Development for the property</inlineHelpText>
        <label>Development</label>
        <referenceTo>Development__c</referenceTo>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Property Auto-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Development__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Developer who is responsible for this development.</description>
        <label>Developer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be a developer</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Property Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Developments</relationshipLabel>
        <relationshipName>Developments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_Development__c</fullName>
        <label>Name of Development</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Development</label>
    <nameField>
        <displayFormat>DVL-{000000}</displayFormat>
        <label>Development Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <description>Name of the Developer for the Building.</description>
        <formula>Building__r.Developer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of the Developer for the Building.</inlineHelpText>
        <label>Developer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing_Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The listing for this object</description>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Preference__c</fullName>
        <label>Preference</label>
        <referenceTo>Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Listing Preference</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Listing Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of this preference</description>
        <inlineHelpText>Enter the current status of this preference</inlineHelpText>
        <label>XStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Old</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>of_AMI_for_Pricing_Unit__c</fullName>
        <inlineHelpText>% of Area Median Income for pricing unit</inlineHelpText>
        <label>% of AMI for Pricing Unit</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <recordTypes>
        <fullName>Unit</fullName>
        <active>true</active>
        <description>Unit level details for a property (Apt. #, Sq. Ft., # of Bedrooms, etc.)</description>
        <label>Unit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>BMR_Rent_Monthly__c</fullName>
        <description>Monthly Rent for BMR Unit</description>
        <inlineHelpText>Monthly Rent for BMR Unit</inlineHelpText>
        <label>Monthly rent (if $)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Maximum_Household_Size__c</fullName>
        <description>Maximum members of a household that are allowed in a unit.</description>
        <inlineHelpText>Maximum members of a household that are allowed in a unit.</inlineHelpText>
        <label>Maximum Household Size</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Building Record Number</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rent_Multiple__c</fullName>
        <label>Rent Multiple</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>To be Built out, but is the unit currently occupied/available (includes in development). Will largely be a hidden field.</description>
        <inlineHelpText>To be Built out, but is the unit currently occupied/available (includes in development). Will largely be a hidden field.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Occupied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_AMI_for_Pricing_Unit__c</fullName>
        <description>% of Area Median Income for Pricing Unit.</description>
        <inlineHelpText>% of Area Median Income for Pricing Unit.</inlineHelpText>
        <label>% of AMI for Pricing Unit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>UID-{0000000}</displayFormat>
        <label>Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListingApiTest.cls
@isTest
private class ListingApiTest {
     
    private static List<Properties__c> lProperties;
    private static Account acc;
    private static Contact con;
    private static User usr;
    static  ID listingID ;
    static String preferenceName;
    
    static void setupTestData() {
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        acc = new Account();
        acc.Name = 'Test Account';
        acc.RecordTypeId = rtId;
        acc.AccountNumber = '12345';
        insert acc;
        
        Development__c dev = new Development__c();
        dev.Name_of_Development__c = 'amli';
        insert dev;
        
        //Property__c prop = new Property__c();//
        //prop.development__c=dev.id;//
       // insert prop;//
       
        Building__c build = new Building__c();
        build.Development__c = dev.Id;
        build.Developer__c = acc.Id;
       	insert build;
        
        Listing__c listing = new Listing__c();
        listing.name='somelisting';
        listing.Building__c  = build.id;
        listing.Account__c = acc.Id;
        listing.Status__c= 'Active';
        insert listing;
        
        Listing__c listing1 = new Listing__c();
        listing1.name='somelisting';
        listing1.Building__c  = build.id;
        listing1.Account__c = acc.Id;
        listing1.Status__c= 'Active';
        insert listing1;
        
        Listing__c listing2 = new Listing__c();
        listing2.name='somelisting';
        listing2.Building__c  = build.id;
        listing2.Account__c = acc.Id;
        listing2.Status__c= 'Active';
        insert listing2;
        
        Lottery_Preference__c lp = new Lottery_Preference__c();
        lp.Name = 'Test Lottery Preference';
        lp.Status__c = 'New';
        insert lp;
       	preferenceName = lp.Name;
        
        Listing_Lottery_Preference__c llp = new Listing_Lottery_Preference__c();
        llp.Listing__c = listing.Id;
        llp.Lottery_Preference__c = lp.Id;
        insert llp;
        
        Unit__c unit = new Unit__c();
        unit.property__c  = build.id;
        unit.BMR_Rent_Monthly__c = 400;
        unit.Rent_Multiple__c=3;
        unit.of_AMI_for_Pricing_Unit__c=55;
        unit.Listing__c = listing.id;
        unit.Maximum_Household_Size__c  =2;
        insert unit;
        listingID = listing.id;
        
        AMI__c ami = new AMI__c();
        ami.name='asdf';
        ami.amount__c = 40000;
        ami.Num_of_HouseHold__c=2;
        ami.Percent_of_Median__c=55;
        insert ami;
        //select id, amount__c, Num_of_HouseHold__c, Percent_of_Median__c from AMI__c]
    }
    static testMethod void testGetAll() {
         setupTestData();
        RestRequest reqContext = new RestRequest();

        reqContext.requestURI = '/Listings/';
        //reqContext.params.put('preference','test preference');
        System.RestContext.request =reqContext; 
        
        
        system.assert(ListingApi.doGet().size() == 3);
        
        
    }
    static testMethod void testGetByID() {
        setupTestData();
        RestRequest reqContext = new RestRequest();

        reqContext.requestURI = '/Listings/' + listingID;
        System.RestContext.request =reqContext; 
        
        List<Listing__c> testL = new List<Listing__c>();
        testL = ListingApi.doGet();
        //verify the returned Id is the right one 
        system.assert(testL[0].Id == listingID);

        //ListingApi.doGet();
        
        
    }
     static testMethod void testGetByIDs() {
        setupTestData();
        RestRequest reqContext = new RestRequest();
        reqContext.params.put('ids', listingID);

        reqContext.requestURI = '/Listings/';
        System.RestContext.request =reqContext; 
        
        List<Listing__c> testL = new List<Listing__c>();
        testL = ListingApi.doGet();
        //verify the returned Id is the right one 
        system.assert(testL[0].Id == listingID);

         //ListingApi.doGet();
        
        
    }
    static testMethod void testGetByIDParam() {
        setupTestData();
        RestRequest reqContext = new RestRequest();
        reqContext.params.put('id', listingID); 

        reqContext.requestURI = '/Listings/';
        System.RestContext.request =reqContext; 
        
        List<Listing__c> testL = new List<Listing__c>();
        testL = ListingApi.doGet();
        //verify the returned Id is the right one 
        system.assert(testL[0].Id == listingID);

        //ListingApi.doGet();
        
        
    }
    
    static testMethod void testParamListing() {
        setupTestData();
        
        RestRequest reqContext = new RestRequest();
        reqContext.params.put('householdsize','1');
        reqContext.params.put('incomelevel','31000');
        reqContext.requestURI = '/Listings/';
        System.RestContext.request =reqContext;
        
        List<Listing__c> testL = new List<Listing__c>();
        testL = ListingApi.doGet();
        //verify the returned Id is the right one 
        system.assert(testL[0].Id == listingID);
        
       	//ListingApi.doGet();
    }

    static testMethod void getActiveListingsByPreference() {
         setupTestData();
        RestRequest reqContext = new RestRequest();

        reqContext.requestURI = '/Listings/';
        reqContext.params.put('preference', preferenceName);
        System.RestContext.request =reqContext; 
        
        List<Listing__c> testL = new List<Listing__c>();
        testL = ListingApi.doGet();
        //verify the returned Id is the right one 
        system.assert(testL[0].Id == listingID);
        
        //system.assert(ListingApi.doGet().size() == 3);
    }
}