src/objects/API_Service_Log__c.object
<CustomObject>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Serialized_Request__c</fullName>
        <description>json serialized request</description>
        <label>Serialized Request</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>API Service Log</label>
    <nameField>
        <displayFormat>API-{000000000}</displayFormat>
        <label>Api_Service_Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>API Service Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/API_LoggingService.cls
public with sharing class API_LoggingService {
      public static void logRequest (RestRequest req) {
    	String jsonRequest= Json.serialize (req);
    	API_Service_Log__c log = new API_Service_Log__c();
    	try {
    		log.Body__c = req.requestBody.tostring();
    	}
    	catch (System.Exception e){
    		
    	}
    	log.URL__c=req.requestURI;
    	log.Method__c = req.httpMethod;
    	log.Serialized_Request__c = jsonRequest;
    	insert log;
    }
}