src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Primary Applicant Gender</description>
        <formula>IF(ISPICKVAL( Applicant__r.Gender__c, &quot;Male&quot;), &quot;Male&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Female&quot;), &quot;Female&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Trans Male&quot;), &quot;Trans Male&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Trans Female&quot;), &quot;Trans Female&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Not Listed&quot;), Applicant__r.Gender_Other__c,
IF(ISPICKVAL( Applicant__r.Gender__c, &quot;Decline to State&quot;), &quot;Decline to State&quot;, NULL))))))</formula>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Resident__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resident</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary applicant on the application</description>
        <inlineHelpText>Select the primary applicant for this application</inlineHelpText>
        <label>Applicant</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Applicant_Household__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications (Primary Applicant)</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Certificate_of_Preference_Holder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certificate of Preference Holder?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Displaced_Tenant_Preference__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Formerly The Ellis Act, Does this Contact have this preference?</description>
        <inlineHelpText>Formerly The Ellis Act, Does this Contact have this preference?</inlineHelpText>
        <label>Displaced Tenant Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans Male</fullName>
                </value>
                <value>
                    <fullName>Trans Female</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Decline to State</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prior_Tax_Year_Total_Income_Amount__c</fullName>
        <label>Prior Tax Year Total Income Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Head_of_Household2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Registered Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Great Grandparent</fullName>
                </value>
                <value>
                    <fullName>In-Law</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_City__c</fullName>
        <description>City of Work of the Contact</description>
        <inlineHelpText>City of Work of the Contact</inlineHelpText>
        <label>Work City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Postal_Code__c</fullName>
        <description>Work Postal Code for the Contact</description>
        <inlineHelpText>Work Postal Code for the Contact</inlineHelpText>
        <label>Work Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_State__c</fullName>
        <description>State of Work for the Contact</description>
        <inlineHelpText>State of Work for the Contact</inlineHelpText>
        <label>Work State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Street__c</fullName>
        <description>Work street Address</description>
        <inlineHelpText>Work street Address</inlineHelpText>
        <label>Work Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/API_Application.cls
global with sharing class API_Application {
    
    global class ShortForm {
    	global String id;
    	global ID listingID;
        global Person primaryApplicant;
        global Person secondaryContact;
        global List<Person> householdMembers;
        global Boolean worksInSanFrancisco;
        global String currentStatus;
        global Integer yearsHomeless;
        global Boolean isResident;

        global ShortForm() {} 

        global ShortForm(Application__c app, List<Contact> hms) {
            this.id = app.Id;
            this.primaryApplicant = app.Primary_Applicant__r == null ? null : new Person(app.Primary_Applicant__r);
            this.secondaryContact = app.Secondary_Contact__r == null ? null : new Person(app.Secondary_Contact__r);
            this.householdMembers = new List<Person>();
            for (Contact c : hms) {
                this.householdMembers.add(new Person(c));
            }
            
            this.listingID =  app.Listing__c; 
            this.worksInSanFrancisco = app.Works_In_SF__c;
            this.currentStatus = app.Status__c;
            this.yearsHomeless = Integer.valueOf(app.Years_Homeless__c);
            this.isResident = app.Is_Resident__c;
       }

        global Application__c toApplication() {
            Application__c app = new Application__c();
            app.Id = this.id;
            app.Listing__c = listingID; 
            app.Primary_Applicant__c = this.primaryApplicant == null ? null : this.primaryApplicant.id;
            app.Secondary_Contact__c = this.secondaryContact == null ? null : this.secondaryContact.id;
            app.Works_In_SF__c = this.worksInSanFrancisco;
            app.Status__c = this.currentStatus;
            app.Years_Homeless__c = this.yearsHomeless;
            app.Is_Resident__c = this.isResident;

            return app;
        }
    }

    global class Person {
        global String id;
        global String firstName;
        global String lastName;
        global String dob;
        global String email;
        global String phone;
        global String address;
        global String city;
        global String state;
        global String zip;
        global String mailingAddress;
        global String mailingCity;
        global String mailingState;
        global String mailingZip;
        global String workAddress;
        global String workCity;
        global String workState;
        global String workZip;
        global String gender;
        global Boolean holdsCOP;
        global Boolean holdsDTP;
        global String relationship;
        global Decimal annualIncome;
        global String incomeType;

        global Person() {}

        global Person(Contact c) {
            this.id = c.Id;
            this.firstName = c.FirstName;
            this.lastName = c.LastName;
            this.dob = c.Birthdate == null ? '' : c.Birthdate.format();
            this.email = c.Email;
            this.phone = c.Phone;
            this.address = c.Street_Name__c;
            this.city = c.City__c;
            this.state = c.State__c;
            this.zip = c.Zip_Code__c;
            this.mailingAddress = c.MailingStreet;
            this.mailingCity = c.MailingCity;
            this.mailingState = c.MailingState;
            this.mailingZip = c.MailingPostalCode;
            this.workAddress = c.Work_Street__c;
            this.workCity = c.Work_City__c;
            this.workState = c.Work_State__c;
            this.workZip = c.Work_Postal_Code__c;
            this.gender = c.Gender__c;
            this.holdsCOP = c.Certificate_of_Preference_Holder__c;
            this.holdsDTP = c.Displaced_Tenant_Preference__c;
            this.relationship = c.Relationship_to_Head_of_Household__c;
            this.annualIncome = c.Prior_Tax_Year_Total_Income_Amount__c;
            //this.incomeType = ;
        }

        global Contact toContact() {
            Contact c = new Contact();
            c.Id = this.id;
            c.FirstName = this.firstName;
            c.LastName = this.lastName;
            c.Birthdate = String.isBlank(this.dob) ? null : Date.parse(this.dob);
            c.Email = this.email;
            c.Phone = this.phone;
            c.Street_Name__c = this.address;
            c.City__c = this.city;
            c.State__c = this.state;
            c.Zip_Code__c = this.zip;
            c.MailingStreet = this.mailingAddress;
            c.MailingCity = this.mailingCity;
            c.MailingState = this.mailingState;
            c.MailingPostalCode = this.mailingZip;
            c.Work_Street__c = this.workAddress;
            c.Work_City__c = this.workCity;
            c.Work_State__c = this.workState;
            c.Work_Postal_Code__c = this.workZip;
            c.Gender__c = this.gender;
            c.Certificate_of_Preference_Holder__c = this.holdsCOP == null ? false : this.holdsCOP;
            c.Displaced_Tenant_Preference__c = this.holdsDTP == null ? false : this.holdsDTP;
            c.Relationship_to_Head_of_Household__c = this.relationship;
            c.Prior_Tax_Year_Total_Income_Amount__c = this.annualIncome;
            //this.incomeType = ;

            return c;
        }
    }
    
}