src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Application_Households</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Applicant</fullName>
                </value>
                <value>
                    <fullName>Alternate Contact</fullName>
                </value>
                <value>
                    <fullName>Household Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isFiltered__c</fullName>
        <label>isFiltered</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FALSE</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>TRUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListingApplicationStatusChangeAction.cls
// *****************************************************************************
// CLASS: ListingApplicationStatusChangeAction
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 2016-11-02
// Description: Reviews if child Application Members need to be marked as duplicates
//              when the status of an Application changes to Submitted
//            
// *****************************************************************************
// MODIFICATIONS:  NOTE MOD#, DATE of mod, who made the change and description
// *****************************************************************************
// MOD1, 2016-11-16, Andu Andrei
// - replacing isDuplicateChecked__c with isFiltered__c
// - adding logic for when the Application Status changes back to Draft
// *****************************************************************************
public without sharing class ListingApplicationStatusChangeAction extends TriggerAction {

    Boolean shouldRun;
    public List<Application_Member__c> filteredApplicationMembers { get; set; }
    public List<Application_Member__c> unfilteredApplicationMembers { get; set; }
	private static string APPLICATION_SUBMITTED = 'Submitted';
    public ListingApplicationStatusChangeAction(Map<Id, SObject> triggerNewMap, Map<Id, SObject> triggerOldMap) {
        super(triggerNewMap, triggerOldMap);
        String ALTERNATE_CONTACT = API_Application.ALTERNATE_CONTACT;
        
        filteredApplicationMembers = new List<Application_Member__c>();
        unfilteredApplicationMembers = new List<Application_Member__c>();

        Set<Id> nonSubmittedApplicationIDS = new Set<Id>();
        Set<Id> submittedApplicationIDS = new Set<Id>();
        Set<Id> applicationIds = new Set<Id>();
        
        for (Id sObjId : triggerNewMap.keySet()) {
            Application__c oldApp = (Application__c)triggerOldMap.get(sObjId);
            Application__c newApp = (Application__c)triggerNewMap.get(sObjId);
			if (oldApp.Status__c == newApp.Status__c) {
				continue;
			}
            if (oldApp.Status__c == APPLICATION_SUBMITTED && newApp.Status__c != APPLICATION_SUBMITTED) {
                nonSubmittedApplicationIDS.add(sObjId);
                applicationIds.add(sObjId);
            }
            if (oldApp.Status__c != APPLICATION_SUBMITTED && newApp.Status__c == APPLICATION_SUBMITTED) {
                submittedApplicationIDS.add(sObjId);
                applicationIds.add(sObjId);
            }
        }
        
        if (applicationIds.size() > 0) {
            for (Application_Member__c am : [SELECT isFiltered__c, Type__c, Application__c FROM Application_Member__c WHERE Application__c IN :applicationIds AND Type__c != :ALTERNATE_CONTACT]) {
                if (submittedApplicationIDS.contains(am.Application__c)) {
               		unfilteredApplicationMembers.add(am);
                	
                }
                if (nonSubmittedApplicationIDS.contains(am.Application__c)) {
                 	filteredApplicationMembers.add(am);
                    
                }
            }
        }

        shouldRun = filteredApplicationMembers.size() > 0 || unfilteredApplicationMembers.size() > 0;
    }

    public override Boolean shouldRunOnInsert() { return false; }
    public override Boolean shouldRunOnDelete() { return false; } 
    public override Boolean shouldRunOnUpdate() { return shouldRun; }

    public override void doAction() {
        List<Application_Member__c> applicationMembersToUpdate = new List<Application_Member__c>();

        for (Application_Member__c am : filteredApplicationMembers) {
            am.isFiltered__c = 'TRUE';
            applicationMembersToUpdate.add(am);
        }
        for (Application_Member__c am : unfilteredApplicationMembers) {
            am.isFiltered__c = 'FALSE';
            applicationMembersToUpdate.add(am);
        }
        
        update applicationMembersToUpdate;
    }

    public static void runHandler() {
        if (trigger.isBefore && trigger.isUpdate) {
            ListingApplicationStatusChangeAction action = new ListingApplicationStatusChangeAction(Trigger.newMap, Trigger.oldMap);

            if (action.shouldRunOnUpdate()) {
                action.doAction(); 
            }
        }
    }

}