src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>COP_Preference_Manual__c</fullName>
        <description>Primary applicant holds COP - manual overrride for MSOL</description>
        <inlineHelpText>Certificate of Preference</inlineHelpText>
        <label>COP Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>COP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An related application member that holds a COP preference</description>
        <label>COP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>COP_Preference_Rank__c</fullName>
        <label>COP Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>COP_Preference__c</fullName>
        <formula>/*OLD - Replaced 8/16 based on underlying field change IF( OR(NOT(ISBLANK(COP_Preference_Member__c)),   COP_Preference_Manual__c  ) , true, false)*/


IF(
  OR(
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;Valid&apos;)),
    ISPICKVAL(COP_Preference_Manual__c, &apos;Valid - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>COP Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Manual__c</fullName>
        <description>Displaced tenant DTHP Preference Manual</description>
        <inlineHelpText>Displaced Tenant Housing Preference</inlineHelpText>
        <label>DTHP Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member that holds a DTHP preference</description>
        <label>DTHP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (DTHP Preference Member)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Rank__c</fullName>
        <label>DTHP Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK( DTHP_Preference_Member__c )),     DTHP_Preference_Manual__c    ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid&apos;)),
    ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DTHP Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference_Paper__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Live work manual preference override for msol</description>
        <label>Live/Work Preference Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference_Rank__c</fullName>
        <label>Live/Work Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Live_in_SF_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live in SF Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Live in SF Preference Member)</relationshipLabel>
        <relationshipName>Applications6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <inlineHelpText>The status of this application as related to the lottery</inlineHelpText>
        <label>Lottery Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Lottery</fullName>
                </value>
                <value>
                    <fullName>Non-Winner</fullName>
                </value>
                <value>
                    <fullName>Winner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Address__c</fullName>
        <formula>IF(NOT(ISBLANK(Neighborhood_Preference_Member__r.Street__c)),Neighborhood_Preference_Member__r.Street__c + &apos;, &apos; + Neighborhood_Preference_Member__r.City__c + &apos;, &apos; + Neighborhood_Preference_Member__r.State__c + &apos;, &apos; + Neighborhood_Preference_Member__r.Zip_Code__c, &apos;&apos;)</formula>
        <label>Neighborhood Preference Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Manual__c</fullName>
        <description>Neighborhood manual preference override for msol</description>
        <label>Neighborhood Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid Address</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Valid Address - Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member who has the neighborhood preference</description>
        <label>Neighborhood Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Neighborhood Preference Member)</relationshipLabel>
        <relationshipName>Applications3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Proof__c</fullName>
        <label>Neighborhood Preference Proof</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Telephone bill</fullName>
                </value>
                <value>
                    <fullName>Cable and internet bill</fullName>
                </value>
                <value>
                    <fullName>Gas bill</fullName>
                </value>
                <value>
                    <fullName>Electric bill</fullName>
                </value>
                <value>
                    <fullName>Garbage bill</fullName>
                </value>
                <value>
                    <fullName>Water bill</fullName>
                </value>
                <value>
                    <fullName>Paystub</fullName>
                </value>
                <value>
                    <fullName>Public benefits record</fullName>
                </value>
                <value>
                    <fullName>School record</fullName>
                </value>
                <value>
                    <fullName>Paystub with employer address</fullName>
                </value>
                <value>
                    <fullName>Letter from employer</fullName>
                </value>
                <value>
                    <fullName>Third-Party Proof of SF Homelessness</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Rank__c</fullName>
        <label>Neighborhood Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK(  Neighborhood_Preference_Member__c  )),  Neighborhood_Preference_Manual__c  ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address&apos;)),
    ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Neighborhood Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_in_SF_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work in SF Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Work in SF Preference Member)</relationshipLabel>
        <relationshipName>Applications7</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Work_in_SF_Preference_Proof__c</fullName>
        <label>Work in SF Preference Proof</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Telephone bill</fullName>
                </value>
                <value>
                    <fullName>Cable and internet bill</fullName>
                </value>
                <value>
                    <fullName>Gas bill</fullName>
                </value>
                <value>
                    <fullName>Electric bill</fullName>
                </value>
                <value>
                    <fullName>Garbage bill</fullName>
                </value>
                <value>
                    <fullName>Water bill</fullName>
                </value>
                <value>
                    <fullName>Paystub</fullName>
                </value>
                <value>
                    <fullName>Public benefits record</fullName>
                </value>
                <value>
                    <fullName>School record</fullName>
                </value>
                <value>
                    <fullName>Paystub with employer address</fullName>
                </value>
                <value>
                    <fullName>Letter from employer</fullName>
                </value>
                <value>
                    <fullName>Third-Party Proof of SF Homelessness</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Lottery Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Run</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lottery Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/zMigrationBatch.cls
global class zMigrationBatch implements Database.Batchable<sObject>, Database.Stateful {
    String query;
	Set<Id> listingIds;
	Date startDate;
	Date endDate;
    List<Application__c> appsToUpdate;
    
    // Count the number of applications processed
    Integer count;
	
    global zMigrationBatch(Set<Id> listingIds, Date startDate, Date endDate) {
    	this.listingIds = listingIds;
    	this.startDate = startDate;
    	this.endDate = endDate;
        
        count = 0;
        appsToUpdate = new List<Application__c>();
        
		
		if (listingIds == null || listingIds.size() == 0) {
			Map<ID,Listing__c> allListingMap = new Map<ID,Listing__c>([SELECT Id FROM Listing__c WHERE Lottery_Status__c = 'Lottery Complete']);
			listingIds = allListingMap.keySet();
		}
		

	
    	
    	query = 'Select id, Listing__c,DTHP_Preference_Member__c,DTHP_Preference_Manual__c,DTHP_Preference_Rank__c, Is_Migrated__c,';
		query += 'DTHP_Opt_Out__c,DTHP_Preference__c,Neighborhood_Preference_Member__c,Neighborhood_Preference_Manual__c,';
		query += 'Neighborhood_Preference_Rank__c,NRHP_Opt_Out__c,Neighborhood_Preference_Proof__c,Neighborhood_Preference__c,';
		query += 'Neighborhood_Preference_Address__c,COP_Preference_Member__c,COP_Preference_Manual__c,COP_Preference_Rank__c,';
		query += 'COP_Opt_Out__c,COP_Preference__c,Live_in_SF_Preference_Member__c,Live_Work_Preference_Paper__c, Work_in_SF_Preference_Proof__c, Work_in_SF_Preference_Member__c, ';
		query += 'Live_Work_Preference_Rank__c,Live_Work_Opt_Out__c,Live_in_SF_Preference_Proof__c,Live_Work_Preference__c ';
		query += 'From Application__c where Listing__c in :listingIds AND Listing__r.Lottery_Status__c = \'Lottery Complete\'';
		if (startDate != null) {
			query += ' AND CreatedDate >= :startDate';
		}
		if (endDate != null) {
			query += ' AND CreatedDate <= :endDate';
		}
		system.debug('query:::' + query);
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
    	return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Application__c> scope) {
		system.debug('scope:::' + scope);
        List<Application__c> migrationAppList = new List<Application__c>();
        
        for(Application__c app : scope)
            if(app.Is_Migrated__c == false) {
            	migrationAppList.add(app);
                
                app.Is_Migrated__c = true;
                appsToUpdate.add(app);
            }
        
        count += migrationAppList.size();
        zMigrationScript.createApplicationPreference(migrationAppList);
        
        //Update the migrated field on apps
        update appsToUpdate; 
        
	}
	
	global void finish(Database.BatchableContext BC) {
        

        
       // Send a mail after the applications have been processed 
       List<Messaging.SingleEmailMessage> emails = new List<Messaging.SingleEmailMessage>();
       Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();
       List<String> toAddress = new List<String>();
       toAddress.add('donna.nguyen@vertiba.com');
        toAddress.add('nishchith.hebbar@vertiba.com');
       email.setToAddresses(toAddress);
       email.setSubject('Migration complete');
       email.setHtmlBody('The migration script has run successfully. ' + count + ' Application(s) have been processed.');
       emails.add(email);
       Messaging.sendEmail(emails);
        
	}
}