src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <description>Primary applicant date of birth</description>
        <formula>Applicant__r.Date_of_Birth__c</formula>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Primary applicant first name</description>
        <formula>Applicant__r.First_Name__c</formula>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Primary applicant last name</description>
        <formula>Applicant__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Application_Households</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Preference__c.object
<CustomObject>
    <description>Stores a &quot;snapshot in time&quot; of which preferences were claimed or opted-out of for each application, and any related application members (household members), if applicable.</description>
    <fields>
        <fullName>Application_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Application Member Number</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>$Source.Application__c</field>
                <operation>equals</operation>
                <valueField>Application_Member__c.Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application__c</fullName>
        <description>The related Application that this preference was saved for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Listing_Preference_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing Preference Number</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Preference</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing_Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The listing for this object</description>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Preference__c</fullName>
        <label>Preference</label>
        <referenceTo>Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Submitted_Apps__c</fullName>
        <label>Total Submitted App</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Listing Preference</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Listing Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of this preference</description>
        <inlineHelpText>Enter the current status of this preference</inlineHelpText>
        <label>XStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Old</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ListingAppPreferenceRollupActionTest.cls
@isTest
public class ListingAppPreferenceRollupActionTest {
	
    static testMethod void appPrefTriggerTest() {
        Account someAccount = new Account(Name = 'someAccount');
        insert someAccount;
        
        Listing__c someListing = new Listing__c(Name = 'someListing', Account__c = someAccount.Id);
        insert someListing;
        
        Application__c someApplication = new Application__c(Listing__c = someListing.Id, Status__c =  'Submitted');
        insert someApplication;
        
        Application_Member__c householdMember = new Application_Member__c(	Application__c = someApplication.Id,
                                                                          First_Name__c = 'Household', Last_Name__c = 'Member', Date_of_Birth__c = Date.today());
        insert householdMember;
        
        Lottery_Preference__c lotPref = new Lottery_Preference__c(Name = 'Neighborhood Resident Housing Preference (NRHP)');
        insert lotPref;
        
        Listing_Lottery_Preference__c listingPref = new Listing_Lottery_Preference__c(Listing__c = someListing.Id, Lottery_Preference__c = lotPref.Id);
        insert listingPref;
        
        Test.startTest();
        
        	Application_Preference__c appPref = new Application_Preference__c(Application__c = someApplication.Id, Listing_Preference_ID__c = listingPref.Id, Application_Member__c = householdMember.Id);
            List<Application_Preference__c> appPrefs = new List<Application_Preference__c>{appPref};
            insert appPrefs;
        	
        	listingPref = [SELECT Id, Total_Submitted_Apps__c FROM Listing_Lottery_Preference__c where Id = :listingPref.Id];
        	System.assertEquals(listingPref.Total_Submitted_Apps__c, 1);
        	
        	delete appPref;
        	listingPref = [SELECT Id, Total_Submitted_Apps__c FROM Listing_Lottery_Preference__c where Id = :listingPref.Id];
        	System.assertEquals(listingPref.Total_Submitted_Apps__c, 0);
        
            ListingApplicationPreferenceRollupAction trg = new ListingApplicationPreferenceRollupAction(new List<Application_Preference__c>{appPref});
            boolean del = trg.shouldRunOnDelete();
            boolean ins = trg.shouldRunOnInsert();
            boolean upd = trg.shouldRunOnUpdate();
        	
        Test.stopTest();
    }
}