src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Is_Application_Draft__c</fullName>
        <formula>ISPICKVAL(Application__r.Status__c, &quot;Draft&quot;)</formula>
        <label>Is Application Draft</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Applicant</fullName>
                </value>
                <value>
                    <fullName>Alternate Contact</fullName>
                </value>
                <value>
                    <fullName>Household Member</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>isFiltered__c</fullName>
        <label>isFiltered</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>FALSE</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>TRUE</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListingApplicationMemberDuplicateAction.cls
// *****************************************************************************
// CLASS: ListingApplicationMemberDuplicateAction
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 2016-11-01
// Description: Marks Application Members as duplicates if they match a certain condition
//            
// *****************************************************************************
// MODIFICATIONS:  NOTE MOD#, DATE of mod, who made the change and description
// *****************************************************************************
// MOD1, 2016-11-16, Andu Andrei - replacing isDuplicateChecked__c with isFiltered__c
// *****************************************************************************
public without sharing class ListingApplicationMemberDuplicateAction extends TriggerAction {

    Boolean shouldRun;
    public List<Application_Member__c> isFilteredTrue { get; set; }
    public List<Application_Member__c> isFilteredFalse { get; set; }

    public ListingApplicationMemberDuplicateAction(List<SObject> triggerList) {
        super(triggerList);
        isFilteredTrue = new List<Application_Member__c>();
        isFilteredFalse = new List<Application_Member__c>();

        for (SObject sObj : triggerList) {
            Application_Member__c am = (Application_Member__c)sObj;
            if (am.Type__c == API_Application.ALTERNATE_CONTACT || am.Is_Application_Draft__c == true) {
                isFilteredTrue.add(am);
            }
            else isFilteredFalse.add(am);
        }
            
        shouldRun = true;
    }

    public override Boolean shouldRunOnInsert() { return shouldRun; }
    public override Boolean shouldRunOnDelete() { return false; } 
    public override Boolean shouldRunOnUpdate() { return shouldRun; }

    public override void doAction() {
        for (Application_Member__c am : isFilteredTrue) {
            am.isFiltered__c = 'TRUE';
        }
         for (Application_Member__c am : isFilteredFalse) {
            am.isFiltered__c = 'FALSE';
        }
    }

    public static void runHandler() {
        if (trigger.isBefore && trigger.isInsert) {
            ListingApplicationMemberDuplicateAction action = new ListingApplicationMemberDuplicateAction(Trigger.new);

            if (action.shouldRunOnInsert()) {
                action.doAction(); 
            }
        }
         if (trigger.isBefore && trigger.isUpdate) {
            ListingApplicationMemberDuplicateAction action = new ListingApplicationMemberDuplicateAction(Trigger.new);

            if (action.shouldRunOnUpdate()) {
                action.doAction(); 
            }
        }
    }

}