src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Preference__c.object
<CustomObject>
    <description>Stores a &quot;snapshot in time&quot; of which preferences were claimed or opted-out of for each application, and any related application members (household members), if applicable.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The related Application that this preference was saved for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Auto_Grants_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>parent application preference</description>
        <label>Auto Grant Preference</label>
        <referenceTo>Application_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing_ID__c</fullName>
        <formula>Application__r.Listing__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Listing ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing_Preference_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing Preference Number</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Preference</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Developer for the Building.</description>
        <inlineHelpText>Developer for the Building.</inlineHelpText>
        <label>Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development__c</fullName>
        <description>Development for the property</description>
        <inlineHelpText>Development for the property</inlineHelpText>
        <label>Development</label>
        <referenceTo>Development__c</referenceTo>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Development__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MOHCD Project ID</label>
        <type>Text</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Property Auto-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Development__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Developer who is responsible for this development.</description>
        <label>Developer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be a developer</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Property Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Developments</relationshipLabel>
        <relationshipName>Developments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_Development__c</fullName>
        <label>Name of Development</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Development</label>
    <nameField>
        <displayFormat>DVL-{000000}</displayFormat>
        <label>Development Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <description>Name of the Developer for the Building.</description>
        <formula>Building__r.Developer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of the Developer for the Building.</inlineHelpText>
        <label>Developer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Does_Match__c</fullName>
        <defaultValue>false</defaultValue>
        <description>UNUSED hidden field which we use for service level translation</description>
        <label>Does Match</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Building__r.Development__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing_Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Grants_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auto Grant Preference</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The listing for this object</description>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Preference__c</fullName>
        <label>Preference</label>
        <referenceTo>Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Listing Preference</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Listing Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of this preference</description>
        <inlineHelpText>Enter the current status of this preference</inlineHelpText>
        <label>XStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Old</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ApplicationPrefSetAutoGrantActionTest.cls
@isTest
public class ApplicationPrefSetAutoGrantActionTest {
	  static testMethod void ApplicationPrefSetAutoGrantActionTest() {  
          Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
          Account acc = new Account();
          acc.Name = 'Test Account';
          acc.RecordTypeId = rtId;
          acc.AccountNumber = '12345';
          insert acc;
          
          Development__c dev = new Development__c();
          dev.Name_of_Development__c = 'amli';
          dev.Project_ID__c = '123';
          insert dev;
          
          Building__c build = new Building__c();
          build.Development__c = dev.Id;
          build.Developer__c = acc.Id;
          insert build;
          
          Listing__c listing = new Listing__c();
          listing.name='somelisting';
          listing.Building__c  = build.id;
          listing.Account__c = acc.Id;
          listing.Status__c = 'Active';
          listing.Does_Match__c = true;
          insert listing;
          
          Lottery_Preference__c lp = new Lottery_Preference__c(Name='Live or Work in San Francisco Preference');
          insert lp;
          Lottery_Preference__c lp2 = new Lottery_Preference__c(Name='Neighborhood Resident Housing Preference (NRHP)',Auto_Grants_Preference__c=lp.Id);
          insert lp2;
          
          Listing_Lottery_Preference__c llp1 = new Listing_Lottery_Preference__c();
          llp1.Listing__c = listing.id;
          llp1.Lottery_Preference__c = lp2.Id;
          insert llp1;
          
          Listing_Lottery_Preference__c llp = new Listing_Lottery_Preference__c();
          llp.Listing__c = listing.id;
          llp.Lottery_Preference__c = lp.Id;
          insert llp;
          
          Application__c app = new Application__c();
          app.Listing__c = listing.Id;
          insert app;
          
          Test.startTest();
              List<Application_Preference__c> appPrefs = [SELECT Id, Auto_Grants_Preference__c, Listing_Preference_ID__c, Application__c, Listing_ID__c FROM Application_Preference__c];
              for (Application_Preference__c appPref : appPrefs) {
                  if (appPref.Listing_Preference_ID__c == llp.Id) {
                      system.assert(appPref.Auto_Grants_Preference__c == null);
                  }
                  if (appPref.Listing_Preference_ID__c == llp1.Id) {
                      system.assert(appPref.Auto_Grants_Preference__c != null);
                  }
              }
              
          	  /*Application_Preference__c appPref1 = new Application_Preference__c();
              appPref1.Application__c = app.Id;
              appPref1.Listing_Preference_ID__c = llp1.Id;
              insert appPref1;
          
              appPref1 = [SELECT Id, Auto_Grants_Preference__c FROM Application_Preference__c WHERE Id = :appPref1.Id];
              system.assert(appPref1.Auto_Grants_Preference__c == appPref.Id);
          
              delete appPref;
              appPref1 = [SELECT Id, Auto_Grants_Preference__c FROM Application_Preference__c WHERE Id = :appPref1.Id];
              system.assert(appPref1.Auto_Grants_Preference__c == NULL);
              delete appPref1;
          
              appPref1 = new Application_Preference__c();
              appPref1.Application__c = app.Id;
              appPref1.Listing_Preference_ID__c = llp1.Id;
              insert appPref1;
          
              appPref1 = [SELECT Id, Auto_Grants_Preference__c FROM Application_Preference__c];
              system.assert(appPref1.Auto_Grants_Preference__c == null);
              
              appPref = new Application_Preference__c();
              appPref.Application__c = app.Id;
              appPref.Listing_Preference_ID__c = llp.Id;
              insert appPref;
          
              appPref1 = [SELECT Id, Auto_Grants_Preference__c FROM Application_Preference__c WHERE Id = :appPref1.Id];
              system.assert(appPref1.Auto_Grants_Preference__c == appPref.Id);
          
              appPref1.Auto_Grants_Preference__c = null;
              update appPref1;
              appPref1 = [SELECT Id, Auto_Grants_Preference__c, Application__c, Listing_ID__c FROM Application_Preference__c WHERE Id = :appPref1.Id];
              system.assert(appPref1.Auto_Grants_Preference__c == appPref.Id);*/
          
              ApplicationPreferenceSetAutoGrantAction trg = new ApplicationPreferenceSetAutoGrantAction(new List<Application_Preference__c>{appPrefs[0]});
              boolean del = trg.shouldRunOnDelete();
              boolean ins = trg.shouldRunOnInsert();
              boolean upd = trg.shouldRunOnUpdate();
          Test.stopTest();
    }
}