src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Rank__c</fullName>
        <description>Returned lottery number rank</description>
        <label>Lottery Rank (Unsorted)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <inlineHelpText>The status of this application as related to the lottery</inlineHelpText>
        <label>Lottery Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Lottery</fullName>
                </value>
                <value>
                    <fullName>Non-Winner</fullName>
                </value>
                <value>
                    <fullName>Winner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Preference__c.object
<CustomObject>
    <description>Stores a &quot;snapshot in time&quot; of which preferences were claimed or opted-out of for each application, and any related application members (household members), if applicable.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The related Application that this preference was saved for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Listing_Preference_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing Preference Number</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Pre-Lottery Validation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid for lottery</fullName>
                </value>
                <value>
                    <fullName>Invalid for lottery</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
                <value>
                    <fullName>Does not receive preference</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Needs pre-lottery validation</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Receives preference</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Preference_Lottery_Rank__c</fullName>
        <label>Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Receives_Preference__c</fullName>
        <formula>OR(
Auto_Grant_Count__c &gt; 0,
AND(NOT(ISBLANK(Application_Member__c)), NOT(ISPICKVAL(Lottery_Status__c, &apos;Invalid for lottery&apos;))), 
ISPICKVAL(Lottery_Status__c, &apos;Valid - Added&apos;)
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Receives Preference</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Preference</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Lottery Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Run</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lottery Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LOT_ApplicationPreferenceRankBatch.cls
global class LOT_ApplicationPreferenceRankBatch implements Database.Batchable<sObject>, Database.Stateful {

    String query;
	Integer preferedRank;
    Id listingId;
	public LOT_PreferenceRankBatch nextBatch;

	
	global LOT_ApplicationPreferenceRankBatch(Id listingId) {
		this.preferedRank = 1;
		this.listingId = listingId;
        
		query = 'select id ,Listing_Preference_ID__c, Application__c, Receives_Preference__c, Application__r.Lottery_Rank__c from Application_Preference__c where Application__r.listing__c = \'' + listingId + '\' AND Application__r.Status__c = \'Submitted\' order by Listing_Preference_ID__c, Application__r.Lottery_Rank__c';
		system.debug('query:::' + query);
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Application_Preference__c> scope) {
		system.debug('scope:::' + scope);
        calculateRank(scope);
	}
	
	global void finish(Database.BatchableContext BC) {
        system.debug('nextBatch:::' + nextBatch);
        if (nextBatch != null){
        	Database.executeBatch(nextBatch);
        } else {
        	Listing__c listing = new Listing__c(Id=listingId);
	        /*if(preferedRank > 0){
	            //Listing__c listing = new Listing__c(Id=listingId);
	            listing.put(totalField,preferedRank);
	            //update listing;
	        }*/
        	listing.Lottery_Status__c = 'Lottery Complete';
	        update listing;
        }
	}

	public void calculateRank(List<Application_Preference__c> scope){
		ID currentListingPreferenceID = scope[0].Listing_Preference_ID__c;
		system.debug('scope:::' + scope.size());
   		for (Application_Preference__c appPref : scope) {
   			if (appPref.Listing_Preference_ID__c != currentListingPreferenceID) {
   				currentListingPreferenceID = appPref.Listing_Preference_ID__c;
   				preferedRank = 1;
   			}
   			if (appPref.Receives_Preference__c == true) {
   				appPref.Preference_Lottery_Rank__c = preferedRank++;
   			} else {
   				appPref.Preference_Lottery_Rank__c = null;
   			}
            system.debug('appPref:::' + appPref);
   		}
   		update scope;
	}
}