src/objects/Application_Preference__c.object
<CustomObject>
    <description>Stores a &quot;snapshot in time&quot; of which preferences were claimed or opted-out of for each application, and any related application members (household members), if applicable.</description>
    <fields>
        <fullName>Application_Is_Submitted__c</fullName>
        <formula>ISPICKVAL( Application__r.Status__c , &apos;Submitted&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Application Submitted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listing_Preference_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing Preference Number</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application Preference</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing_Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Total_Submitted_Apps__c</fullName>
        <label>Total Submitted App</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Listing Preference</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Listing Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListingApplicationPreferenceRollupAction.cls
public class ListingApplicationPreferenceRollupAction extends TriggerAction{
    
    private Set<ID> listingPrefIds;
 	public ListingApplicationPreferenceRollupAction (List<SObject> appPrefs) {
		
		super(appPrefs);
		listingPrefIds = new Set<ID> ();
		for (Sobject sobj: appPrefs) {
			Application_Preference__c appPref = (Application_Preference__c) sobj;
			listingPrefIds.add(appPref.Listing_Preference_ID__c);	
		}
	 
	}
	
	public override boolean shouldRunOnInsert() {
		if (listingPrefIds.size()>0) {
			return true;		
		}
		else return false;
		
	}
	public override boolean shouldRunOnDelete() { 
		if (listingPrefIds.size()>0) {
			return true;		
		}
		else return false;
	
	} 
	public override boolean shouldRunOnUpdate() {
		if (listingPrefIds.size()>0) {
			return true;		
		}
		else return false;
	
		
	} 
	
	private class total {
		ID listingPrefID;
		Integer appSubmittedTotal;
		Integer appTotal;
		
	}
	public override void doAction() {
		
	
	//	AggregateResult[] totalAppResults = [SELECT  i.Listing_Preference_ID__c, COUNT(i.id)appCount FROM Application_Preference__c i where i.Listing_Preference_ID__c in :listingPrefIds GROUP BY i.Listing_Preference_ID__c];
		
	 	AggregateResult[] totalSubmittedAppResults = [SELECT  a.Listing_Preference_ID__c, COUNT(a.id)appCount FROM Application_Preference__c a where a.Listing_Preference_ID__c in :listingPrefIds and Application_Is_Submitted__c =true GROUP BY a.Listing_Preference_ID__c];
	 
	 	Map<ID,Listing_Lottery_Preference__c> listingPrefMap = new Map<ID,Listing_Lottery_Preference__c>();
		for (AggregateResult result: totalSubmittedAppResults) {
			Id listingPrefID = (Id)result.get('Listing_Preference_ID__c');
			Integer appCount = (Integer)result.get('appCount');
			Listing_Lottery_Preference__c listingPref =  (!listingPrefMap.containsKey(listingPrefID)) ? new Listing_Lottery_Preference__c(ID = listingPrefID): listingPrefMap.get(listingPrefID);
			listingPref.Total_Submitted_Apps__c = appCount;
			listingPrefMap.put(listingPrefID,listingPref);
		}
        
        //when deleting last appPref previous for is never executed and listingPrefs are not updated correctly
        for (Id listingPrefId : listingPrefIds) {
            if (!listingPrefMap.containsKey(listingPrefId)) {
                listingPrefMap.put(listingPrefID,new Listing_Lottery_Preference__c(ID = listingPrefID, Total_Submitted_Apps__c = 0));
            }
        }
		/*
		for (AggregateResult result: totalAppResults) {
			Id listingPrefID = (Id)result.get('Listing_Preference_ID__c');
			Integer appCount = (Integer)result.get('appCount');
			Listing_Lottery_Preference__c listingPref =  (!listingPrefMap.containsKey(listingPrefID)) ? new Listing_Lottery_Preference__c(ID = listingPrefID): listingPrefMap.get(listingPrefID);
			listingPref.Total_Apps__c = appCount;
			listingPrefMap.put(listingPrefID,listingPref);
			
		}*/
		if (listingPrefMap.keyset().size()>0) {
			update listingPrefMap.values();
		}
	
	}
  	public static void runHandler() {
        if (trigger.isAfter && (trigger.isUpdate || trigger.isInsert)){
        	ListingApplicationPreferenceRollupAction action = new ListingApplicationPreferenceRollupAction(Trigger.new);
            action.doAction(); 
            return;
        }
        if (trigger.isAfter && (trigger.isDelete)){
        	ListingApplicationPreferenceRollupAction action = new ListingApplicationPreferenceRollupAction(Trigger.old);
	        action.doAction(); 
	        return;
        	
        }
        
       
    }
}