src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>COP_Preference_Manual__c</fullName>
        <description>Primary applicant holds COP - manual overrride for MSOL</description>
        <inlineHelpText>Certificate of Preference</inlineHelpText>
        <label>COP Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>COP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An related application member that holds a COP preference</description>
        <label>COP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>COP_Preference_Rank__c</fullName>
        <label>COP Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Manual__c</fullName>
        <description>Displaced tenant DTHP Preference Manual</description>
        <inlineHelpText>Displaced Tenant Housing Preference</inlineHelpText>
        <label>DTHP Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member that holds a DTHP preference</description>
        <label>DTHP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (DTHP Preference Member)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Rank__c</fullName>
        <label>DTHP Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK( DTHP_Preference_Member__c )),     DTHP_Preference_Manual__c    ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid&apos;)),
    ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DTHP Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Address__c</fullName>
        <formula>IF(NOT(ISBLANK(Neighborhood_Preference_Member__r.Street__c)),Neighborhood_Preference_Member__r.Street__c + &apos;, &apos; + Neighborhood_Preference_Member__r.City__c + &apos;, &apos; + Neighborhood_Preference_Member__r.State__c + &apos;, &apos; + Neighborhood_Preference_Member__r.Zip_Code__c, &apos;&apos;)</formula>
        <label>Neighborhood Preference Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Manual__c</fullName>
        <description>Neighborhood manual preference override for msol</description>
        <label>Neighborhood Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid Address</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Valid Address - Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member who has the neighborhood preference</description>
        <label>Neighborhood Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Neighborhood Preference Member)</relationshipLabel>
        <relationshipName>Applications3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Proof__c</fullName>
        <label>Neighborhood Preference Proof</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Telephone bill</fullName>
                </value>
                <value>
                    <fullName>Cable and internet bill</fullName>
                </value>
                <value>
                    <fullName>Gas bill</fullName>
                </value>
                <value>
                    <fullName>Electric bill</fullName>
                </value>
                <value>
                    <fullName>Garbage bill</fullName>
                </value>
                <value>
                    <fullName>Water bill</fullName>
                </value>
                <value>
                    <fullName>Paystub</fullName>
                </value>
                <value>
                    <fullName>Public benefits record</fullName>
                </value>
                <value>
                    <fullName>School record</fullName>
                </value>
                <value>
                    <fullName>Paystub with employer address</fullName>
                </value>
                <value>
                    <fullName>Letter from employer</fullName>
                </value>
                <value>
                    <fullName>Third-Party Proof of SF Homelessness</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Rank__c</fullName>
        <label>Neighborhood Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK(  Neighborhood_Preference_Member__c  )),  Neighborhood_Preference_Manual__c  ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address&apos;)),
    ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Neighborhood Preference</label>
        <type>Checkbox</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Application_Households</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Neighborhood Preference</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Preference__c.object
<CustomObject>
    <description>Stores a &quot;snapshot in time&quot; of which preferences were claimed or opted-out of for each application, and any related application members (household members), if applicable.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The related Application that this preference was saved for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Auto_Grants_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>parent application preference</description>
        <label>Auto Grant Preference</label>
        <referenceTo>Application_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Opt_Out__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If user actively opted-out of this preference, the relationship will be created and this box will be checked. May or may not have a related application member. Status will remain blank.</description>
        <label>Applicant Opted Out</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Preference_Name__c</fullName>
        <formula>Listing_Preference_ID__r.Preference_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preference</label>
        <type>Text</type>
    </fields>
    <label>Application Preference</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing_Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Grants_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auto Grant Preference</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The listing for this object</description>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Preference__c</fullName>
        <label>Preference</label>
        <referenceTo>Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Preference_Name__c</fullName>
        <formula>Lottery_Preference__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Preference Name</label>
        <type>Text</type>
    </fields>
    <label>Listing Preference</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Listing Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/zMigrationScript.cls
public with sharing class zMigrationScript {
	private static final String LIVE_WORK_PREFERENCE_NAME = 'Live or Work in San Francisco Preference';
	private static final String COP_PREFERENCE_NAME = 'Certificate of Preference (COP)';
	private static final String DTHP_PREFERENCE_NAME = 'Displaced Tenant Housing Preference (DTHP)';
	private static final String NEIGHBORHOOD_PREFERENCE_NAME = 'Neighborhood Resident Housing Preference (NRHP)';

	//returns a map<listingid, map<preferenceID, listingLotteryPreference>
	private static Map<ID,Map<ID,Listing_Lottery_Preference__c>> getListingLotteryPreferences(Set<ID> listingIDS) {
		Map<ID,Map<ID,Listing_Lottery_Preference__c>> listingPrefMap = new Map<ID,Map<ID,Listing_Lottery_Preference__c>>();
		List< Listing_Lottery_Preference__c> prefList = [Select id, Name, Listing__c,Auto_Grants_Preference__c, Lottery_Preference__c, Preference_Name__c From Listing_Lottery_Preference__c where Listing__c in :listingIDS];
		for (Listing_Lottery_Preference__c lotPref:  prefList) {
			Map<ID,Listing_Lottery_Preference__c> listingLotteryPrefMap  = (listingPrefMap.containsKey(lotPref.Listing__c))? listingPrefMap.get(lotPref.Listing__c) : new  Map<ID,Listing_Lottery_Preference__c>();
			listingLotteryPrefMap.put(lotPref.Lottery_Preference__c,lotPref);
			listingPrefMap.put(lotPref.Listing__c,listingLotteryPrefMap);
		}
		return listingPrefMap;
	}

	//returns a map<listingid, map<id, applications>
	private static Map<ID,Map<ID,Application__c>> getApplicationsMap(List<Application__c> appList) {
		Map<ID,Map<ID,Application__c>> listingAppMap = new Map<ID,Map<ID,Application__c>>();
		//update this
		/*List<Application__c> appList = [Select id, Listing__c,DTHP_Preference_Member__c,DTHP_Preference_Manual__c,DTHP_Preference_Rank__c,
										DTHP_Opt_Out__c,DTHP_Preference__c,Neighborhood_Preference_Member__c,Neighborhood_Preference_Manual__c,
										Neighborhood_Preference_Rank__c,NRHP_Opt_Out__c,Neighborhood_Preference_Proof__c,Neighborhood_Preference__c,
										Neighborhood_Preference_Address__c,COP_Preference_Member__c,COP_Preference_Manual__c,COP_Preference_Rank__c,
										COP_Opt_Out__c,COP_Preference__c,Live_in_SF_Preference_Member__c,Live_Work_Preference_Paper__c,
										Live_Work_Preference_Rank__c,Live_Work_Opt_Out__c,Live_in_SF_Preference_Proof__c,Live_Work_Preference__c
										From Application__c where Listing__c in :listingIDS];
		*/
		for (Application__c app:  appList) {
			Map<ID,Application__c> appMap  = (listingAppMap.containsKey(app.Listing__c))? listingAppMap.get(app.Listing__c) : new  Map<ID,Application__c>();
			appMap.put(app.id,app);
			listingAppMap.put(app.Listing__c,appMap);
		}
		return listingAppMap;
	}

	public static void createApplicationPreference(List<Application__c> appList) {
		Set<Id> listingIds = new Set<Id>();
		for (Application__c app : appList) {
			listingIds.add(app.Listing__c);
		}

		Map<ID,Listing__c> allListingMap = new Map<ID,Listing__c>([SELECT Id FROM Listing__c WHERE Id IN :listingIds]);

		Map<ID,Map<ID,Application__c>> appMap  = getApplicationsMap(appList);
		Map<ID,Map<ID,Listing_Lottery_Preference__c>> prefMap =  getListingLotteryPreferences(allListingMap.keySet());

		List<Application_Preference__c> appPrefList = new List<Application_Preference__c>();
		for (ID listingId : allListingMap.keyset()) {
			for (ID lotteryPrefId : prefMap.get(listingId).keySet()) {
				if (appMap.get(listingId) == null || appMap.get(listingId).isEmpty()) {
					continue;
				}
				for (Id appId : appMap.get(listingId).keySet()) {
					Application__c currentApp = appMap.get(listingId).get(appId);
					appPrefList.add(buildApplicationPreference(prefMap.get(listingId).get(lotteryPrefId),currentApp));
				}
			}
		}
		if (appPrefList.size() > 0) {
			insert appPrefList;
		}
	}

	private static Application_Preference__c buildApplicationPreference(Listing_Lottery_Preference__c listingPref, Application__c currentApp) {
		Application_Preference__c newAppPref = new Application_Preference__c();

		newAppPref.Application__c = currentApp.Id;
		newAppPref.Listing_Preference_ID__c = listingPref.Id;

		if (listingPref.Preference_Name__c == DTHP_PREFERENCE_NAME) {
			newAppPref.Application_Member__c = currentApp.DTHP_Preference_Member__c;
			newAppPref.Lottery_Status__c = (currentApp.DTHP_Preference_Manual__c == 'Valid' ? 'Valid for lottery' : currentApp.DTHP_Preference_Manual__c == 'Invalid' ? 'Invalid for lottery' : currentApp.DTHP_Preference_Manual__c);
			newAppPref.Preference_Lottery_Rank__c = currentApp.DTHP_Preference_Rank__c;
			newAppPref.Opt_Out__c = currentApp.DTHP_Opt_Out__c;
			//newAppPref.Type_of_proof__c = currentApp.;
			//newAppPref.Receives_Preference__c = currentApp.DTHP_Preference__c;//formula field
		} else if (listingPref.Preference_Name__c == NEIGHBORHOOD_PREFERENCE_NAME) {
			newAppPref.Application_Member__c = currentApp.Neighborhood_Preference_Member__c;
			newAppPref.Lottery_Status__c = (currentApp.Neighborhood_Preference_Manual__c == 'Valid Address' ? 'Valid for lottery' : currentApp.Neighborhood_Preference_Manual__c == 'Invalid Address' ? 'Invalid for lottery' : currentApp.Neighborhood_Preference_Manual__c != null ? currentApp.Neighborhood_Preference_Manual__c.replace('Address ','') : currentApp.Neighborhood_Preference_Manual__c);
			newAppPref.Preference_Lottery_Rank__c = currentApp.Neighborhood_Preference_Rank__c;
			newAppPref.Opt_Out__c = currentApp.NRHP_Opt_Out__c;
			newAppPref.Type_of_proof__c = currentApp.Neighborhood_Preference_Proof__c;
			//newAppPref.Receives_Preference__c = currentApp.Neighborhood_Preference__c;//formula field
		} else if (listingPref.Preference_Name__c == COP_PREFERENCE_NAME) {
			newAppPref.Application_Member__c = currentApp.COP_Preference_Member__c;
			newAppPref.Lottery_Status__c = (currentApp.COP_Preference_Manual__c == 'Valid' ? 'Valid for lottery' : currentApp.COP_Preference_Manual__c == 'Invalid' ? 'Invalid for lottery' : currentApp.COP_Preference_Manual__c);
			newAppPref.Preference_Lottery_Rank__c = currentApp.COP_Preference_Rank__c;
			newAppPref.Opt_Out__c = currentApp.COP_Opt_Out__c;
			//newAppPref.Type_of_proof__c = currentApp.;
			//newAppPref.Receives_Preference__c = currentApp.COP_Preference__c;//formula field
		} else if (listingPref.Preference_Name__c == LIVE_WORK_PREFERENCE_NAME) {
            if(currentApp.Live_in_SF_Preference_Member__c == null) {
                if(currentApp.Work_in_SF_Preference_Member__c != null) {
                newAppPref.Application_Member__c = currentApp.Work_in_SF_Preference_Member__c;
                newAppPref.Type_of_proof__c = currentApp.Work_in_SF_Preference_Proof__c;
                newAppPref.If_combined_individual_preference__c = 'Work in SF';
                newAppPref.Lottery_Status__c = currentApp.Live_Work_Preference_Paper__c ? 'None' : null;
                newAppPref.Preference_Lottery_Rank__c = currentApp.Live_Work_Preference_Rank__c;
                newAppPref.Opt_Out__c = currentApp.Live_Work_Opt_Out__c;
            }
                else {
                	newAppPref.Preference_Lottery_Rank__c = currentApp.Live_Work_Preference_Rank__c;
                	newAppPref.Opt_Out__c = currentApp.Live_Work_Opt_Out__c;
                    if(currentApp.Neighborhood_Preference__c || currentApp.DTHP_Preference__c)
                        newAppPref.Lottery_Status__c = currentApp.Live_Work_Preference_Paper__c ? 'None' : null;
                    else newAppPref.MOHCD_Preference_Assertion__c = currentApp.Live_Work_Preference_Paper__c ? 'Valid for lottery' : '';
                }
            }
            else if(currentApp.Live_in_SF_Preference_Member__c != null){
			newAppPref.Application_Member__c = currentApp.Live_in_SF_Preference_Member__c;
			newAppPref.Lottery_Status__c = currentApp.Live_Work_Preference_Paper__c ? 'None' : null;
			newAppPref.Preference_Lottery_Rank__c = currentApp.Live_Work_Preference_Rank__c;
            newAppPref.If_combined_individual_preference__c = 'Live in SF';
			newAppPref.Opt_Out__c = currentApp.Live_Work_Opt_Out__c;
			newAppPref.Type_of_proof__c = currentApp.Live_in_SF_Preference_Proof__c;
			//newAppPref.Receives_Preference__c = currentApp.Live_Work_Preference__c;//formula field
            }
		}
		return newAppPref;
	}



	/*



for each listing -

	appmap  = getApplicationsForListing()
	prefMap =  getlistingPreferenceForListing
	for each listingPreference {


		for each application  {

			create new AppPref(listingpref, application, appMember, status);
		}



	}

listingPref.name =
create new AppPref(listingpref, application, appMember, status) {
	if listingPref.name = 'dthp'
		fill in these values
		return
	else COP {

	}

}


	*/
}