src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>COP_Preference_Rank__c</fullName>
        <label>COP Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>COP_Preference__c</fullName>
        <formula>/*OLD - Replaced 8/16 based on underlying field change IF( OR(NOT(ISBLANK(COP_Preference_Member__c)),   COP_Preference_Manual__c  ) , true, false)*/


IF(
  OR(
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;Valid&apos;)),
    ISPICKVAL(COP_Preference_Manual__c, &apos;Valid - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>COP Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Rank__c</fullName>
        <label>DTHP Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK( DTHP_Preference_Member__c )),     DTHP_Preference_Manual__c    ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid&apos;)),
    ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DTHP Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>General_Lottery_Rank__c</fullName>
        <label>General Lottery Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>General_Lottery__c</fullName>
        <formula>NOT(OR(DTHP_Preference__c,Live_Work_Preference__c,COP_Preference__c, Neighborhood_Preference__c ))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>General Lottery</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference_Rank__c</fullName>
        <label>Live/Work Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference__c</fullName>
        <formula>IF( OR(NOT(ISBLANK(Live_in_SF_Preference_Member__c)), NOT(ISBLANK(Work_in_SF_Preference_Member__c)), Live_Work_Preference_Paper__c  ) , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Live/Work Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lottery_Rank__c</fullName>
        <description>Returned lottery number rank</description>
        <label>Lottery Rank (Unsorted)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <inlineHelpText>The status of this application as related to the lottery</inlineHelpText>
        <label>Lottery Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Lottery</fullName>
                </value>
                <value>
                    <fullName>Non-Winner</fullName>
                </value>
                <value>
                    <fullName>Winner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Rank__c</fullName>
        <label>Neighborhood Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK(  Neighborhood_Preference_Member__c  )),  Neighborhood_Preference_Manual__c  ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address&apos;)),
    ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Neighborhood Preference</label>
        <type>Checkbox</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>COP_App_Total__c</fullName>
        <description>Total applications with COP preference</description>
        <label>COP App Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTHP_App_Total__c</fullName>
        <description>Total applications with DTHP preference</description>
        <label>DTHP App Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>General_App_Total__c</fullName>
        <label>General App Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Live_Work_App_Total__c</fullName>
        <description>Total applications with Live/Work preference</description>
        <label>Live Work App Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Lottery Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Run</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lottery Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Neighborhood_App_Total__c</fullName>
        <description>Total applications with Neighborhood preference</description>
        <label>Neighborhood App Total</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LOT_RandomDrawBatch.cls
global class LOT_RandomDrawBatch implements Database.Batchable<String>, Database.Stateful {
    
    List<String> winnerList;
    Map<String,ID> entities;
    global Integer rank;
    Id listingId;
    
    global LOT_RandomDrawBatch(List<String> winnerList, Map<String,ID> entities, Id listingId) {
        this.winnerList = winnerList;
        this.entities = entities;
        this.listingId = listingId;
        this.rank = 0;
    }
    
    global Iterable<String> start(Database.BatchableContext BC){
        return winnerList;
    }
    
    global void execute(Database.BatchableContext BC, List<String> winnerList){
        calculateRank(winnerList);
    }
    
    global void finish(Database.BatchableContext BC){
        Map<string,string> applicationPreference = new Map<string,string>();
        
        applicationPreference.put('DTHP_Preference__c','DTHP_Preference_Rank__c');
        applicationPreference.put('COP_Preference__c','COP_Preference_Rank__c');
        applicationPreference.put('Live_Work_Preference__c','Live_Work_Preference_Rank__c');
        applicationPreference.put('Neighborhood_Preference__c','Neighborhood_Preference_Rank__c');
        applicationPreference.put('General_Lottery__c','General_Lottery_Rank__c');
        
        Map<string,string> listingTotalFields = new Map<string,string>();
        listingTotalFields.put('DTHP_Preference__c','DTHP_App_Total__c');
        listingTotalFields.put('COP_Preference__c','COP_App_Total__c');
        listingTotalFields.put('Live_Work_Preference__c','Live_Work_App_Total__c');
        listingTotalFields.put('Neighborhood_Preference__c','Neighborhood_App_Total__c');
       	listingTotalFields.put('General_Lottery__c','General_App_Total__c');
        
        
        for(string pref : applicationPreference.keySet()){
            LOT_PreferenceRankBatch prefBatch = new LOT_PreferenceRankBatch(pref, applicationPreference.get(pref), listingTotalFields.get(pref), listingId);
            Database.executeBatch(prefBatch);
        }
        Listing__c listing = new Listing__c(Id=listingId);
        listing.Lottery_Status__c = 'Lottery Complete';
        update listing;
		
    }
    
    public void calculateRank(List<String> winnerList){
		List<Application__c> appRankList= new List<Application__c> ();
		system.debug('entities:::2::' + entities);
		system.debug('winnerList:::2::' + winnerList);
		for (String winnerName : winnerList) {
			ID theID = entities.get(winnerName);
			Application__c app = new Application__c();
			app.id = theID;
			rank++;
			app.Lottery_Rank__c = rank; 
        

			appRankList.add(app);
			
		}
		system.debug('appRankList:::2::' + appRankList);
		update  appRankList;
    }
}