src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Applicant_Household__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Applicant Household</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <description>Primary Applicant Gender</description>
        <formula>IF(ISPICKVAL( Applicant__r.Gender__c, &quot;Male&quot;), &quot;Male&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Female&quot;), &quot;Female&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Trans Male&quot;), &quot;Trans Male&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Trans Female&quot;), &quot;Trans Female&quot;,
IF(ISPICKVAL( Applicant__r.Gender__c , &quot;Not Listed&quot;), Applicant__r.Gender_Other__c,
IF(ISPICKVAL( Applicant__r.Gender__c, &quot;Decline to State&quot;), &quot;Decline to State&quot;, NULL))))))</formula>
        <label>Gender</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Is_Resident__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Resident</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary applicant on the application</description>
        <inlineHelpText>Select the primary applicant for this application</inlineHelpText>
        <label>Applicant</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>$Source.Applicant_Household__c</field>
                <operation>equals</operation>
                <valueField>Contact.AccountId</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Applications (Primary Applicant)</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Application_Households</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Household_Members</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans Male</fullName>
                </value>
                <value>
                    <fullName>Trans Female</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Decline to State</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>Example: CA, HI, WA, AZ, NY, WV, etc.</inlineHelpText>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Certificate_of_Preference_Holder__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Certificate of Preference Holder?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Displaced_Tenant_Preference__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Formerly The Ellis Act, Does this Contact have this preference?</description>
        <inlineHelpText>Formerly The Ellis Act, Does this Contact have this preference?</inlineHelpText>
        <label>Displaced Tenant Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans Male</fullName>
                </value>
                <value>
                    <fullName>Trans Female</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Decline to State</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prior_Tax_Year_Total_Income_Amount__c</fullName>
        <label>Prior Tax Year Total Income Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Head_of_Household2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Registered Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Great Grandparent</fullName>
                </value>
                <value>
                    <fullName>In-Law</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_City__c</fullName>
        <description>City of Work of the Contact</description>
        <inlineHelpText>City of Work of the Contact</inlineHelpText>
        <label>Work City</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Postal_Code__c</fullName>
        <description>Work Postal Code for the Contact</description>
        <inlineHelpText>Work Postal Code for the Contact</inlineHelpText>
        <label>Work Postal Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_State__c</fullName>
        <description>State of Work for the Contact</description>
        <inlineHelpText>State of Work for the Contact</inlineHelpText>
        <label>Work State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Street__c</fullName>
        <description>Work street Address</description>
        <inlineHelpText>Work street Address</inlineHelpText>
        <label>Work Street</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Applicant</fullName>
        <active>true</active>
        <description>Applicants for multi-family and/or BMR housing.</description>
        <label>Applicant</label>
    </recordTypes>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/API_ApplicationService.cls
public with sharing class API_ApplicationService {
    
    private static final String HOUSEHOLD_FIELDLIST = 
        'Id, Name';

    private static final String CONTACT_FIELDLIST =
        'Id, AccountId, FirstName, LastName, Birthdate, Email, Phone, Street_Name__c, City__c, State__c, Zip_Code__c,' +
        ' MailingStreet, MailingCity, MailingState, MailingPostalCode, Work_Street__c, Work_City__c, Work_State__c, Work_Postal_Code__c,' +
        ' Gender__c, Certificate_of_Preference_Holder__c, Displaced_Tenant_Preference__c, Relationship_to_Head_of_Household__c,' +
        ' Prior_Tax_Year_Total_Income_Amount__c'; //, incomeType

    private static final String SHORTFORM_FIELDLIST =
        'Id, Applicant_Household__c, Listing__c,' +
        prefixQuery('Primary_Applicant__r.', CONTACT_FIELDLIST) +
        ', ' +
        prefixQuery('Secondary_Contact__r.', CONTACT_FIELDLIST) +
        ', Works_In_SF__c, Status__c, Years_Homeless__c, Is_Resident__c';

    private static String prefixQuery(String prefix, String query) {
        return prefix + query.replaceAll(', ', ', ' + prefix);
    }



    public static Account getHouseholdById(Id householdId) {
        List<Account> accs = Database.query(
            'SELECT ' +
            HOUSEHOLD_FIELDLIST +
            ' FROM Account' +
            ' WHERE Id = :householdId'
        );

        if (accs.size() != 1) {
            return null;
        } else {
            return accs[0];
        }
    }

    public static List<Contact> getContactsByHouseholdIds(Set<Id> householdIds) {
        return Database.query(
            'SELECT ' +
            CONTACT_FIELDLIST +
            ' FROM Contact' +
            ' WHERE AccountId IN :householdIds'
        );
    }

    public static List<Contact> getContactsByHouseholdId(Id householdId) {
        return getContactsByHouseholdIds(new Set<Id>{householdId});
    }

    public static Contact getContactById(Id contactId) {
        List<Contact> cs = Database.query(
            'SELECT ' +
            CONTACT_FIELDLIST +
            ' FROM Contact' +
            ' WHERE Id = :contactId'
        );

        if (cs.size() != 1) {
            return null;
        } else {
            return cs[0];
        }
    }

    public static API_Application.Person getPersonById(Id contactId) {
        Contact c = getContactById(contactId);

        if (c == null) {
            return null;
        } else {
            return new API_Application.Person(c);
        }
    }

    public static Application__c getApplicationById(Id shortformId) {
        List<Application__c> apps = Database.query(
            'SELECT ' +
            SHORTFORM_FIELDLIST +
            ' FROM Application__c' +
            ' WHERE Id = :shortformId'
        );

        if (apps != null && apps.size() != 1) {
            return null;
        } else {
            return apps[0];
        }
    }

    public static List<Application__c> getApplicationsByPrimaryApplicantId(Id contactId) {
        return Database.query(
            'SELECT ' +
            SHORTFORM_FIELDLIST +
            ' FROM Application__c' +
            ' WHERE Primary_Applicant__c = :contactId'
        );
    }

    public static API_Application.ShortForm getShortformById(Id shortformId) {
        Application__c app = getApplicationById(shortformId);

        if (app == null) {
            return null;
        } else {
            List<Contact> hms = getContactsByHouseholdId(app.Applicant_Household__c);
            return new API_Application.ShortForm(app, hms);
        }
    }

    public static List<API_Application.ShortForm> getShortformsByContactId(Id contactId) {
        List<Application__c> apps = getApplicationsByPrimaryApplicantId(contactId);

        Set<Id> householdIds = new Set<Id>();
        Map<Id, List<Contact>> householdToMembersMap = new Map<Id, List<Contact>>();

        for (Application__c app : apps) {
            householdIds.add(app.Applicant_Household__c);
            householdToMembersMap.put(app.Applicant_Household__c, new List<Contact>());
        }

        List<Contact> allHouseholdMembers = getContactsByHouseholdIds(householdIds);
        for (Contact hm : allHouseholdMembers) {
            householdToMembersMap.get(hm.AccountId).add(hm);
        }

        List<API_Application.ShortForm> sfs = new List<API_Application.ShortForm>();
        for (Application__c app : apps) {
            sfs.add(new API_Application.ShortForm(app, householdToMembersMap.get(app.Applicant_Household__c)));
        }

        return sfs;
    }



    public static API_Application.Person upsertPerson(API_Application.Person p) {
        if (p == null) return null;

        Contact c = p.toContact();
        upsert c;
        return new API_Application.Person(c);
    }

    public static API_Application.ShortForm upsertShortform(API_Application.ShortForm sf) {
        if (sf == null) return null;

        Application__c app;
        Account household;

        if (sf.id == null) {
            // new application
            app = new Application__c();
        } else {
            // existing application
            app = sf.toApplication();
        }

        API_Application.Person primaryApplicant = sf.primaryApplicant;
        Contact primaryApplicantContact;

        // household
        Id householdId = null;
        Boolean newPrimaryApplicant = primaryApplicant.id == null;

        if (primaryApplicant.id != null) {
            primaryApplicantContact = getContactById(primaryApplicant.id);
            householdId = primaryApplicantContact.AccountId;
        }

        if (householdId == null) {
            household = new Account(Name = sf.primaryApplicant.firstName + ' ' + sf.primaryApplicant.lastName + '\'s Household');
            insert household;
        } else {
            household = getHouseholdById(householdId);
        }
        if (sf.id == null) {
            app.Applicant_Household__c = household.Id;
        }

        if (primaryApplicant.id == null) {
            // new primary applicant
            primaryApplicantContact = primaryApplicant.toContact();
            primaryApplicantContact.AccountId = household.Id;
            upsert primaryApplicantContact;
            primaryApplicant = new API_Application.Person(primaryApplicantContact);
        } else {
            // existing primary applicant
            primaryApplicant = upsertPerson(sf.primaryApplicant);
        }

        // secondary contact
        API_Application.Person secondaryContact = upsertPerson(sf.secondaryContact);

        // household members
        Set<Id> householdMemberIds = new Set<Id>();
        for (API_Application.Person householdMember : sf.householdMembers) {
            // for a new shortform, skip duplicate primary applicant as household member
            if (householdMember.id == null && newPrimaryApplicant &&
                householdMember.firstName == primaryApplicant.firstName &&
                householdMember.lastName == primaryApplicant.lastName &&
                householdMember.email == primaryApplicant.email) continue;

            Contact householdMemberContact = householdMember.toContact();
            householdMemberContact.AccountId = household.Id;
            upsert householdMemberContact;
            householdMemberIds.add(householdMemberContact.Id);
        }

        // finalize application
        if (sf.id == null) {
            app.Primary_Applicant__c = primaryApplicant == null ? null : primaryApplicant.id;
            app.Secondary_Contact__c = secondaryContact == null ? null : secondaryContact.id;
        }
        upsert app;

        // old application members
        /*List<Application_Member__c> applicationMembers =
            [
                SELECT Id, Application__c, Household_Member__c
                FROM Application_Member__c
                WHERE Application__c = :app.Id
                AND Household_Member__c IN :householdMemberIds
            ];

        Set<Id> existingHouseholdMembers = new Set<Id>();
        for (Application_Member__c applicationMember : applicationMembers) {
            existingHouseholdMembers.add(applicationMember.Household_Member__c);
        }

        List<Application_Member__c> newApplicationMembers = new List<Application_Member__c>();
        for (Id householdMemberId : householdMemberIds) {
            if (!existingHouseholdMembers.contains(householdMemberId)) {
                newApplicationMembers.add(new Application_Member__c(Application__c = app.Id, Household_Member__c = householdMemberId));
            }
        }
        if (newApplicationMembers.size() > 0) {
            insert newApplicationMembers;
        }*/
        
        // new application members
        List<Application_Household__c> applicationMembers =
            [
                SELECT Id, Application__c, Contact__c
                FROM Application_Household__c
                WHERE Application__c = :app.Id
                AND Contact__c IN :householdMemberIds
            ];

        Set<Id> existingHouseholdMembers = new Set<Id>();
        for (Application_Household__c applicationMember : applicationMembers) {
            existingHouseholdMembers.add(applicationMember.Contact__c);
        }

        List<Application_Household__c> newApplicationMembers = new List<Application_Household__c>();
        for (Id householdMemberId : householdMemberIds) {
            if (!existingHouseholdMembers.contains(householdMemberId)) {
                newApplicationMembers.add(new Application_Household__c(Application__c = app.Id, Contact__c = householdMemberId));
            }
        }
        if (newApplicationMembers.size() > 0) {
            insert newApplicationMembers;
        }

        return getShortformById(app.Id);
    }

    public static void deleteShortform(API_Application.ShortForm sf) {
        if (sf.id == null) return;
        delete [SELECT Id FROM Application__c WHERE Id = :sf.id];
    }

    public static void deletePerson(API_Application.Person p) {
        if (p.id == null) return;
        delete [SELECT Id FROM Contact WHERE Id = :p.id];
    }

}