src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Rank__c</fullName>
        <description>Returned lottery number rank</description>
        <label>Lottery Rank (Unsorted)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LOT_RandomDrawReqTest.cls
public class LOT_RandomDrawReqTest {
    
    static Listing__c theListing = new Listing__c();
    static List<Application__c> apps;
    
    
    
    public static Map<String,ID>  getEntities(String listingID) {
        
        Map<String,ID> entities = new Map<String,ID>();
        List<Application__c> theApps = [select id, name from Application__c where status__c = 'Submitted' AND listing__c = :listingID ];
        
        for( Application__c app  :theApps){
            entities.put(app.name, app.id);
        }
        
        return entities;
    }
    
    public static void testBulk(String listingID) {
        
            Map<String,ID> entities=  getEntities(listingID) ;
            LOT_RandomDrawReq.Drawing drawing = new LOT_RandomDrawReq.Drawing();
            LOT_RandomDrawReq.DrawingParams params = new LOT_RandomDrawReq.DrawingParams();
            params.title= 'drawing 4';
            params.recordType= 'test'; //'public';
            params.entries= new List<String>(entities.keySet()); //our map is reversed-  
            params.winnerCount=(entities.size() < 50000) ? entities.size() : 500000;
            drawing.params= params;
            LOT_RandomDrawReq req = new LOT_RandomDrawReq(drawing);
            system.debug(req.getJSON());
            req.sendRequest();
            LOT_RandomDrawReq.DrawingResult drawResult = req.drawResult;
            
            Integer rank = 1;
            List<Application__c> appRankList= new List<Application__c> ();
            for (String winnerName:drawResult.result.winners) {
                ID theID = entities.get(winnerName);
                Application__c app = new Application__c();
                app.id = theID;
                rank++;
                app.Lottery_Rank__c = rank; 
                appRankList.add(app);
                
            }
            update  appRankList;
        
    }
}