src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Annual_Income__c</fullName>
        <label>Annual Income</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary applicant of the application</description>
        <inlineHelpText>Select the primary applicant for this application</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Applicant)</relationshipLabel>
        <relationshipName>Applications4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Application_Language__c</fullName>
        <description>Language of the application</description>
        <inlineHelpText>Language used to fill out this application</inlineHelpText>
        <label>Application Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>English</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Spanish</fullName>
                </value>
                <value>
                    <fullName>Chinese</fullName>
                </value>
                <value>
                    <fullName>Filipino</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>COP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An related application member that holds a COP preference</description>
        <label>COP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member that holds a DTHP preference</description>
        <label>DTHP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (DTHP Preference Member)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <description>Primary applicant date of birth</description>
        <formula>Applicant__r.Date_of_Birth__c</formula>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <description>Primary applicant email address</description>
        <formula>Applicant__r.Email__c</formula>
        <label>Email</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Primary applicant first name</description>
        <formula>Applicant__r.First_Name__c</formula>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Housing_Voucher_or_Subsidy__c</fullName>
        <label>Housing Voucher or Subsidy</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>true</fullName>
                </value>
                <value>
                    <fullName>false</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Primary applicant last name</description>
        <formula>Applicant__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference_Paper__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Live work manual preference override for msol</description>
        <label>Live/Work Preference Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <description>Primary applicant middle name</description>
        <formula>Applicant__r.Middle_Name__c</formula>
        <label>Middle Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member who has the neighborhood preference</description>
        <label>Neighborhood Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Neighborhood Preference Member)</relationshipLabel>
        <relationshipName>Applications3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Phone_Type__c</fullName>
        <description>Primary applicant phone type</description>
        <formula>TEXT(Applicant__r.Phone_Type__c)</formula>
        <label>Phone Type</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <description>Primary applicant phone</description>
        <formula>Applicant__r.Phone__c</formula>
        <label>Phone</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Terms_Acknowledged__c</fullName>
        <defaultValue>false</defaultValue>
        <description>User agreed online to terms of application submittal</description>
        <inlineHelpText>The user agreed to the terms of submitting this application.</inlineHelpText>
        <label>Terms Acknowledged</label>
        <type>Checkbox</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Application_Households</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Middle_Name__c</fullName>
        <label>Middle Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <formula>First_Name__c &amp; IF( OR( ISBLANK(First_Name__c), ISBLANK(Middle_Name__c) ) , &apos;&apos;, &apos; &apos;) &amp; Middle_Name__c &amp; IF( OR( ISBLANK(Middle_Name__c), ISBLANK(Last_Name__c) ), &apos;&apos;, &apos; &apos;) &amp; IF( AND( NOT( ISBLANK(First_Name__c) ), ISBLANK(Middle_Name__c), NOT( ISBLANK(Last_Name__c) ) ), &apos; &apos;, &apos;&apos;) &amp; Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Type__c</fullName>
        <label>Phone Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Home</fullName>
                </value>
                <value>
                    <fullName>Work</fullName>
                </value>
                <value>
                    <fullName>Cell</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <inlineHelpText>Example: CA, HI, WA, AZ, NY, WV, etc.</inlineHelpText>
        <label>State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>75</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/HOP_ApplicationController.cls
public without sharing class HOP_ApplicationController {

    public Application__c app {get; set;}
    public Application_Member__c primaryApplicant {get; set;}
    public Boolean editMode {get; set;}
    public Boolean hasErrors {get; set;}
    public List<Attachment> attachments {get; set;}
    public Attachment attachment {
        get {
            if (attachment == null)
                attachment = new Attachment();
            return attachment;
        }
        set;
    } 

    private List<Attachment> getAttachmentsByParent(String parentId) {
        return [
            SELECT Id, Name, BodyLength
            FROM Attachment
            WHERE ParentId = :parentId
        ];
    }

    private void queryAppAndPrimaryApplicant(String pAppId) {
        List<Application__c> apps = [
            SELECT
                Id, Name, Annual_Income__c, Terms_Acknowledged__c, Live_Work_Preference_Paper__c,
                Housing_Voucher_or_Subsidy__c, Application_Language__c, Applicant__c,
                Neighborhood_Preference_Member__c, DTHP_Preference_Member__c, COP_Preference_Member__c
            FROM Application__c
            WHERE Id = :pAppId
        ];

        if (apps.size() == 0) {
            app = null;
            primaryApplicant = null;
        } else {
            app = apps[0];

            List<Application_Member__c> primaryApplicants = [
                SELECT
                    First_Name__c, Middle_Name__c, Last_Name__c, Date_of_Birth__c,
                    Email__c, Phone__c, Phone_Type__c, Street__c, City__c, State__c, Zip_Code__c
                FROM Application_Member__c
                WHERE Id = :app.Applicant__c
            ];

            if (primaryApplicants.size() == 0) {
                primaryApplicant = null;
            } else {
                primaryApplicant = primaryApplicants[0];
            }
        }
    }

    public HOP_ApplicationController() {
        editMode = false;
        hasErrors = false;
        attachments = new List<Attachment>();

        String pAppId = ApexPages.currentPage().getParameters().get('id');
        if (String.isBlank(pAppId)) {
            editMode = true;
            app = new Application__c();
            primaryApplicant = new Application_Member__c();
            return;
        }

        queryAppAndPrimaryApplicant(pAppId);
        if (app == null) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Application record with Id ' + pAppId + ' not found'));
            hasErrors = true;
            return;
        }

        attachments = getAttachmentsByParent(app.Id);
    }

    public void saveApplication() {
        upsert app;
        editMode = false;
        queryAppAndPrimaryApplicant(app.Id);
        attachments = getAttachmentsByParent(app.Id);
    }

    public void processAttachment() {
        attachment.ParentId = app.Id;
        insert attachment;
        attachment = null;
        attachments = getAttachmentsByParent(app.Id);
    }
    
    @RemoteAction
    public static List<Application_Member__c> getApplicationMembers(String query) {
        String nameLike = '%' + query + '%';
        return [SELECT Id, Name__c FROM Application_Member__c WHERE Name__c LIKE :nameLike ORDER BY Name__c];
    }

}