src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Rank__c</fullName>
        <description>Returned lottery number rank</description>
        <label>Lottery Rank (Unsorted)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <inlineHelpText>The status of this application as related to the lottery</inlineHelpText>
        <label>Lottery Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Lottery</fullName>
                </value>
                <value>
                    <fullName>Non-Winner</fullName>
                </value>
                <value>
                    <fullName>Winner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Lottery Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Run</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lottery Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/LOT_PreferenceRankBatch.cls
global class LOT_PreferenceRankBatch implements Database.Batchable<sObject>, Database.Stateful {
	
	String query;
	String preferedField;
	String rankField;
	Integer preferedRank;
    String totalField;
    Id listingId;
	Set<string> completedPreffered;
	public LOT_PreferenceRankBatch nextBatch;

	
	global LOT_PreferenceRankBatch(string prefField, string prefRankField, string prefTotalField, Id listingId) {
		this.preferedRank = 0;
		this.preferedField = prefField;
		this.rankField = prefRankField;
        this.totalField = prefTotalField;
        this.listingId = listingId;
        
		query = 'SELECT Id, Lottery_Rank__c, ' + preferedField + ', ' + rankField + ' FROM Application__c WHERE Listing__c = \'' + listingId + '\' AND Status__c = \'Submitted\' AND (' + preferedField + ' = true OR ' + rankField + ' != null) ORDER BY Lottery_Rank__c asc';
		//query = 'SELECT Id, Lottery_Rank__c, ' + preferedField + ', ' + rankField + ' FROM Application__c WHERE Listing__c = \'' + listingId + '\' AND Status__c = \'Submitted\' ORDER BY Lottery_Rank__c asc';
		system.debug('query:::' + query);
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Application__c> scope) {
		system.debug('scope:::' + scope);
        calculateRank(scope);
	}
	
	global void finish(Database.BatchableContext BC) {
        
        if (nextBatch != null){
        	Database.executeBatch(nextBatch);
        } else {
        	Listing__c listing = new Listing__c(Id=listingId);
	        if(preferedRank > 0){
	            //Listing__c listing = new Listing__c(Id=listingId);
	            listing.put(totalField,preferedRank);
	            //update listing;
	        }
        	listing.Lottery_Status__c = 'Lottery Complete';
	        update listing;
        }
	}

	public void calculateRank(List<Application__c> scope){
		List<Application__c> updatedApplications = new List<Application__c>();

		for(Application__c application : scope){
			if ((boolean)application.get(preferedField) == true) {
				preferedRank++;
				application.put(rankField, preferedRank);
			} else {
				application.put(rankField, null);
			}
		}
		update scope;
	}
	
}