src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Application_Submission_Type__c</fullName>
        <description>Field to determine how an application was submitted: via electronic or paper means.  If paper is submitted, a Leasing Agent user is required to be identified as the user who entered it.</description>
        <inlineHelpText>Please indicate the method by which this application was submitted to SF MOHCD.</inlineHelpText>
        <label>Application Submission Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Electronic</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Paper</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <inlineHelpText>The status of this application as related to the lottery</inlineHelpText>
        <label>Lottery Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Awaiting Lottery</fullName>
                </value>
                <value>
                    <fullName>Non-Winner</fullName>
                </value>
                <value>
                    <fullName>Winner</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Preference__c.object
<CustomObject>
    <description>Stores a &quot;snapshot in time&quot; of which preferences were claimed or opted-out of for each application, and any related application members (household members), if applicable.</description>
    <fields>
        <fullName>Application__c</fullName>
        <description>The related Application that this preference was saved for.</description>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Auto_Grant_Count__c</fullName>
        <label>Auto Grant Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Auto_Grants_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>parent application preference</description>
        <label>Auto Grant Preference</label>
        <referenceTo>Application_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing_Preference_ID__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing Preference Number</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Application Preferences</relationshipLabel>
        <relationshipName>Application_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Pre-Lottery Validation</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>None</fullName>
                </value>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid for lottery</fullName>
                </value>
                <value>
                    <fullName>Invalid for lottery</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
                <value>
                    <fullName>Does not receive preference</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Needs pre-lottery validation</fullName>
                    <isActive>false</isActive>
                </value>
                <value>
                    <fullName>Receives preference</fullName>
                    <isActive>false</isActive>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application Preference</label>
    <nameField>
        <displayFormat>AP-{0000000000}</displayFormat>
        <label>Application Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Development__c</fullName>
        <description>Development for the property</description>
        <inlineHelpText>Development for the property</inlineHelpText>
        <label>Development</label>
        <referenceTo>Development__c</referenceTo>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Development__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MOHCD Project ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Name__c</fullName>
        <description>Name of Building</description>
        <inlineHelpText>Name of Building</inlineHelpText>
        <label>Building Name</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Property Auto-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Development__c.object
<CustomObject>
    <fields>
        <fullName>Development_City__c</fullName>
        <defaultValue>&quot;San Francisco&quot;</defaultValue>
        <description>City of the Development - Defaults to San Francisco</description>
        <inlineHelpText>City of the Development - Defaults to San Francisco</inlineHelpText>
        <label>Development City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Development_State__c</fullName>
        <defaultValue>&quot;CA&quot;</defaultValue>
        <description>Development State - Defaults to CA</description>
        <inlineHelpText>Development State - Defaults to CA</inlineHelpText>
        <label>Development State</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Development__c</fullName>
        <label>Name of Development</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Development</label>
    <nameField>
        <displayFormat>DVL-{000000}</displayFormat>
        <label>Development Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Lottery Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Run</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lottery Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Building__r.Development__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing_Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Auto_Grants_Preference__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Auto Grant Preference</label>
        <referenceTo>Listing_Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Preferences</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The listing for this object</description>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Preference__c</fullName>
        <label>Preference</label>
        <referenceTo>Lottery_Preference__c</referenceTo>
        <relationshipLabel>Listing Preferences</relationshipLabel>
        <relationshipName>Listing_Lottery_Preferences</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Total_Submitted_Apps__c</fullName>
        <label>Total Submitted App</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Listing Preference</label>
    <nameField>
        <displayFormat>LP-{00000}</displayFormat>
        <label>Listing Preference Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Listing Preferences</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of this preference</description>
        <inlineHelpText>Enter the current status of this preference</inlineHelpText>
        <label>XStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Old</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RollUpSummaryActionTest.cls
@isTest
public class RollUpSummaryActionTest {

    
	 static testmethod void AutoGrantApplicationRollUpTest() {
         
         List<Application__c> appList = [SELECT ID, Preferences_Received_Count__c FROM Application__c];
         List<Listing_Lottery_Preference__c> lotList = [SELECT ID FROM Listing_Lottery_Preference__c];
         
         Application_Preference__c appPref = new Application_Preference__c(Application__c = appList[0].Id, Listing_Preference_ID__c = lotList[0].Id);
         insert appPref;
                 
 		test.startTest();
         appPref.Lottery_Status__c = 'Valid - Added';
         update appPref;
         
         appList = [SELECT ID, Preferences_Received_Count__c FROM Application__c];
         System.assertEquals(appList[0].Preferences_Received_Count__c, 1);
         
         Application_Preference__c appPref2 = new Application_Preference__c(Application__c = appList[0].Id, Listing_Preference_ID__c = lotList[0].Id, Lottery_Status__c = 'Valid - Added');
         insert appPref2;
         
         appList = [SELECT ID, Preferences_Received_Count__c FROM Application__c];
         System.assertEquals(appList[0].Preferences_Received_Count__c, 2);
         
         appList[0].Status__c = 'Submitted';
         update appList;
         
         lotList = [SELECT ID, Total_Submitted_Apps__c FROM Listing_Lottery_Preference__c];
         System.assertEquals(appList[0].Preferences_Received_Count__c, 2);
         
         test.stopTest();
        
    }
    
    
	 static testmethod void AutoGrantApplicationPreferenceRollUpTest() {
         
         List<Application__c> appList = [SELECT ID, Preferences_Received_Count__c FROM Application__c];
         List<Listing_Lottery_Preference__c> lotList = [SELECT ID FROM Listing_Lottery_Preference__c];
         
                 
 		test.startTest();
		
         Application_Preference__c appPref = new Application_Preference__c(Application__c = appList[0].Id, Listing_Preference_ID__c = lotList[0].Id);
         insert appPref;
         
         Application_Preference__c appPref2 = new Application_Preference__c(Application__c = appList[0].Id, Listing_Preference_ID__c = lotList[0].Id, Auto_Grants_Preference__c = appPref.Id, Lottery_Status__c = 'Valid - Added');
         insert appPref2;
         
         List<Application_Preference__c> appPrefList = [SELECT ID, Auto_Grant_Count__c FROM Application_Preference__c];
         
         System.assertEquals(appPrefList[0].Auto_Grant_Count__c, 1);

         delete appPref2;
         
         appPrefList = [SELECT ID, Auto_Grant_Count__c FROM Application_Preference__c];
         System.assertEquals(appPrefList[0].Auto_Grant_Count__c, 0);
         
         test.stopTest();
        
    }
    
    @testSetup static void setup() {
        // Creating common data
       
        Account acc = new Account(Name='Test Account');
        insert acc;
        
        Development__c dev = new Development__c(Name_of_Development__c='Test Development', Development_City__c = 'San Francisco', Development_State__c = 'CA', Project_ID__c = '123');
        insert dev;
        
        Building__c build = new Building__c(Property_Name__c='Test Building', Development__c = dev.id);
        insert build;
        
        Listing__c listing = new Listing__c(Name='Test Listing', Building__c = build.id, Account__c = acc.id);
        insert listing;
        
        Lottery_Preference__c lotPref = new Lottery_Preference__c(Name='Test Preference', Active__c = true);
        insert lotPref;
        
        Listing_Lottery_Preference__c listLotPref = new Listing_Lottery_Preference__c(Listing__c = listing.id, Lottery_Preference__c = lotPref.id);
        insert listlotPref;
        
        Application__c app = new Application__c(Listing__c = listing.id, Application_Submission_Type__c = 'Electronic');
        insert app;
        

}
}