src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>Alternate_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The alternate contact for this application</description>
        <inlineHelpText>Someone who can be contacted in place of the Primary Applicant.</inlineHelpText>
        <label>Alternate Contact</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Alternate Contact)</relationshipLabel>
        <relationshipName>Applications5</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Applicant__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Primary applicant of the application</description>
        <inlineHelpText>Select the primary applicant for this application</inlineHelpText>
        <label>Applicant</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Applicant)</relationshipLabel>
        <relationshipName>Applications4</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date_of_birth__c</fullName>
        <description>Primary applicant date of birth</description>
        <formula>Applicant__r.Date_of_Birth__c</formula>
        <label>Date of birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <description>Primary applicant first name</description>
        <formula>Applicant__r.First_Name__c</formula>
        <label>First Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <description>Primary applicant last name</description>
        <formula>Applicant__r.Last_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Last Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Stats of application</description>
        <inlineHelpText>The current status of this application</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Draft</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Removed</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Application_Households</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Building__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Developer for the Building.</description>
        <inlineHelpText>Developer for the Building.</inlineHelpText>
        <label>Developer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Buildings</relationshipLabel>
        <relationshipName>Buildings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Development__c</fullName>
        <description>Development for the property</description>
        <inlineHelpText>Development for the property</inlineHelpText>
        <label>Development</label>
        <referenceTo>Development__c</referenceTo>
        <relationshipName>Properties</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Development__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>MOHCD Project ID</label>
        <type>Text</type>
    </fields>
    <label>Building</label>
    <nameField>
        <displayFormat>PR-{000000}</displayFormat>
        <label>Property Auto-Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Buildings</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Development__c.object
<CustomObject>
    <fields>
        <fullName>Developer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Developer who is responsible for this development.</description>
        <label>Developer</label>
        <lookupFilter>
            <active>true</active>
            <errorMessage>Must be a developer</errorMessage>
            <filterItems>
                <field>Account.RecordType.Name</field>
                <operation>equals</operation>
                <value>Property Management</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Developments</relationshipLabel>
        <relationshipName>Developments</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Name_of_Development__c</fullName>
        <label>Name of Development</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <label>Project ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Development</label>
    <nameField>
        <displayFormat>DVL-{000000}</displayFormat>
        <label>Development Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Developments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flagged_Application__c.object
<CustomObject>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipName>Conflicting_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Conflicting_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flagged Application</label>
    <nameField>
        <displayFormat>FLAG-{000000}</displayFormat>
        <label>Flagged Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flagged Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Flagged_Record_Set__c.object
<CustomObject>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Conflict</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Flagged Record Set</label>
    <nameField>
        <displayFormat>FRS-{0000000000}</displayFormat>
        <label>Flagged Record Set</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flagged Record Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Building__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Building</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Developer__c</fullName>
        <description>Name of the Developer for the Building.</description>
        <formula>Building__r.Developer__r.Name</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Name of the Developer for the Building.</inlineHelpText>
        <label>Developer</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project_ID__c</fullName>
        <formula>Building__r.Development__r.Project_ID__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Project ID</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>BMR_Rent_Monthly__c</fullName>
        <description>Monthly Rent for BMR Unit</description>
        <inlineHelpText>Monthly Rent for BMR Unit</inlineHelpText>
        <label>Monthly rent (if $)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Bedrooms__c</fullName>
        <label>Number of Bedrooms</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Property__c</fullName>
        <label>Building Record Number</label>
        <referenceTo>Building__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Rent_Multiple__c</fullName>
        <label>Rent Multiple</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Reserved_Type__c</fullName>
        <label>Reserved Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetName>Priority</valueSetName>
        </valueSet>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>To be Built out, but is the unit currently occupied/available (includes in development). Will largely be a hidden field.</description>
        <inlineHelpText>To be Built out, but is the unit currently occupied/available (includes in development). Will largely be a hidden field.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Available</fullName>
                </value>
                <value>
                    <fullName>Occupied</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>of_AMI_for_Pricing_Unit__c</fullName>
        <description>% of Area Median Income for Pricing Unit.</description>
        <inlineHelpText>% of Area Median Income for Pricing Unit.</inlineHelpText>
        <label>% of AMI for Pricing Unit</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>UID-{0000000}</displayFormat>
        <label>Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/globalValueSets/Priority.globalValueSet
<GlobalValueSet>
    <customValue>
        <fullName>Vision impaired</fullName>
    </customValue>
    <customValue>
        <fullName>Mobility impaired</fullName>
    </customValue>
    <customValue>
        <fullName>Mobility/hearing/vision impaired</fullName>
    </customValue>
    <customValue>
        <fullName>Hearing impaired</fullName>
    </customValue>
    <customValue>
        <fullName>Hearing/Vision impaired</fullName>
    </customValue>
    <customValue>
        <fullName>Developmental disabilities</fullName>
    </customValue>
    <customValue>
        <fullName>Senior</fullName>
    </customValue>
    <customValue>
        <fullName>Veteran</fullName>
    </customValue>
    <masterLabel>Priority</masterLabel>
</GlobalValueSet>

src/classes/HOP_ApplicationViewControllerTest.cls
// *****************************************************************************
// CLASS: HOP_ApplicationViewControllerTest
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Test class for the HOP_ApplicationViewController class.
//
// *****************************************************************************

@isTest
private class HOP_ApplicationViewControllerTest {
	
	@isTest
	static void emptyIdTest() {
		Test.startTest();
			HOP_ApplicationViewController cnt = new HOP_ApplicationViewController();
			System.assert(cnt.hasErrors == true);
		Test.stopTest();
	}
	
	@isTest
	static void badIdTest() {
		Test.startTest();
			ApexPages.currentPage().getParameters().put('id', UserInfo.getUserId());
			HOP_ApplicationViewController cnt = new HOP_ApplicationViewController();
			System.assert(cnt.hasErrors == true);
		Test.stopTest();
	}

	@isTest
	static void communityUser_noAccessAccountTest() {
		Test.startTest();

			List<Profile> communityUserProfiles = [SELECT Id FROM Profile WHERE UserLicense.Name = :HOP_Constants.COMMUNITY_LICENSE_NAME LIMIT 1];
			if (communityUserProfiles.size() == 0) return;
			Id communityUserProfileId = communityUserProfiles[0].Id;

			Id PROPERTY_MANAGEMENT_ACCOUNT_RTID = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = 'Property_Management'].Id;
			Account cuAccount = new Account(RecordTypeId = PROPERTY_MANAGEMENT_ACCOUNT_RTID, Name = 'PMA');
        	insert cuAccount;
        
        	Account otherAccount = new Account(Name = 'OA');
        	insert otherAccount;
        	
			Listing__c otherListing = new Listing__c(Name = 'OtherListing', Account__c = otherAccount.Id);
			insert otherListing;

			Listing__c myListing = new Listing__c(Name = 'MyListing', Account__c = cuAccount.Id);
			insert myListing;

			Application__c otherApp = new Application__c(Listing__c = otherListing.Id);
			insert otherApp;

			Application__c myDraftApp = new Application__c(Listing__c = myListing.Id, Status__c = HOP_Constants.DRAFT_APPLICATION);
			insert myDraftApp;
        	
            Development__c dev = new Development__c();
            dev.Name_of_Development__c = 'amli';
            dev.Project_ID__c = '123';
            insert dev;
          
            Building__c build = new Building__c();
            build.Development__c = dev.Id;
            build.Developer__c = cuAccount.Id;
            insert build;
        
        	Unit__c unit = new Unit__c();
            unit.property__c  = build.id;
            unit.BMR_Rent_Monthly__c = 400;
            unit.Rent_Multiple__c=3;
            unit.of_AMI_for_Pricing_Unit__c=55;
            unit.Listing__c = myListing.id;
            unit.Number_of_Bedrooms__c = 3;
        	unit.Reserved_Type__c = 'Developmental disabilities';
            insert unit;

	        Id LENDING_AGENT_CONTACT_RTID = [SELECT Id FROM RecordType WHERE SObjectType = 'Contact' AND DeveloperName = 'Lending_Agent'].Id;
			Contact cuContact = new Contact(RecordTypeId = LENDING_AGENT_CONTACT_RTID, AccountId = cuAccount.Id, LastName = 'PMC');
	        insert cuContact;
        
	        User cuUser = new User(	UserName = 'cuUser@cuUser.comcom', Alias = 'PMU', LastName = 'PMU', Email = 'cuUser@cuUser.comcom', IsActive = true,
	        						ProfileId = communityUserProfileId, EmailEncodingKey = 'UTF-8', TimeZoneSidKey = 'America/Denver',
	        						LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ContactId = cuContact.Id);
	        insert cuUser;
        
			System.runAs(cuUser) {
				ApexPages.currentPage().getParameters().put('id', otherApp.Id);
				HOP_ApplicationViewController cnt = new HOP_ApplicationViewController();
				System.assert(cnt.hasErrors == true);

				ApexPages.currentPage().getParameters().put('id', myDraftApp.Id);
				cnt = new HOP_ApplicationViewController();
				System.assert(cnt.hasErrors == true);
			}
		Test.stopTest();
	}

	@isTest
	static void positiveTest() {
		Test.startTest();

			Account someAccount = new Account(Name = 'someAccount');
        	insert someAccount;
        	
			Listing__c someListing = new Listing__c(Name = 'someListing', Account__c = someAccount.Id);
			insert someListing;

			Application__c someApplication = new Application__c(Listing__c = someListing.Id);
			insert someApplication;

			Application_Member__c primaryApplicant = new Application_Member__c(Application__c = someApplication.Id, First_Name__c = 'Name2', Last_Name__c = 'LastName2', Date_of_Birth__c = date.today());
			insert primaryApplicant;

			Application_Member__c alternateContact = new Application_Member__c(Application__c = someApplication.Id, First_Name__c = 'Name', Last_Name__c = 'LastName', Date_of_Birth__c = date.today());
			insert alternateContact;
			
			someApplication.Applicant__c = primaryApplicant.Id;
			someApplication.Alternate_Contact__c = alternateContact.Id;
			update someApplication;
			
			Flagged_Record_Set__c someFlaggedRecordSet = new Flagged_Record_Set__c(Listing__c = someListing.Id);
			insert someFlaggedRecordSet;

			Flagged_Application__c someFlaggedApplication = new Flagged_Application__c(Flagged_Record_Set__c = someFlaggedRecordSet.Id, Application__c = someApplication.Id);
			insert someFlaggedApplication;

			ApexPages.currentPage().getParameters().put('id', someApplication.Id);
			HOP_ApplicationViewController cnt = new HOP_ApplicationViewController();
			System.assert(cnt.hasErrors == false);
			System.assert(cnt.app.Id == someApplication.Id);
			System.assert(cnt.flaggedRecordSetString == '\'' + someFlaggedRecordSet.Id + '\'');

		Test.stopTest();
	}
	
}