src/objects/Application__c.object
<CustomObject>
    <description>Application</description>
    <fields>
        <fullName>COP_Preference_Manual__c</fullName>
        <description>Primary applicant holds COP - manual overrride for MSOL</description>
        <inlineHelpText>Certificate of Preference</inlineHelpText>
        <label>COP Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>COP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An related application member that holds a COP preference</description>
        <label>COP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>COP_Preference__c</fullName>
        <formula>/*OLD - Replaced 8/16 based on underlying field change IF( OR(NOT(ISBLANK(COP_Preference_Member__c)),   COP_Preference_Manual__c  ) , true, false)*/


IF(
  OR(
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(COP_Preference_Member__c)), ISPICKVAL(COP_Preference_Manual__c, &apos;Valid&apos;)),
    ISPICKVAL(COP_Preference_Manual__c, &apos;Valid - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>COP Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Manual__c</fullName>
        <description>Displaced tenant DTHP Preference Manual</description>
        <inlineHelpText>Displaced Tenant Housing Preference</inlineHelpText>
        <label>DTHP Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid</fullName>
                </value>
                <value>
                    <fullName>Valid - Added</fullName>
                </value>
                <value>
                    <fullName>Invalid</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Member_Name__c</fullName>
        <formula>DTHP_Preference_Member__r.First_Name__c + &apos; &apos; + DTHP_Preference_Member__r.Last_Name__c</formula>
        <label>DTHP Preference Member Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member that holds a DTHP preference</description>
        <label>DTHP Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (DTHP Preference Member)</relationshipLabel>
        <relationshipName>Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference_Rank__c</fullName>
        <label>DTHP Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>DTHP_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK( DTHP_Preference_Member__c )),     DTHP_Preference_Manual__c    ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(DTHP_Preference_Member__c)), ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid&apos;)),
    ISPICKVAL(DTHP_Preference_Manual__c, &apos;Valid - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>DTHP Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <description>The Listing that is being applied for</description>
        <inlineHelpText>The associated listing for this application</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Applications</relationshipLabel>
        <relationshipName>Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference_Paper__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Live work manual preference override for msol</description>
        <label>Live/Work Preference Manual</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference_Rank__c</fullName>
        <label>Live/Work Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Live_Work_Preference__c</fullName>
        <formula>IF( OR(NOT(ISBLANK(Live_in_SF_Preference_Member__c)), NOT(ISBLANK(Work_in_SF_Preference_Member__c)), Live_Work_Preference_Paper__c  ) , true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Live/Work Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Live_in_SF_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Live in SF Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Live in SF Preference Member)</relationshipLabel>
        <relationshipName>Applications6</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Live_in_SF_Preference_Proof__c</fullName>
        <label>Live in SF Preference Proof</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Telephone bill</fullName>
                </value>
                <value>
                    <fullName>Cable and internet bill</fullName>
                </value>
                <value>
                    <fullName>Gas bill</fullName>
                </value>
                <value>
                    <fullName>Electric bill</fullName>
                </value>
                <value>
                    <fullName>Garbage bill</fullName>
                </value>
                <value>
                    <fullName>Water bill</fullName>
                </value>
                <value>
                    <fullName>Paystub</fullName>
                </value>
                <value>
                    <fullName>Public benefits record</fullName>
                </value>
                <value>
                    <fullName>School record</fullName>
                </value>
                <value>
                    <fullName>Paystub with employer address</fullName>
                </value>
                <value>
                    <fullName>Letter from employer</fullName>
                </value>
                <value>
                    <fullName>Third-Party Proof of SF Homelessness</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Address__c</fullName>
        <formula>IF(NOT(ISBLANK(Neighborhood_Preference_Member__r.Street__c)),Neighborhood_Preference_Member__r.Street__c + &apos;, &apos; + Neighborhood_Preference_Member__r.City__c + &apos;, &apos; + Neighborhood_Preference_Member__r.State__c + &apos;, &apos; + Neighborhood_Preference_Member__r.Zip_Code__c, &apos;&apos;)</formula>
        <label>Neighborhood Preference Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Manual__c</fullName>
        <description>Neighborhood manual preference override for msol</description>
        <label>Neighborhood Preference Manual</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Unconfirmed</fullName>
                </value>
                <value>
                    <fullName>Valid Address</fullName>
                </value>
                <value>
                    <fullName>Invalid Address</fullName>
                </value>
                <value>
                    <fullName>Valid Address - Added</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>An application member who has the neighborhood preference</description>
        <label>Neighborhood Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Neighborhood Preference Member)</relationshipLabel>
        <relationshipName>Applications3</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Proof__c</fullName>
        <label>Neighborhood Preference Proof</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Telephone bill</fullName>
                </value>
                <value>
                    <fullName>Cable and internet bill</fullName>
                </value>
                <value>
                    <fullName>Gas bill</fullName>
                </value>
                <value>
                    <fullName>Electric bill</fullName>
                </value>
                <value>
                    <fullName>Garbage bill</fullName>
                </value>
                <value>
                    <fullName>Water bill</fullName>
                </value>
                <value>
                    <fullName>Paystub</fullName>
                </value>
                <value>
                    <fullName>Public benefits record</fullName>
                </value>
                <value>
                    <fullName>School record</fullName>
                </value>
                <value>
                    <fullName>Paystub with employer address</fullName>
                </value>
                <value>
                    <fullName>Letter from employer</fullName>
                </value>
                <value>
                    <fullName>Third-Party Proof of SF Homelessness</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference_Rank__c</fullName>
        <label>Neighborhood Preference Rank</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference__c</fullName>
        <formula>/*OLD - Removed 8/16 based on underlying field changes IF( OR(NOT(ISBLANK(  Neighborhood_Preference_Member__c  )),  Neighborhood_Preference_Manual__c  ) , true, false)*/

IF(
  OR(
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;&apos;)),
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Unconfirmed&apos;)), 
    AND(NOT(ISBLANK(Neighborhood_Preference_Member__c)), ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address&apos;)),
    ISPICKVAL(Neighborhood_Preference_Manual__c, &apos;Valid Address - Added&apos;)
    ), true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Neighborhood Preference</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_in_SF_Preference_Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Work in SF Preference Member</label>
        <referenceTo>Application_Member__c</referenceTo>
        <relationshipLabel>Applications (Work in SF Preference Member)</relationshipLabel>
        <relationshipName>Applications7</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Application</label>
    <nameField>
        <displayFormat>APP-{00000000}</displayFormat>
        <label>Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Application_Member__c.object
<CustomObject>
    <description>Renamed to Application Household from Household Member on 5/6/16 per client&apos;s feedback and instruction.

Renamed again to Application Member from Application Household on 6/16/16 per client&apos;s feedback and instruction.</description>
    <fields>
        <fullName>Application__c</fullName>
        <label>Application</label>
        <referenceTo>Application__c</referenceTo>
        <relationshipLabel>Application Members</relationshipLabel>
        <relationshipName>Application_Households</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Neighborhood_Preference__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Neighborhood Preference</label>
        <type>Checkbox</type>
    </fields>
    <label>Application Member</label>
    <nameField>
        <displayFormat>AMN-{000000}</displayFormat>
        <label>Application Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/RandomizePreference.cls
public class RandomizePreference {
    
    public static Integer getRand(Integer x, Integer y) {
        return (Integer)Math.floor(Math.random() * ((y-x)+1) + x);
        
    }
    
    public static List<Application_Member__c> getAppMember(Id appId, List<Application_Member__c> appMemberList) {
        List<Application_Member__c> appMemList = new List<Application_Member__c>();
        for(Application_Member__c appMem : appMemberList) {
            if(appId == appMem.Application__c)
                appMemList.add(appMem);
        }
        return appMemList;
    }
    public static void randomize(){
        String[] prefManual = new String[]{'Valid','Valid - Added','Unconfirmed','Invalid'};
        String[] NRHPManual = new String[]{'Valid Address','Valid Address - Added','Unconfirmed','Invalid Address'};
		Map<Id,Application__c> appMap = new Map<Id,Application__c>();
        Map<id,List<Application_Member__c>> appMemberMap =new Map<id,List<Application_Member__c>>();
        
        List<Application__c> appList = [SELECT Id, Is_Migrated__c, Name, Listing__c, COP_Preference_Manual__c, COP_Preference_Member__c, COP_Preference__c, DTHP_Preference_Manual__c, DTHP_Preference_Member_Name__c, DTHP_Preference_Member__c, DTHP_Preference_Rank__c, DTHP_Preference__c, Live_Work_Preference_Paper__c, Live_Work_Preference_Rank__c, Live_Work_Preference__c, Live_in_SF_Preference_Member__c, Live_in_SF_Preference_Proof__c, Neighborhood_Preference_Address__c, Neighborhood_Preference_Manual__c, Neighborhood_Preference_Member__c, Neighborhood_Preference_Proof__c, Neighborhood_Preference_Rank__c, Neighborhood_Preference__c, Work_in_SF_Preference_Member__c, Work_in_SF_Preference_Proof__c, COP_Opt_Out__c, DTHP_Opt_Out__c, Live_Work_Opt_Out__c, NRHP_Opt_Out__c From Application__c Where Listing__c = 'a0Wg0000004hUz2' AND Is_Migrated__c = false LIMIT 300];
        for(Application__c app : appList) {
            appMap.put(app.Id, app);
        }
        List<Application_Member__c> appMemberList = [SELECT Id, Application__c FROM Application_Member__c Where Application__c In :appMap.keySet()];
        for(Id appid : appMap.keySet()) {
            appMemberMap.put(appid , getAppMember(appid, appMemberList));
        }

        
        for(Application__c app : appList) {
            //COP
            if(getRand(0,10) > 3) {
                app.COP_Preference_Manual__c = prefManual[getRand(0,3)];  
                if(getRand(0,3) == 0)
                    app.COP_Opt_Out__c = true;
                if(getRand(0,2) != 0)
                app.COP_Preference_Member__c = appMemberMap.get(app.Id)[getRand(0,appMemberMap.get(app.Id).size() - 1)].Id;
            }
            //DTHP
            if(getRand(0,10) > 3) {
                app.DTHP_Preference_Manual__c = prefManual[getRand(0,3)]; 
                if(getRand(0,3) == 0)
                    app.DTHP_Opt_Out__c = true;
                if(getRand(0,2) != 0)
                app.DTHP_Preference_Member__c = appMemberMap.get(app.Id)[getRand(0,appMemberMap.get(app.Id).size() - 1)].Id;
            }
            //NRHP
            if(getRand(0,10) > 6) {
                app.Neighborhood_Preference_Manual__c = NRHPManual[getRand(0,3)];  
                if(getRand(0,3) == 0)
                    app.NRHP_Opt_Out__c = true;
                if(getRand(0,2) != 0)
                app.Neighborhood_Preference_Member__c = appMemberMap.get(app.Id)[getRand(0,appMemberMap.get(app.Id).size() - 1)].Id;
            }
            //Live/Work
            if(getRand(0,10) > 6) {
                app.Live_Work_Preference_Paper__c = (getRand(0,10) > 8) ? true : false; 
                if(getRand(0,4) == 0)
                    app.Live_Work_Opt_Out__c = true;
                if(getRand(0,1) == 0)
                app.Live_in_SF_Preference_Member__c = appMemberMap.get(app.Id)[getRand(0,appMemberMap.get(app.Id).size() - 1)].Id;
                if(getRand(0,1) == 0)
                app.Work_in_SF_Preference_Member__c = appMemberMap.get(app.Id)[getRand(0,appMemberMap.get(app.Id).size() - 1)].Id;
            }
            app.Is_Migrated__c = true;
        }
        Database.update(appList,false);
    }

}