src/objects/Certificate_Program__c.object
<CustomObject>
    <description>Certificate Program requests and approved certifications.</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Certificate_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Contact__c</fullName>
        <label>Household Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Certificate_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Submit_Date__c</fullName>
        <label>Submit Date</label>
        <type>Date</type>
    </fields>
    <label>Certificate Program</label>
    <nameField>
        <displayFormat>CP-{YY}-{MM}-{0}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificate Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_MOHCDViewMyCertsCC.cls
/*
* @auther : Cloud Sherpas Inc.
* @date : 07/15/2014
* @description : Apex class for mohcdViewMyCerts VF Page
*/ 
public with sharing class CS_MOHCDViewMyCertsCC {
    
    //Public Variables
    public List<Certificate_Program__c> lMyCertificatePrograms {get; set;}   
    
    //Constructor   
    public CS_MOHCDViewMyCertsCC() {
        lMyCertificatePrograms = new List<Certificate_Program__c>();
        
        User usr = [SELECT ID, Name, ContactId, Contact.AccountId FROM USer WHERE Id =: Userinfo.getUserId() LIMIT 1];
        
        lMyCertificatePrograms = [SELECT RecordTypeId, RecordType.Name, Household_Account__c,         
            Submit_Date__c, Name, Id, Application_Status__c, Household_Contact__c 
            FROM Certificate_Program__c 
            WHERE Household_Account__c =: usr.Contact.AccountId 
            AND Household_Contact__c =: usr.ContactId];
    }
}