src/objects/Certificate_Program__c.object
<CustomObject>
    <description>Certificate Program requests and approved certifications.</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Current_Address__c</fullName>
        <label>Current Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Displacement_Address_1__c</fullName>
        <label>Displacement Address 1</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Displacement_Address_2__c</fullName>
        <label>Displacement Address 2</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>Certificate_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Contact__c</fullName>
        <label>Household Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Certificate_Applications</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Hunters_Point_between_1966_and_1975__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Did you live in Hunters Point between the years of 1966 and 1975?</description>
        <inlineHelpText>Did you live in Hunters Point between the years of 1966 and 1975?</inlineHelpText>
        <label>Hunters Point between 1966 and 1975?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>In_what_year_were_you_displaced_2__c</fullName>
        <label>In what year were you displaced 2</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>In_what_year_were_you_displaced__c</fullName>
        <label>In what year were you displaced 1</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Name_of_Head_of_Household_when_Displaced__c</fullName>
        <label>Name of Head of Household when Displaced</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Requester_s_Mailing_Address__c</fullName>
        <formula>Household_Account__r.Mailing_Address__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Requester&apos;s Mailing Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Submit_Date__c</fullName>
        <label>Submit Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Telephone_Number__c</fullName>
        <label>Telephone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Western_Addition_between_1966_and_1975__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Did you live in Western Addition between the years of 1966 and 1975?</description>
        <inlineHelpText>Did you live in Western Addition between the years of 1966 and 1975?</inlineHelpText>
        <label>Western Addition between 1966 and 1975?</label>
        <type>Checkbox</type>
    </fields>
    <label>Certificate Program</label>
    <nameField>
        <displayFormat>CP-{YY}-{MM}-{0}</displayFormat>
        <label>Record ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Certificate Programs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Current_Address__c</fullName>
        <formula>Street_Number__c &amp; &quot; &quot; &amp; Street_Name__c &amp; &quot; &quot; &amp; IF( TEXT(Street_Type__c)=&quot;[Not Applicable]&quot;,&quot;&quot;,TEXT(Street_Type__c)) &amp; IF(ISBLANK(Apt_Unit__c),&quot;&quot;, &quot; #&quot; &amp; Apt_Unit__c ) &amp; BR()
&amp; IF(Address_Line_2__c = &quot;&quot;, &quot;&quot;, Address_Line_2__c &amp; BR())
&amp; City__c &amp; &quot;, &quot; &amp; TEXT(State__c) &amp; &quot; &quot; &amp; Zip_Code__c</formula>
        <label>Current Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Head_of_Household2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Registered Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Great Grandparent</fullName>
                </value>
                <value>
                    <fullName>In-Law</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprogramsNewCertAppCont.cls
/***************************************************************************
 * @author Kimiko Roberto
 * @date 16 May 2014
 * @description An apex page controller that supports creation of New Certificate Application
    for users
 * @revision(s)
 ***************************************************************************/
public with sharing class SfmohprogramsNewCertAppCont {


    public String firstName {get; set;}
    public String lastName {get; set;}
    public String address {get; set;}
    public String phone {get; set;}
    public String email {get; set;}
    public String conId {get; set;}
    public Contact con_detail {get; set;}
    public String relToHH {get;set;}
    public String dpAdd1 {get; set;}
    public String dpAdd2 {get; set;}
    public String yrOfDp {get; set;}
    public String yrOfDp2 {get; set;}
    public String nameOfHHDp {get; set;}
    List<Contact> fetchCon = new List<Contact>();
    public Boolean isWestern {get; set;}
    public Boolean isHunters {get; set;}
    public Boolean isDisplaced {get; set;}
    public List<SfmohprogramsWrapperClass.wContact> wrpContact {get;set;}
    SfmohprogramsWrapperClass conwrap = new SfmohprogramsWrapperClass();
    public SfmohprogramsNewCertAppCont() {
        wrpContact = conwrap.getContacts2();
        
    }



    public PageReference selectContact(){
        if(conId == '' || conId == null){
            firstName = '';
            lastName = '';
            address = '';
            phone = '';
            email = '';
        }
        else if(conId != '' || conId != null){
            fetchCon = [SELECT Id,
                               AccountId,
                               FirstName,
                               LastName,
                               Phone,
                               Email,
                               Current_Address__c
                               FROM Contact
                               WHERE Id =: conId];
            for (Contact c : fetchCon) {
                firstName = c.FirstName;
                lastName = c.LastName;
                address = c.Current_Address__c.replace('<br>','   ');
                phone = c.Phone;
                email = c.Email;
            }
        }
        
        return null;
    }

    public PageReference submitRequest(){
    
        if (fetchCon != null && ! fetchCon.isEmpty()) {
            List<Certificate_Program__c> certAppList = new List<Certificate_Program__c>();
            Certificate_Program__c certApp = new Certificate_Program__c();
            Recordtype recTypeId = [SELECT Id from Recordtype where Name=:StringConstants.CERT_RECTYPE_COP ];

                 
                
            certApp.RecordTypeId = recTypeId.Id;
            certApp.Household_Contact__c = fetchCon[0].Id;
            certApp.Household_Account__c = fetchCon[0].AccountId;
            certApp.Application_Status__c = 'Received';
            certApp.Submit_Date__c = Date.today();
            certApp.Western_Addition_between_1966_and_1975__c = isWestern;
            certApp.Hunters_Point_between_1966_and_1975__c = isHunters;
            certApp.Telephone_Number__c = phone;
            certApp.Email_Address__c = email;
            //certApp.Requester_s_Mailing_Address__c = fetchCon[0].Current_Address__c.replace('<br>',' ');
            certApp.Displacement_Address_1__c = dpAdd1;
            certApp.Displacement_Address_2__c = dpAdd2;
            certApp.Name_of_Head_of_Household_when_Displaced__c = nameOfHHDp;
            certApp.Relationship_to_Head_of_Household__c = relToHH;
            certApp.In_what_year_were_you_displaced__c = yrOfDp;
            certApp.In_what_year_were_you_displaced_2__c = yrOfDp2;
            certAppList.add(certApp);

            System.debug('********************' + certAppList);

            if (certAppList != null && !certAppList.isEmpty()) {
                insert certAppList;
            }
            //PageReference page = new PageReference('/housingprograms/'+ certApp.Id);
            //Change redirection page Ronald Martinez 07/17/2014 
            PageReference page = new PageReference('/housingprograms/mohcdViewMyCerts'); 
            page.setRedirect(true);
            return page;

        }

        

        return null;
    }


    public List<SelectOption> getPicklist() {
        
        List<SelectOption> options = new List<SelectOption>();
        options.add(new SelectOption('','--None--'));
            for(SfmohprogramsWrapperClass.wContact cn: wrpContact){
                options.add(new SelectOption(cn.con.Id,cn.con.FirstName));
            }
        return options;
    }





}