src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lender_Mortgage_Broker_Company_Name__c</fullName>
        <label>Lender/Mortgage Broker Company Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Race_Ethnicity_optional__c</fullName>
        <label>OldRace/Ethnicity</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Hispanic or Latino</fullName>
                </value>
                <value>
                    <fullName>American Indian or Alaskan Native</fullName>
                </value>
                <value>
                    <fullName>Asian</fullName>
                </value>
                <value>
                    <fullName>Black or African American</fullName>
                </value>
                <value>
                    <fullName>Native Hawaiian or Other Pacific Islander</fullName>
                </value>
                <value>
                    <fullName>White</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application__c.object
<CustomObject>
    <description>Financial Applications for MOHCD Homeownership Programs</description>
    <fields>
        <fullName>Amount_of_First_Mortgage__c</fullName>
        <label>Amount of First Mortgage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Bankrupty_Declaration_Explanation__c</fullName>
        <label>Bankrupty Declaration Explanation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Borrowers_move_in_60_days_post_closing__c</fullName>
        <inlineHelpText>Do Borrower(s) intend to occupy the property within 60 days of close of escrow?</inlineHelpText>
        <label>Borrowers move in &lt; 60 days post-closing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Development_Name__c</fullName>
        <label>Development Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Estimated_Closing_Costs__c</fullName>
        <label>Estimated Closing Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Estimated_Prepaid_Escrow__c</fullName>
        <label>Estimated Prepaid Escrow</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Has_Borrower_or_co_borrowers_owned_prop__c</fullName>
        <inlineHelpText>Has any Borrower or Co-Borrower owned any property as a principal residence?</inlineHelpText>
        <label>Has Borrower or co-borrowers owned prop?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_anyone_declared_bankruptcy_last_7yr__c</fullName>
        <label>Has anyone declared bankruptcy last 7yr</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Interest_Rate__c</fullName>
        <label>Interest Rate</label>
        <precision>18</precision>
        <scale>3</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Lender_Branch_Address__c</fullName>
        <formula>Loan_Officer__r.MailingStreet</formula>
        <label>Lender Branch Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lender_Mortgage_Broker_Company_Name__c</fullName>
        <formula>Loan_Officer__r.Account.Name</formula>
        <label>Lender/Mortgage Broker Company Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Officer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Program_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Loan_Term_of_1st_Mortgage_Years__c</fullName>
        <inlineHelpText>Loan Term in Years</inlineHelpText>
        <label>Loan Term of 1st Mortgage (Years)</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Oustanding_judgements_against_borrowers__c</fullName>
        <label>Oustanding judgements against borrowers?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Outstanding_Judgement_Explanation__c</fullName>
        <label>Outstanding Judgement Explanation</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Purchase_Price__c</fullName>
        <label>Purchase Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Ratio_First_Mortgage_Purchase_Price__c</fullName>
        <formula>Amount_of_First_Mortgage__c / Purchase_Price__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Amount of First Mortgage / Purchase Price</inlineHelpText>
        <label>Ratio (First Mortgage/Purchase Price)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Total_Costs__c</fullName>
        <formula>Purchase_Price__c + Estimated_Closing_Costs__c + Estimated_Prepaid_Escrow__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Sum of Purchase Price + Est Closing Costs + Est Prepaid Escrow</inlineHelpText>
        <label>Total Costs</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>of_Bathrooms__c</fullName>
        <label># of Bathrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Bedrooms__c</fullName>
        <label># of Bedrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <displayFormat>FA-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Financial_Application_Member__c</fullName>
        <label>Financial Application Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Application_Member__c.Financial_Application__c</field>
                <operation>equals</operation>
                <valueField>$Source.Financial_Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Application_Member__c</referenceTo>
        <relationshipLabel>Financial Application Assets for this Member</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application - Member Assets</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application Asset</label>
    <nameField>
        <displayFormat>FAA-{YY}-{0}</displayFormat>
        <label>FA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Financial_Application_Member__c</fullName>
        <label>Financial Application Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Application_Member__c.Financial_Application__c</field>
                <operation>equals</operation>
                <valueField>$Source.Financial_Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Application_Member__c</referenceTo>
        <relationshipLabel>Financial Application Incomes for this Member</relationshipLabel>
        <relationshipName>Financial_Application_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application - Member Incomes</relationshipLabel>
        <relationshipName>Financial_Application_Incomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application Income</label>
    <nameField>
        <displayFormat>FAI-{YY}-{0}</displayFormat>
        <label>FA-Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application Members</relationshipLabel>
        <relationshipName>Financial_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Address__c</fullName>
        <description>Street_Number__c &amp; &quot; &quot; &amp; Street_Name__c &amp; IF(ISPICKVAL(Street_Type__c,&quot;[Not Applicable]&quot;),&quot;&quot;, &quot; &quot; &amp; TEXT(Street_Type__c)) &amp; &quot; #&quot; &amp; Apt_Unit__c &amp; BR()

&amp; IF(Address_Line_2__c = &quot;&quot;, &quot;&quot;, Address_Line_2__c &amp; BR()) 

&amp; City__c &amp; &quot;, &quot; &amp; State__c &amp; &quot; &quot; &amp; Zip_Code__c</description>
        <formula>Street_Number__c &amp; &quot; &quot; &amp; Street_Name__c &amp; IF(ISPICKVAL(Street_Type__c,&quot;[Not Applicable]&quot;),&quot;&quot;, &quot; &quot; &amp; TEXT(Street_Type__c)) &amp; &quot; #&quot; &amp; Apt_Unit__c &amp; BR()

&amp; IF(Address_Line_2__c = &quot;&quot;, &quot;&quot;, Address_Line_2__c &amp; BR()) 

&amp; City__c &amp; &quot;, &quot; &amp; TEXT(State__c) &amp; &quot; &quot; &amp; Zip_Code__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Full Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Financial Application Member</label>
    <nameField>
        <displayFormat>MEM-{000000}</displayFormat>
        <label>Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_MOHCDFinancialAppDetailsCX.cls
/**
 * @author:      Sumit Shingavi
 * @date:        07/21/2014
 * @description: Apex class for mohcdFinancialAppDetails
 * @history:     06/10/2015 - Heidi Tang - Edited
*/ 
public class CS_MOHCDFinancialAppDetailsCX {
    
    public Financial_Application__c faInstance {get; set;}
    public Financial_Application_Member__c borrower {get; set;}
    
    public CS_MOHCDFinancialAppDetailsCX(ApexPages.StandardController controller) {
        faInstance = (Financial_Application__c) controller.getRecord();
        
        faInstance = [Select Id, Name, Application_Status__c, 
        Lender_Mortgage_Broker_Company_Name__c, Lender_Branch_Address__c,
        Loan_Officer__r.Name, Loan_Officer__r.Title, Loan_Officer__r.Work_Phone__c,
        Loan_Officer__r.Email, Loan_Officer__r.Fax,
        Property_Address__c, of_Bathrooms__c, of_Bedrooms__c, Development_Name__c,
        Has_Borrower_or_co_borrowers_owned_prop__c, Bankrupty_Declaration_Explanation__c,
        Has_anyone_declared_bankruptcy_last_7yr__c, Outstanding_Judgement_Explanation__c,
        Oustanding_judgements_against_borrowers__c, Borrowers_move_in_60_days_post_closing__c,
        
        Purchase_Price__c, Estimated_Closing_Costs__c, Estimated_Prepaid_Escrow__c, 
        Total_Costs__c, Amount_of_First_Mortgage__c, Ratio_First_Mortgage_Purchase_Price__c,
        Loan_Term_of_1st_Mortgage_Years__c, Interest_Rate__c,
        
        (Select Email_Address__c, First_Name__c, Full_Address__c, Home_Phone__c, 
            Last_Name__c, Occupation__c, Race_Ethnicity_optional__c, Work_Phone__c, 
            Borrower_Role__c, Relationship_to_Head_of_Household__c
            From Financial_Application_Members1__r), 
            
        (Select Id, Name, RecordType.Name, Employer_Name__c,  Annual_Income_Amount__c 
            From Financial_Application_Incomes__r), 
        
        (Select Id, Name, Asset_Type__c, RecordType.Name, Current_Cash_Value_of_Gift__c, Name_of_Institution__c, 
            Retirement_Asset_Type__c From Financial_Application_Assets__r),
        
        (Select Id, Title, Body From Notes WHERE isPrivate = false)
         
        From Financial_Application__c
        WHERE Id =: faInstance.Id LIMIT 1];
        
        borrower = new Financial_Application_Member__c();
        
        for(Financial_Application_Member__c fam : faInstance.Financial_Application_Members1__r) {
            if(fam.Borrower_Role__c == 'Primary Borrower') {
                borrower = fam;
                break;
            } 
        }
        System.debug(LoggingLevel.INFO, '==borrower=='+borrower);
    }
}