src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Personal_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Incomes for all Household Members</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Income</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Income</label>
    <nameField>
        <displayFormat>INC-{YY}-{0}</displayFormat>
        <label>Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprgramsPersonalIncomeTriggerTest.cls
@isTest
private class SfmohprgramsPersonalIncomeTriggerTest {
	
	private static List<Account> accts = new List<Account>();
    private static List<Contact> cons = new List<Contact>();
    private static List<Personal_Income__c> pIncomes = new List<Personal_Income__c>();
    private static User hUser;

	static testMethod void testPIncomeOnInsert() {

		Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        accts.add(CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId));
        accts.add(CS_TestDataSetup.createTestAccount('Test Account 2', '1234512345', 'IT Software', rtId));
        accts.add(CS_TestDataSetup.createTestAccount('Test Account 3', '1234512345', 'IT Software', rtId));
        insert accts;
        
        Id hConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        cons.add(CS_TestDataSetup.createTestContact(accts[0].Id, 'Contact01', 'Test01', 'test@mail01.com', hConRTId));
        cons.add(CS_TestDataSetup.createTestContact(accts[0].Id, 'Contact02', 'Test02', 'test@mail02.com', hConRTId));
        cons.add(CS_TestDataSetup.createTestContact(accts[0].Id, 'Contact03', 'Test03', 'test@mail03.com', hConRTId));
        insert cons;   

		Id pIncomeRTId = Schema.SObjectType.Personal_Income__c.getRecordTypeInfosByName().get('Employment Income').getRecordTypeId();
        pIncomes.add(new Personal_Income__c(Household_Member__c=cons[0].Id, RecordTypeId =pIncomeRTId));
		pIncomes.add(new Personal_Income__c(Household_Member__c=cons[1].Id, RecordTypeId =pIncomeRTId));
		pIncomes.add(new Personal_Income__c(Household_Member__c=cons[2].Id, RecordTypeId =pIncomeRTId));            

       	Test.startTest();
        	insert pIncomes;
        Test.stopTest();
        
        Set<Id> pIncomeIds = new Set<Id>();

        for(Personal_Income__c pInc : pIncomes){
            	pIncomeIds.add(pInc.Id);
        }

		pIncomes = new List<Personal_Income__c>([SELECT Household_Account__c 
						FROM Personal_Income__c WHERE Id IN :pIncomeIds]);            

		for(Integer i=0;i<pIncomes.size();i++){
			System.assert(pIncomes[i].Household_Account__c != null);
		}
    }
}