src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Personal_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Assets for all Household Members</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Assets</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Asset</label>
    <nameField>
        <displayFormat>HHMA-{YY}-{0}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprgramsPersonalAssetTriggerTest.cls
@isTest
private class SfmohprgramsPersonalAssetTriggerTest {
		
	private static List<Account> accts = new List<Account>();
    private static List<Contact> cons = new List<Contact>();
    private static List<Personal_Asset__c> pAssets = new List<Personal_Asset__c>();
    private static User hUser;

	static testMethod void testPAssetOnInsert() {

		Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        accts.add(CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId));
        accts.add(CS_TestDataSetup.createTestAccount('Test Account 2', '1234512345', 'IT Software', rtId));
        accts.add(CS_TestDataSetup.createTestAccount('Test Account 3', '1234512345', 'IT Software', rtId));
        insert accts;
        
        Id hConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        cons.add(CS_TestDataSetup.createTestContact(accts[0].Id, 'Contact01', 'Test01', 'test@mail01.com', hConRTId));
        cons.add(CS_TestDataSetup.createTestContact(accts[0].Id, 'Contact02', 'Test02', 'test@mail02.com', hConRTId));
        cons.add(CS_TestDataSetup.createTestContact(accts[0].Id, 'Contact03', 'Test03', 'test@mail03.com', hConRTId));
        insert cons;   

        Id pAssetRTId = Schema.SObjectType.Personal_Asset__c.getRecordTypeInfosByName().get('Assets with an Account').getRecordTypeId();
        pAssets.add(new Personal_Asset__c(Household_Member__c=cons[0].Id, RecordTypeId =pAssetRTId));
		pAssets.add(new Personal_Asset__c(Household_Member__c=cons[1].Id, RecordTypeId =pAssetRTId));
		pAssets.add(new Personal_Asset__c(Household_Member__c=cons[2].Id, RecordTypeId =pAssetRTId));            

       	Test.startTest();
        	insert pAssets;
        Test.stopTest();
        
        Set<Id> pAssetIds = new Set<Id>();

        for(Personal_Asset__c pAss : pAssets){
            	pAssetIds.add(pAss.Id);
        }

		pAssets = new List<Personal_Asset__c>([SELECT Household_Account__c 
						FROM Personal_Asset__c WHERE Id IN :pAssetIds]);            

		for(Integer i=0;i<pAssets.size();i++){
			System.assert(pAssets[i].Household_Account__c != null);
		}
    }
	
}