src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application__c.object
<CustomObject>
    <description>Financial Applications for MOHCD Homeownership Programs</description>
    <fields>
        <fullName>Copy_Existing_Info__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do you want to copy existing information from the Household account and application? Check to copy, uncheck to start a blank application.</inlineHelpText>
        <label>Copy Existing Information ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Development_Name__c</fullName>
        <label>Development Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Housing_Application__c.Household_Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <displayFormat>FA-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <recordTypes>
        <fullName>DALP</fullName>
        <active>true</active>
        <description>Downpayment Assistance - General Downpayment Assistance Loan Program (DALP)</description>
        <label>DALP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Development_Name__c</fullName>
        <formula>Property_of_Interest__r.Development_Name__c</formula>
        <label>Development Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Housing Applications</relationshipLabel>
        <relationshipName>Housing_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Personal_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Assets for all Household Members</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Assets</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Asset</label>
    <nameField>
        <displayFormat>HHMA-{YY}-{0}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Personal_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Incomes for all Household Members</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Income</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Income</label>
    <nameField>
        <displayFormat>INC-{YY}-{0}</displayFormat>
        <label>Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>Development_Name__c</fullName>
        <label>Development Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <description>Property level details (including the block and lot number)</description>
        <label>Property</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SfmohprogramsFinAppTriggerTest.cls
@isTest
private class SfmohprogramsFinAppTriggerTest {
	
	private static Account acc;
    private static Contact con;
    private static List<Properties__c> lProperties = new List<Properties__c>();
    private static List<Housing_Application__c> housingApps = new List<Housing_Application__c>();
    private static List<Financial_Application__c> finApps = new List<Financial_Application__c>();
    private static User hUser;

	static void testData(){
		Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        acc = CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId);
        insert acc;
        
        Id lenderConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        con = CS_TestDataSetup.createTestContact(acc.Id, 'Contact', 'Test', 'test@mail.com', lenderConRTId);
        insert con;        
        
        Id pIncomeRTId = Schema.SObjectType.Personal_Income__c.getRecordTypeInfosByName().get('Employment Income').getRecordTypeId();
        Personal_Income__c pIncome = new Personal_Income__c(Household_Account__c=acc.Id,Household_Member__c=con.Id, RecordTypeId =pIncomeRTId);
        insert pIncome;

        Id pAssetRTId = Schema.SObjectType.Personal_Asset__c.getRecordTypeInfosByName().get('Assets with an Account').getRecordTypeId();
        Personal_Asset__c pAsset = new Personal_Asset__c(Household_Account__c=acc.Id,Household_Member__c=con.Id,RecordTypeId =pAssetRTId);
        insert pAsset;

        Id mohcdHouseholdProfileId = [SELECT Id FROM Profile WHERE Name = :StringConstants.HOUSEHOLD_PROFILE LIMIT 1].Id;
        hUser = CS_TestDataSetup.createTestPortalUser('FName1', 'LName1', 'test1@fakemail.com', mohcdHouseholdProfileId, con.Id);
        insert hUser;
	}
	
	static testMethod void testFAppAssetOnInsert() {

		testData();

        System.runAs(hUser){

	        Id propRtId = Schema.SObjectType.Properties__c.getRecordTypeInfosByName().get('Property').getRecordTypeId();
	        
	       	Properties__c lProp = CS_TestDataSetup.createTestProperties(130000, 'Rental', 4.5, 2, 'New', 'Condo', 'Castro', propRtId);
	       	lProp.Development_Name__c = 'Property Ownership';
	        lProperties.add(lProp);           
	        lProperties.add(CS_TestDataSetup.createTestProperties(130000, 'Ownership', 4.5, 2, 'New', 'Apartment', 'Castro', propRtId));
	        lProperties.add(CS_TestDataSetup.createTestProperties(130000, 'Rental', 4.5, 2, 'New', 'Condo', 'Castro', propRtId));           
	        insert lProperties;       

	        Housing_Application__c hApp = CS_TestDataSetup.createHousingApplication(lProperties[0].Id, 'Submitted');
	        hApp.Household_Account__c = acc.Id;
	        housingApps.add(hApp);
	        housingApps.add(CS_TestDataSetup.createHousingApplication(lProperties[1].Id, 'Submitted'));
	        housingApps.add(CS_TestDataSetup.createHousingApplication(lProperties[2].Id, 'Submitted'));
	        insert housingApps;

			Id dalpRTId = Schema.SObjectType.Financial_Application__c.getRecordTypeInfosByName().get('DALP').getRecordTypeId();        
        	Financial_Application__c finApp = CS_TestDataSetup.createFinancialApplication(housingApps[0].Id, 'Submitted', acc.Id, dalpRTId, con.Id);
        	finApp.Copy_Existing_Info__c = true;
        	finApps.add(finApp);
        	
        	Test.startTest();
        		insert finApps;

        	    finApps = new List<Financial_Application__c>();
        		finApps.add(CS_TestDataSetup.createFinancialApplication(housingApps[1].Id, 'Submitted', acc.Id, dalpRTId, con.Id));
	        	finApps.add(CS_TestDataSetup.createFinancialApplication(housingApps[2].Id, 'Submitted', acc.Id, dalpRTId, con.Id));

	        	insert finApps;

        	Test.stopTest();
            
        	for(Financial_Application__c fApp : finApps){
        		System.assert(fApp.Id != null);
        	}
        }
    }
}