src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application__c.object
<CustomObject>
    <description>Financial Applications for MOHCD Homeownership Programs</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Copy_Existing_Info__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do you want to copy existing information from the Household account and application? Check to copy, uncheck to start a blank application.</inlineHelpText>
        <label>Copy Existing Information ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Housing_Application__c.Household_Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <displayFormat>FA-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <recordTypes>
        <fullName>DALP</fullName>
        <active>true</active>
        <description>Downpayment Assistance - General Downpayment Assistance Loan Program (DALP)</description>
        <label>DALP</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Financial_Application_Member__c</fullName>
        <label>Financial Application Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Application_Member__c.Financial_Application__c</field>
                <operation>equals</operation>
                <valueField>$Source.Financial_Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Application_Member__c</referenceTo>
        <relationshipLabel>Financial Application Assets for this Member</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application - Member Assets</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application Asset</label>
    <nameField>
        <displayFormat>FAA-{YY}-{0}</displayFormat>
        <label>FA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Financial_Application_Member__c</fullName>
        <label>Financial Application Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Application_Member__c.Financial_Application__c</field>
                <operation>equals</operation>
                <valueField>$Source.Financial_Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Application_Member__c</referenceTo>
        <relationshipLabel>Financial Application Incomes for this Member</relationshipLabel>
        <relationshipName>Financial_Application_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application - Member Incomes</relationshipLabel>
        <relationshipName>Financial_Application_Incomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application Income</label>
    <nameField>
        <displayFormat>FAI-{YY}-{0}</displayFormat>
        <label>FA-Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Incomes</pluralLabel>
    <recordTypes>
        <fullName>Unemployed</fullName>
        <active>true</active>
        <description>Unemployed Income Status (fill in additional unemployment details here)</description>
        <label>Unemployed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application Members</relationshipLabel>
        <relationshipName>Financial_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Application Member</label>
    <nameField>
        <displayFormat>MEM-{000000}</displayFormat>
        <label>Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Housing Applications</relationshipLabel>
        <relationshipName>Housing_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Personal_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Assets for all Household Members</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Assets</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Asset</label>
    <nameField>
        <displayFormat>HHMA-{YY}-{0}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Personal_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Incomes for all Household Members</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Income</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Income</label>
    <nameField>
        <displayFormat>INC-{YY}-{0}</displayFormat>
        <label>Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Income</pluralLabel>
    <recordTypes>
        <fullName>Unemployed</fullName>
        <active>true</active>
        <description>Unemployed Income Status (fill in additional unemployment details here)</description>
        <label>Unemployed</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <description>Property level details (including the block and lot number)</description>
        <label>Property</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_MOHCDSubmitFinancialApplicationCXTest.cls
@isTest
private class CS_MOHCDSubmitFinancialApplicationCXTest {
    
    private static Account acc;
    private static Contact con;
    private static Contact con1;
    private static List<Properties__c> lProperties;
    private static Housing_Application__c housingApp;
    private static Financial_Application__c financialApp;
    private static Financial_Application_Member__c financialMember;
    private static Financial_Application_Income__c financialIncome;
    private static Financial_Application_Asset__c financialAsset;
    private static User hUser;
    
    static void testData(){
        Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        acc = CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId);
        insert acc;
        
        Id lenderConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        con = CS_TestDataSetup.createTestContact(acc.Id, 'Contact', 'Test', 'test@mail.com', lenderConRTId);
        insert con;        
        
        Id pIncomeRTId = Schema.SObjectType.Personal_Income__c.getRecordTypeInfosByName().get('Employment Income').getRecordTypeId();
        Personal_Income__c pIncome = new Personal_Income__c(Household_Account__c=acc.Id,Household_Member__c=con.Id, RecordTypeId =pIncomeRTId);
        insert pIncome;

        Id pAssetRTId = Schema.SObjectType.Personal_Asset__c.getRecordTypeInfosByName().get('Assets with an Account').getRecordTypeId();
        Personal_Asset__c pAsset = new Personal_Asset__c(Household_Account__c=acc.Id,Household_Member__c=con.Id,RecordTypeId =pAssetRTId);
        insert pAsset;

        Id mohcdHouseholdProfileId = [SELECT Id FROM Profile WHERE Name = :StringConstants.HOUSEHOLD_PROFILE LIMIT 1].Id;
        hUser = CS_TestDataSetup.createTestPortalUser('FName1', 'LName1', 'test1@fakemail.com', mohcdHouseholdProfileId, con.Id);
        insert hUser;

        lProperties = new List<Properties__c>();
        Id propRtId = Schema.SObjectType.Properties__c.getRecordTypeInfosByName().get('Property').getRecordTypeId();
        lProperties.add(CS_TestDataSetup.createTestProperties(130000, 'Rental', 4.5, 2, 'New', 'Condo', 'Castro', propRtId));
        lProperties.add(CS_TestDataSetup.createTestProperties(130000, 'Ownership', 4.5, 2, 'New', 'Apartment', 'Castro', propRtId));
        insert lProperties;
                
        housingApp = CS_TestDataSetup.createHousingApplication(lProperties[0].Id, 'Submitted');
        insert housingApp;
        
        Id dalpRTId = Schema.SObjectType.Financial_Application__c.getRecordTypeInfosByName().get('DALP').getRecordTypeId();        
        financialApp = CS_TestDataSetup.createFinancialApplication(housingApp.Id, 'Submitted', acc.Id, dalpRTId, con.Id);
        insert financialApp;
        
        financialMember = CS_TestDataSetup.createFinancialApplicationMember(financialApp.Id, 'Primary Borrower', 'Test', 'Member', System.today()-10000, 'Spouse');
        insert financialMember;
        
        Id fimIncomeRTId = Schema.SObjectType.Financial_Application_Income__c.getRecordTypeInfosByName().get('Unemployed').getRecordTypeId();        
        financialIncome = CS_TestDataSetup.createFinancialApplicationMemberIncome(financialApp.Id, financialMember.Id, fimIncomeRTId);
        insert financialIncome;
        
        Id fimAssetRTId = Schema.SObjectType.Financial_Application_Asset__c.getRecordTypeInfosByName().get('Cash without an Account').getRecordTypeId();        
        financialAsset = CS_TestDataSetup.createFinancialApplicationMemberAsset(financialApp.Id, financialMember.Id, fimAssetRTId);
        insert financialAsset;
    }

    static testMethod void testMOHCDSubmitFinancialApplicationCX() {
        testData();
    
        Test.startTest();
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(financialApp); 
        CS_MOHCDSubmitFinancialApplicationCX controller = new CS_MOHCDSubmitFinancialApplicationCX(stdController);       
        controller.init();
        
        financialApp = new Financial_Application__c();
        stdController = new ApexPages.StandardController(financialApp); 
        controller = new CS_MOHCDSubmitFinancialApplicationCX(stdController);
        controller.init();
        
        Test.stopTest();

        System.assert(financialApp.Id == null);
    }    

    static testMethod void testMOHCDSubmitFinancialApplicationCXError() {
        testData();
    
        Test.startTest();
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(financialApp); 
        CS_MOHCDSubmitFinancialApplicationCX controller = new CS_MOHCDSubmitFinancialApplicationCX(stdController);       
        controller.init();
        
        financialApp = new Financial_Application__c();
        stdController = new ApexPages.StandardController(financialApp); 
        controller = new CS_MOHCDSubmitFinancialApplicationCX(stdController);
        controller.faInstance.Application_Status__c = 'Submitted';
        controller.init();
        
        Test.stopTest();    

        System.assert(controller.faInstance.Application_Status__c == 'Submitted');
    }    

    static testMethod void testMOHCDSubmitFinancialApplicationCXPrepareContactList() {
        testData();

        Test.startTest();
        
        ApexPages.StandardController stdController = new ApexPages.StandardController(financialApp); 
        CS_MOHCDSubmitFinancialApplicationCX controller = new CS_MOHCDSubmitFinancialApplicationCX(stdController);       
        Map<String, Contact> contacts = controller.prepareContactList(new List<Financial_Application_Member__c>());                
        Test.stopTest();    

        System.assert(contacts == null);
    }   

    static testMethod void testMOHCDSubmitFinancialApplicationCXCatchMessage() {
        testData();
        
        Test.startTest();
            
             System.RunAs(hUser){
                LIst<Properties__c> lProperties2 = new List<Properties__c>();
                Id propRtId = Schema.SObjectType.Properties__c.getRecordTypeInfosByName().get('Property').getRecordTypeId();
                lProperties2.add(CS_TestDataSetup.createTestProperties(130000, 'Rental', 4.5, 2, 'New', 'Condo', 'Castro', propRtId));
                lProperties2.add(CS_TestDataSetup.createTestProperties(130000, 'Ownership', 4.5, 2, 'New', 'Apartment', 'Castro', propRtId));
                insert lProperties2;
                        
                Housing_Application__c housingApp2 = CS_TestDataSetup.createHousingApplication(lProperties2[0].Id, 'Submitted');
                insert housingApp2;
                
                Id dalpRTId = Schema.SObjectType.Financial_Application__c.getRecordTypeInfosByName().get('DALP').getRecordTypeId();        
                Financial_Application__c financialApp2 = CS_TestDataSetup.createFinancialApplication(housingApp2.Id, 'Not Yet Submitted', acc.Id, dalpRTId, con.Id);
                financialApp2.Copy_Existing_Info__c = true;
                insert financialApp2;
                
                Financial_Application_Member__c financialMember2 = CS_TestDataSetup.createFinancialApplicationMember(financialApp2.Id, 'Primary Borrower', 'Test', 'Member', System.today()-10000, 'Spouse');
                insert financialMember2;
                
                Id fimIncomeRTId = Schema.SObjectType.Financial_Application_Income__c.getRecordTypeInfosByName().get('Employment Income').getRecordTypeId();        
                Financial_Application_Income__c financialIncome2 = CS_TestDataSetup.createFinancialApplicationMemberIncome(financialApp2.Id, financialMember2.Id, fimIncomeRTId);
                insert financialIncome2;
                
                Id fimAssetRTId = Schema.SObjectType.Financial_Application_Asset__c.getRecordTypeInfosByName().get('Cash without an Account').getRecordTypeId();        
                Financial_Application_Asset__c financialAsset2 = CS_TestDataSetup.createFinancialApplicationMemberAsset(financialApp2.Id, financialMember2.Id, fimAssetRTId);
                insert financialAsset2;
        
                ApexPages.StandardController stdController = new ApexPages.StandardController(financialApp2); 
                CS_MOHCDSubmitFinancialApplicationCX controller = new CS_MOHCDSubmitFinancialApplicationCX(stdController);       
                controller.init();                                
            }
        Test.stopTest();
    }

    static testMethod void testMOHCDSubmitFinancialApplicationCXHappyPath() {
        testData();
        
        Test.startTest();
            
             System.RunAs(hUser){
                LIst<Properties__c> lProperties2 = new List<Properties__c>();
                Id propRtId = Schema.SObjectType.Properties__c.getRecordTypeInfosByName().get('Property').getRecordTypeId();
                lProperties2.add(CS_TestDataSetup.createTestProperties(130000, 'Rental', 4.5, 2, 'New', 'Condo', 'Castro', propRtId));
                lProperties2.add(CS_TestDataSetup.createTestProperties(130000, 'Ownership', 4.5, 2, 'New', 'Apartment', 'Castro', propRtId));
                insert lProperties2;
                        
                Housing_Application__c housingApp2 = CS_TestDataSetup.createHousingApplication(lProperties2[0].Id, 'Submitted');
                housingApp2.Household_Account__c = acc.Id;
                insert housingApp2;
                
                Id dalpRTId = Schema.SObjectType.Financial_Application__c.getRecordTypeInfosByName().get('DALP').getRecordTypeId();        
                Financial_Application__c financialApp2 = CS_TestDataSetup.createFinancialApplication(housingApp2.Id, 'Not Yet Submitted', acc.Id, dalpRTId, con.Id);
                financialApp2.Copy_Existing_Info__c = true;
                insert financialApp2;
                
                Financial_Application_Member__c financialMember2 = CS_TestDataSetup.createFinancialApplicationMember(financialApp2.Id, 'Primary Borrower', 'Test', 'Member', System.today()-10000, 'Spouse');
                insert financialMember2;
                
                Id fimIncomeRTId = Schema.SObjectType.Financial_Application_Income__c.getRecordTypeInfosByName().get('Employment Income').getRecordTypeId();        
                Financial_Application_Income__c financialIncome2 = CS_TestDataSetup.createFinancialApplicationMemberIncome(financialApp2.Id, financialMember2.Id, fimIncomeRTId);
                insert financialIncome2;
                
                Id fimAssetRTId = Schema.SObjectType.Financial_Application_Asset__c.getRecordTypeInfosByName().get('Cash without an Account').getRecordTypeId();        
                Financial_Application_Asset__c financialAsset2 = CS_TestDataSetup.createFinancialApplicationMemberAsset(financialApp2.Id, financialMember2.Id, fimAssetRTId);
                insert financialAsset2;
        
                ApexPages.StandardController stdController = new ApexPages.StandardController(financialApp2); 
                CS_MOHCDSubmitFinancialApplicationCX controller = new CS_MOHCDSubmitFinancialApplicationCX(stdController);       
                controller.init();                                
            }
        Test.stopTest();
    }

}