src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Lender_Mortgage_Broker_Company_Name__c</fullName>
        <label>Lender/Mortgage Broker Company Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application__c.object
<CustomObject>
    <description>Financial Applications for MOHCD Homeownership Programs</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lender_Mortgage_Broker_Company_Name__c</fullName>
        <formula>Loan_Officer__r.Account.Name</formula>
        <label>Lender/Mortgage Broker Company Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Loan_Officer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Loan Officer</label>
        <referenceTo>Contact</referenceTo>
        <relationshipName>Program_Applications1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <type>TextArea</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <displayFormat>FA-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_MOHCDDownPayAsstAppsCC.cls
/**
 * @author:      Sumit Shingavi
 * @date:        07/16/2014
 * @description: Apex class for mohcdDownPayAsstApps VF Page
 * @history:     06/10/2015 - Heidi Tang - Edited
*/ 
public class CS_MOHCDDownPayAsstAppsCC {

    //Public Variables
    public List<Financial_Application__c> financialAppWrapper{get; set;}
    
    public CS_MOHCDDownPayAsstAppsCC() {
        User usr = [SELECT Id,Name, ContactId, Contact.AccountId FROM User WHERE Id =: Userinfo.getUserId()];
        
        financialAppWrapper = new List<Financial_Application__c>();
        
        List<Financial_Application__c> lMyFinancialAppsSetter = new List<Financial_Application__c>([SELECT Id,RecordTypeId, RecordType.Name,Property_Address__c, Name,Lender_Mortgage_Broker_Company_Name__c,Application_Status__c,Loan_Officer__c,Loan_Officer__r.Name FROM Financial_Application__c WHERE Household_Account__c =: usr.Contact.AccountId ]);
            
        for(Financial_Application__c lMyFinancialApp :lMyFinancialAppsSetter){
            financialAppWrapper.add(lMyFinancialApp);
        }
    }
}