src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Does_this_appear_on_another_title__c</fullName>
        <label>Does this appear on another title?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Full_Time_Student__c</fullName>
        <label>Full Time Student?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Trans Male</fullName>
                </value>
                <value>
                    <fullName>Trans Female</fullName>
                </value>
                <value>
                    <fullName>Not Listed</fullName>
                </value>
                <value>
                    <fullName>Decline to State</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Has_owned_a_unit_last_3_yrs__c</fullName>
        <label>Has owned a unit (last 3 yrs)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>In_School__c</fullName>
        <label>In School?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Live_or_Work_in_San_Francisco__c</fullName>
        <label>Live or Work in San Francisco?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Married_or_Domestic_Partnered__c</fullName>
        <label>Married or Domestic Partnered?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Head_of_Household2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Registered Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Great Grandparent</fullName>
                </value>
                <value>
                    <fullName>In-Law</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Live_Or_Work_in_San_Francisco__c</fullName>
        <label>Live or Work in San Francisco?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Housing_Application_Member__c</fullName>
        <label>Housing Application Member</label>
        <referenceTo>Housing_Application_Member__c</referenceTo>
        <relationshipLabel>Housing Application Assets for this Member</relationshipLabel>
        <relationshipName>Housing_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application - Member Assets</relationshipLabel>
        <relationshipName>Housing_Application_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application Asset</label>
    <nameField>
        <displayFormat>HAA-{YY}-{0}</displayFormat>
        <label>HA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Date_of_Birth__c</fullName>
        <label>Date of Birth</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Does_this_appear_on_another_title__c</fullName>
        <label>Does this appear on another title?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>First_Name__c</fullName>
        <label>First Name</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Time_Student__c</fullName>
        <label>Full Time Student?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Gender__c</fullName>
        <label>Gender</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Female</fullName>
                </value>
                <value>
                    <fullName>Male</fullName>
                </value>
                <value>
                    <fullName>Transgender</fullName>
                </value>
                <value>
                    <fullName>Do Not Identify as Female, Male, or Transgender</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Members</relationshipLabel>
        <relationshipName>Housing_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>In_School__c</fullName>
        <label>In School?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Last_Name__c</fullName>
        <label>Last Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Live_Or_Work_in_San_Francisco__c</fullName>
        <label>Live Or Work in San Francisco?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Married_or_Domestic_Partnered__c</fullName>
        <label>Married or Domestic Partnered?</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Yes</fullName>
                </value>
                <value>
                    <fullName>No</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Registered Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Step Daughter</fullName>
                </value>
                <value>
                    <fullName>Step Son</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Step Sister</fullName>
                </value>
                <value>
                    <fullName>Step Brother</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Great Grandparent</fullName>
                </value>
                <value>
                    <fullName>Brother-In-Law</fullName>
                </value>
                <value>
                    <fullName>Daughter-In-Law</fullName>
                </value>
                <value>
                    <fullName>Father-In-Law</fullName>
                </value>
                <value>
                    <fullName>Mother-In-Law</fullName>
                </value>
                <value>
                    <fullName>Sister-In-Law</fullName>
                </value>
                <value>
                    <fullName>Son-In-Law</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprogramsHousingAppAssetTriggerTest.cls
@isTest
private class SfmohprogramsHousingAppAssetTriggerTest {
	
	private static Account acc;
    private static Contact con;
    private static List<Properties__c> lProperties = new List<Properties__c>();
    private static List<Housing_Application__c> housingApps = new List<Housing_Application__c>();
    private static List<Housing_Application_Member__c> housingAppMembers = new List<Housing_Application_Member__c>();
    private static List<Housing_Application_Asset__c> housingAppAssets = new List<Housing_Application_Asset__c>();
    private static User hUser;

	static void testData(){
		Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        acc = CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId);
        insert acc;
        System.assertNotEquals(null, acc.Id);
        
        Id lenderConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        con = CS_TestDataSetup.createTestContact(acc.Id, 'Contact', 'Test', 'test@mail.com', lenderConRTId);
        insert con;        
        System.assertNotEquals(null, con.Id);
            
        Id mohcdHouseholdProfileId = [SELECT Id FROM Profile WHERE Name = :StringConstants.HOUSEHOLD_PROFILE LIMIT 1].Id;
        hUser = CS_TestDataSetup.createTestPortalUser('FName1', 'LName1', 'test1@fakemail.com', mohcdHouseholdProfileId, con.Id);
        insert hUser;
	}
	
	static testMethod void testHAppAssetOnInsert() {

		testData();

        System.runAs(hUser){

	        Id propRtId = Schema.SObjectType.Properties__c.getRecordTypeInfosByName().get('Property').getRecordTypeId();
	        lProperties.add(CS_TestDataSetup.createTestProperties(130000, 'Rental', 4.5, 2, 'New', 'Condo', 'Castro', propRtId));           
	        lProperties.add(CS_TestDataSetup.createTestProperties(130000, 'Ownership', 4.5, 2, 'New', 'Apartment', 'Castro', propRtId));
	        lProperties.add(CS_TestDataSetup.createTestProperties(130000, 'Rental', 4.5, 2, 'New', 'Condo', 'Castro', propRtId));           
	        insert lProperties;       

	        housingApps.add(CS_TestDataSetup.createHousingApplication(lProperties[0].Id, 'Submitted'));
	        housingApps.add(CS_TestDataSetup.createHousingApplication(lProperties[1].Id, 'Submitted'));
	        housingApps.add(CS_TestDataSetup.createHousingApplication(lProperties[2].Id, 'Submitted'));
	        insert housingApps;

	        housingAppMembers.add(new Housing_Application_Member__c(Housing_Application__c=housingApps[0].Id, First_Name__c = 'FTest1',
                                    Last_Name__c = 'LTest1',Work_Phone__c='9421341099',Relationship_to_Head_of_Household__c = 'Brother',
                                    Occupation__c='Student',Date_of_Birth__c=Date.today()-7000, In_School__c='No',Gender__c='Female',
                                    Full_Time_Student__c='Yes',Married_or_Domestic_Partnered__c='Yes',Live_Or_Work_in_San_Francisco__c='Yes',
                                    Does_this_appear_on_another_title__c='Yes',Has_owned_a_unit_last_3_yrs__c='No'));

	        housingAppMembers.add(new Housing_Application_Member__c(Housing_Application__c=housingApps[1].Id, First_Name__c = 'FTest2',
                                    Last_Name__c = 'LTest2',Work_Phone__c='9421341099',Relationship_to_Head_of_Household__c = 'Sister',
                                    Occupation__c='Student',Date_of_Birth__c=Date.today()-7000, In_School__c='No',Gender__c='Female',
                                    Full_Time_Student__c='Yes',Married_or_Domestic_Partnered__c='Yes',Live_Or_Work_in_San_Francisco__c='Yes',
                                    Does_this_appear_on_another_title__c='Yes',Has_owned_a_unit_last_3_yrs__c='No'));

	        housingAppMembers.add(new Housing_Application_Member__c(Housing_Application__c=housingApps[2].Id, First_Name__c = 'FTest3',
                                    Last_Name__c = 'LTest3',Work_Phone__c='9421341099',Relationship_to_Head_of_Household__c = 'Self',
                                    Occupation__c='Student',Date_of_Birth__c=Date.today()-7000, In_School__c='No',Gender__c='Female',
                                    Full_Time_Student__c='Yes',Married_or_Domestic_Partnered__c='Yes',Live_Or_Work_in_San_Francisco__c='Yes',
                                    Does_this_appear_on_another_title__c='Yes',Has_owned_a_unit_last_3_yrs__c='No'));

        	insert housingAppMembers;
        	

        	housingAppAssets.add(new Housing_Application_Asset__c(Housing_Application_Member__c = housingAppMembers[0].Id));
        	housingAppAssets.add(new Housing_Application_Asset__c(Housing_Application_Member__c = housingAppMembers[1].Id));
        	housingAppAssets.add(new Housing_Application_Asset__c(Housing_Application_Member__c = housingAppMembers[2].Id));

        	Test.startTest();
        		insert housingAppAssets;
        	Test.stopTest();
            
        	Set<Id> hAssetIds = new Set<Id>();

            for(Housing_Application_Asset__c hAppAss : housingAppAssets){
            	hAssetIds.add(hAppAss.Id);
            }

			housingAppAssets = new List<Housing_Application_Asset__c>([SELECT Housing_Application__c 
									FROM Housing_Application_Asset__c WHERE Id IN :hAssetIds]);            

			for(Integer i=0;i<housingAppAssets.size();i++){
				System.assert(housingAppAssets[i].Housing_Application__c != null);
			}
        }
    }
}