src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Apt_Unit__c</fullName>
        <label>Apt./Unit #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Type__c</fullName>
        <label>Street Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>[Not Applicable]</fullName>
                </value>
                <value>
                    <fullName>Alley</fullName>
                </value>
                <value>
                    <fullName>Avenue</fullName>
                </value>
                <value>
                    <fullName>Boulevard</fullName>
                </value>
                <value>
                    <fullName>Circle</fullName>
                </value>
                <value>
                    <fullName>Court</fullName>
                </value>
                <value>
                    <fullName>Drive</fullName>
                </value>
                <value>
                    <fullName>Highway</fullName>
                </value>
                <value>
                    <fullName>Lane</fullName>
                </value>
                <value>
                    <fullName>Loop</fullName>
                </value>
                <value>
                    <fullName>Park</fullName>
                </value>
                <value>
                    <fullName>Place</fullName>
                </value>
                <value>
                    <fullName>Plaza</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
                <value>
                    <fullName>Row</fullName>
                </value>
                <value>
                    <fullName>Square</fullName>
                </value>
                <value>
                    <fullName>Street</fullName>
                </value>
                <value>
                    <fullName>Terrace</fullName>
                </value>
                <value>
                    <fullName>Walk</fullName>
                </value>
                <value>
                    <fullName>Way</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_MOHCDUpdateContactCXTest.cls
@isTest
private class CS_MOHCDUpdateContactCXTest {

    private static Account acc;
    private static Account portalAccount1;
    private static Contact con;
    private static Contact contact1;
    private static User user1;
    private static User testUser;
    private static User portalUser;
    private static User portalAccountOwner1;
    
    
    
    static testMethod void UpdateContactCX(){
    
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile testUserID = [Select Id from Profile where name = 'System Administrator'];
        testUser = CS_TestDataSetup.createTestUser('FName1', 'LName1', testUserID.Id);       
        testUser.UserRoleId = portalRole.Id;    
        insert testUser;
        
        System.RunAs(testUser){
            Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
            acc = CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId);
            acc.OwnerId = testUser.Id;
            acc.Work_Phone__c = '5082444';
            acc.Mobile_Phone__c = '09161445787';
            acc.Phone = '09161445890';
            acc.Zip_Code__c = '4012';
            acc.City__c = 'sta rosa';
            acc.Street_Name__c = 'name';
            acc.Street_Number__c = 'num';
            acc.Street_Type__c = 'type';
            acc.Apt_Unit__c = 'unit';
            acc.State__c = 'California';
            acc.Email__c = 'email@email.com';
            insert acc;
            System.assertNotEquals(null, acc.Id);     
            
            Id lenderConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lending Agent').getRecordTypeId();          
            con = CS_TestDataSetup.createTestContact(acc.Id, 'Contact', 'Test', 'test@mail.com', lenderConRTId);
            con.Work_Phone__c = '5082444';
            con.MobilePhone = '09161445787';
            con.Phone = '09161445890';
            con.Zip_Code__c = '4012';
            con.City__c = 'sta rosa';
            con.Street_Name__c = 'name';
            con.Street_Number__c = 'num';
            con.Street_Type__c = 'type';
            con.Apt_Unit__c = 'unit';
            con.State__c = 'California';
            con.Email = 'email@email.com';
            insert con;
            System.assertNotEquals(null, con.Id);           
            
            
            Profile portalUserID = [SELECT Id, Name FROM Profile WHERE Name = 'MOHCD - Household' LIMIT 1];
            portalUser = CS_TestDataSetup.createTestPortalUser('First Name', 'Last Name', 'email@email.com' , portalUserID.id, con.id);
            insert portalUser;          
        }  
    
        Test.startTest();
        System.RunAs(portalUser){
            CS_MOHCDUpdateContactCX controller = new CS_MOHCDUpdateContactCX();
              
            controller.updatePhone = '09161445890';
            controller.updateMobilePhone = '09161445787';
            controller.updateWorkPhone = '5082444';
            controller.updateEmail = 'email@email.com';
            controller.updateStreetNumber = 'num';
            controller.updateStreetName = 'name';
            controller.updateStreetType = 'type';
            controller.updateAptUnit = 'unit';
            controller.updateCity = 'sta rosa';
            controller.updateState = 'California';
            controller.updateZipCode = '4012';
            controller.updateInfo();
        }
    
        Test.stopTest();        
    }

    static testMethod void UpdateContactCXUpdateContactInfo(){
        List<Profile> profiles = new List<Profile>([SELECT Id FROM Profile where Name = 'MOHCD - Household' LIMIT 1]);
        
        Account a = new Account(Name='Test Account Name');
        insert a;
 
        Contact contact = new Contact(LastName='testUserData',Email='testUserDataUnique@email.com', AccountId = a.id);
        insert contact;

        User usrVar = new User( Username = 'testUserDataUnique@email.com', FirstName='testUserData userFirstName', LastName = 'testUserData userLName', Alias = 'testA',
                                    CommunityNickname = 'testUserData',TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',EmailEncodingKey = 'ISO-8859-1',
                                    LanguageLocaleKey = 'en_US', Email = 'test@email.com',ProfileId = profiles.get(0).Id, ContactId = contact.Id, IsActive = true);

        System.runAs(usrVar){
            ApexPages.StandardController thecontroller = new ApexPages.StandardController(usrVar);
            
            CS_MOHCDUpdateContactCX controller = new CS_MOHCDUpdateContactCX(thecontroller);
            controller.updateInfo();
        }
    }

    static testMethod void UpdateContactCXUpdateContactInfoDMLException(){
        try{
            List<Profile> profiles = new List<Profile>([SELECT Id FROM Profile where Name = 'MOHCD - Household' LIMIT 1]);
            
            Account a = new Account(Name='Test Account Name');
            insert a;
     
            Contact contact = new Contact(LastName='testUserData',Email='testUserDataUnique@email.com', AccountId = a.id);
            insert contact;

            User usrVar = new User( Username = 'testUserDataUnique@email.com', FirstName='testUserData userFirstName', LastName = 'testUserData userLName', Alias = 'testA',
                                        CommunityNickname = 'testUserData',TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',EmailEncodingKey = 'ISO-8859-1',
                                        LanguageLocaleKey = 'en_US', Email = 'test@email.com',ProfileId = profiles.get(0).Id, ContactId = contact.Id, IsActive = true);

            System.runAs(usrVar){
                ApexPages.StandardController thecontroller = new ApexPages.StandardController(usrVar);
                
                CS_MOHCDUpdateContactCX controller = new CS_MOHCDUpdateContactCX(thecontroller);
                controller.currentUserContact.LastName = null;
                controller.updateInfo();
            }
        }catch(Exception e){
            System.assert(e.getMessage()=='',e.getMessage());
        }
    }
    
    static testMethod void UpdateContactCXStandardController(){
    
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile testUserID = [Select Id from Profile where name = 'System Administrator'];
        testUser = CS_TestDataSetup.createTestUser('FName1', 'LName1', testUserID.Id);       
        testUser.UserRoleId = portalRole.Id;    
        insert testUser;
        
        System.RunAs(testUser){
            Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
            acc = CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId);
            acc.OwnerId = testUser.Id; 
            acc.Work_Phone__c = '5082444';
            acc.Mobile_Phone__c = '09161445787';
            acc.Phone = '09161445890';
            acc.Zip_Code__c = '4012';
            acc.City__c = 'sta rosa';
            acc.Street_Name__c = 'name';
            acc.Street_Number__c = 'num';
            acc.Street_Type__c = 'type';
            acc.Apt_Unit__c = 'unit';
            acc.State__c = 'California';
            acc.Email__c = 'email@email.com';
            insert acc;
            System.assertNotEquals(null, acc.Id);     
            
            Id lenderConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lending Agent').getRecordTypeId();          
            con = CS_TestDataSetup.createTestContact(acc.Id, 'Contact', 'Test', 'test@mail.com', lenderConRTId);
            con.Work_Phone__c = '5082444';
            con.MobilePhone = '09161445787';
            con.Phone = '09161445890';
            con.Zip_Code__c = '4012';
            con.City__c = 'sta rosa';
            con.Street_Name__c = 'name';
            con.Street_Number__c = 'num';
            con.Street_Type__c = 'type';
            con.Apt_Unit__c = 'unit';
            con.State__c = 'California';
            con.Email = 'email@email.com';
            insert con;
            System.assertNotEquals(null, con.Id);           
            
            
            Profile portalUserID = [SELECT Id, Name FROM Profile WHERE Name = 'MOHCD - Household' LIMIT 1];
            portalUser = CS_TestDataSetup.createTestPortalUser('First Name', 'Last Name', 'email@email.com' , portalUserID.id, con.id);
            insert portalUser;          
        }  
    
        Test.startTest();
        System.RunAs(portalUser){
    
            ApexPages.StandardController thecontroller = new ApexPages.StandardController(portalUser);
            
            CS_MOHCDUpdateContactCX controller = new CS_MOHCDUpdateContactCX(thecontroller);     
            
            controller.updatePhone = '09161445890';
            controller.updateMobilePhone = '09161445787';
            controller.updateWorkPhone = '5082444';
            controller.updateEmail = 'email@email.com';
            controller.updateStreetNumber = 'num';
            controller.updateStreetName = 'name';
            controller.updateStreetType = 'type';
            controller.updateAptUnit = 'unit';
            controller.updateCity = 'sta rosa';
            controller.updateState = 'California';
            controller.updateZipCode = '4012';
            controller.contactID = con.Id;
            controller.updateInfo();
        }
    
        Test.stopTest();        
    }

    static testMethod void SelfUpdateContactCX(){
    
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile testUserID = [Select Id from Profile where name = 'System Administrator'];
        testUser = CS_TestDataSetup.createTestUser('FName1', 'LName1', testUserID.Id);       
        testUser.UserRoleId = portalRole.Id;    
        insert testUser;
        
        System.RunAs(testUser){
            Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
            acc = CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId);
            acc.OwnerId = testUser.Id;
            acc.Work_Phone__c = '5082444';
            acc.Mobile_Phone__c = '09161445787';
            acc.Phone = '09161445890';
            acc.Zip_Code__c = '4012';
            acc.City__c = 'sta rosa';
            acc.Street_Name__c = 'name';
            acc.Street_Number__c = 'num';
            acc.Street_Type__c = 'type';
            acc.Apt_Unit__c = 'unit';
            acc.State__c = 'California';
            acc.Email__c = 'email@email.com';
            insert acc;
            System.assertNotEquals(null, acc.Id);     
            
            Id lenderConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lending Agent').getRecordTypeId();          
            con = CS_TestDataSetup.createTestContact(acc.Id, 'Contact', 'Test', 'test@mail.com', lenderConRTId);
            con.Work_Phone__c = '5082444';
            con.MobilePhone = '09161445787';
            con.Phone = '09161445890';
            con.Zip_Code__c = '4012';
            con.City__c = 'sta rosa';
            con.Street_Name__c = 'name';
            con.Street_Number__c = 'num';
            con.Street_Type__c = 'type';
            con.Apt_Unit__c = 'unit';
            con.State__c = 'California';
            con.Email = 'email@email.com';
            insert con;
            System.assertNotEquals(null, con.Id);           
            
            
            Profile portalUserID = [SELECT Id, Name FROM Profile WHERE Name = 'MOHCD - Household' LIMIT 1];
            portalUser = CS_TestDataSetup.createTestPortalUser('First Name', 'Last Name', 'email@email.com' , portalUserID.id, con.id);
            insert portalUser;          
        }  
    
        Test.startTest();
        System.RunAs(portalUser){
            UpdateContactController controller = new UpdateContactController();
              
            controller.updatePhone = '09161445890';
            controller.updateMobilePhone = '09161445787';
            controller.updateWorkPhone = '5082444';
            controller.updateEmail = 'email@email.com';
            controller.updateStreetNumber = 'num';
            controller.updateStreetName = 'name';
            controller.updateStreetType = 'type';
            controller.updateAptUnit = 'unit';
            controller.updateCity = 'sta rosa';
            controller.updateState = 'California';
            controller.updateZipCode = '4012';
            controller.contactID = con.Id;
            controller.updateInfo();
        }
    
        Test.stopTest();        
    }

    static testMethod void SelfUpdateContactCXUpdateContactInfo(){
        List<Profile> profiles = new List<Profile>([SELECT Id FROM Profile where Name = 'MOHCD - Household' LIMIT 1]);
        
        Account a = new Account(Name='Test Account Name');
        insert a;
 
        Contact contact = new Contact(LastName='testUserData',Email='testUserDataUnique@email.com', AccountId = a.id);
        insert contact;

        User usrVar = new User( Username = 'testUserDataUnique@email.com', FirstName='testUserData userFirstName', LastName = 'testUserData userLName', Alias = 'testA',
                                    CommunityNickname = 'testUserData',TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',EmailEncodingKey = 'ISO-8859-1',
                                    LanguageLocaleKey = 'en_US', Email = 'test@email.com',ProfileId = profiles.get(0).Id, ContactId = contact.Id, IsActive = true);

        System.runAs(usrVar){
            ApexPages.StandardController thecontroller = new ApexPages.StandardController(usrVar);
            
            UpdateContactController controller = new UpdateContactController(thecontroller);
            controller.updateInfo();
        }
    }

    static testMethod void SelfUpdateContactCXUpdateContactInfoDMLException(){
        try{
            List<Profile> profiles = new List<Profile>([SELECT Id FROM Profile where Name = 'MOHCD - Household' LIMIT 1]);
            
            Account a = new Account(Name='Test Account Name');
            insert a;
     
            Contact contact = new Contact(LastName='testUserData',Email='testUserDataUnique@email.com', AccountId = a.id);
            insert contact;

            User usrVar = new User( Username = 'testUserDataUnique@email.com', FirstName='testUserData userFirstName', LastName = 'testUserData userLName', Alias = 'testA',
                                        CommunityNickname = 'testUserData',TimeZoneSidKey = 'America/Los_Angeles', LocaleSidKey = 'en_US',EmailEncodingKey = 'ISO-8859-1',
                                        LanguageLocaleKey = 'en_US', Email = 'test@email.com',ProfileId = profiles.get(0).Id, ContactId = contact.Id, IsActive = true);

            System.runAs(usrVar){
                ApexPages.StandardController thecontroller = new ApexPages.StandardController(usrVar);
                
                UpdateContactController controller = new UpdateContactController(thecontroller);
                controller.currentUserContact.LastName = null;
                controller.updateInfo();
            }
        }catch(Exception e){
            System.assert(e.getMessage()=='',e.getMessage());
        }
    }
    
    static testMethod void SelfUpdateContactCXStandardController(){
    
        UserRole portalRole = [Select Id From UserRole Where PortalType = 'None' Limit 1];
        Profile testUserID = [Select Id from Profile where name = 'System Administrator'];
        testUser = CS_TestDataSetup.createTestUser('FName1', 'LName1', testUserID.Id);       
        testUser.UserRoleId = portalRole.Id;    
        insert testUser;
        
        System.RunAs(testUser){
            Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
            acc = CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId);
            acc.OwnerId = testUser.Id; 
            acc.Work_Phone__c = '5082444';
            acc.Mobile_Phone__c = '09161445787';
            acc.Phone = '09161445890';
            acc.Zip_Code__c = '4012';
            acc.City__c = 'sta rosa';
            acc.Street_Name__c = 'name';
            acc.Street_Number__c = 'num';
            acc.Street_Type__c = 'type';
            acc.Apt_Unit__c = 'unit';
            acc.State__c = 'California';
            acc.Email__c = 'email@email.com';
            insert acc;
            System.assertNotEquals(null, acc.Id);     
            
            Id lenderConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Lending Agent').getRecordTypeId();          
            con = CS_TestDataSetup.createTestContact(acc.Id, 'Contact', 'Test', 'test@mail.com', lenderConRTId);
            con.Work_Phone__c = '5082444';
            con.MobilePhone = '09161445787';
            con.Phone = '09161445890';
            con.Zip_Code__c = '4012';
            con.City__c = 'sta rosa';
            con.Street_Name__c = 'name';
            con.Street_Number__c = 'num';
            con.Street_Type__c = 'type';
            con.Apt_Unit__c = 'unit';
            con.State__c = 'California';
            con.Email = 'email@email.com';
            insert con;
            System.assertNotEquals(null, con.Id);           
            
            
            Profile portalUserID = [SELECT Id, Name FROM Profile WHERE Name = 'MOHCD - Household' LIMIT 1];
            portalUser = CS_TestDataSetup.createTestPortalUser('First Name', 'Last Name', 'email@email.com' , portalUserID.id, con.id);
            insert portalUser;          
        }  
    
        Test.startTest();
        System.RunAs(portalUser){
    
            ApexPages.StandardController thecontroller = new ApexPages.StandardController(portalUser);
            
            UpdateContactController controller = new UpdateContactController(thecontroller);     
            
            controller.updatePhone = '09161445890';
            controller.updateMobilePhone = '09161445787';
            controller.updateWorkPhone = '5082444';
            controller.updateEmail = 'email@email.com';
            controller.updateStreetNumber = 'num';
            controller.updateStreetName = 'name';
            controller.updateStreetType = 'type';
            controller.updateAptUnit = 'unit';
            controller.updateCity = 'sta rosa';
            controller.updateState = 'California';
            controller.updateZipCode = '4012';
            controller.updateInfo();
        }
    
        Test.stopTest();        
    }
    
}