src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>BMR_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this lender BMR Certified?</inlineHelpText>
        <label>BMR Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DALP_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this lender DALP Certified?</inlineHelpText>
        <label>DALP Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>MCC_Certified__c</fullName>
        <defaultValue>false</defaultValue>
        <inlineHelpText>Is this lender MCC Certified?</inlineHelpText>
        <label>MCC Certified</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/DALP_Request__c.object
<CustomObject>
    <description>Object to store DALP requests.</description>
    <fields>
        <fullName>HousingApp__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>DALP Request</relationshipLabel>
        <relationshipName>DALP_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Type__c</fullName>
        <label>Housing Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BMR Pre-Approval or Refinance Request</fullName>
                </value>
                <value>
                    <fullName>Down Payment Assistance or MCC Request for BMR/City Second Properties</fullName>
                </value>
                <value>
                    <fullName>Down Payment Assistance or MCC Request for Non-MOHCD Market Rate Properties</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lender__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lender chosen on the DALP request page.</description>
        <label>Lender</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DALP Request</relationshipLabel>
        <relationshipName>DALP_Request</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Requested_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Requested By</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>DALP Request (Requested By)</relationshipLabel>
        <relationshipName>DALP_Requested_By</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>DALP Request</label>
    <nameField>
        <displayFormat>DP-{0000000}</displayFormat>
        <label>DALP Request ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>DALP Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_of_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Property/Unit of Interest that is associated with this Housing Application.</description>
        <inlineHelpText>The Property/Unit of Interest that is associated with this Housing Application.</inlineHelpText>
        <label>Property of Interest</label>
        <referenceTo>Properties__c</referenceTo>
        <relationshipLabel>Housing Applications</relationshipLabel>
        <relationshipName>Housing_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>Property_Address_Marketing__c</fullName>
        <formula>Property_Address_Street_Number__c &amp; &quot; &quot; &amp; Property_Address_Street_Name__c &amp; &quot; &quot; &amp; TEXT(Property_Address_Street_Type__c) &amp; &quot; &quot; &amp; Apt_Unit__c &amp; BR() 
&amp; Property_Address_City__c &amp; &quot;, &quot; &amp; Property_Address_State__c &amp; &quot; &quot; &amp; Property_Address_Zip_Code__c</formula>
        <label>Property Address Marketing</label>
        <type>Text</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_MOHCDDownPayRequestCC.cls
/**
 * @author:      Sumit Shingavi
 * @date:        07/17/2014
 * @description: Controller class for mohcdDownPayRequest
 * @history:     06/10/2015 - Heidi Tang - Edited
*/ 
public class CS_MOHCDDownPayRequestCC {
        
    public List<HousingApplicationWrapper> lHousingAppWraps {get; set;}
    public Contact conLender {get; set;}
    public DALP_Request__c dalpRequest {get; set;}
    public Boolean bIsSubmitted {get; set;}
    
    public CS_MOHCDDownPayRequestCC() {
        conLender = new Contact();
        bIsSubmitted = false;
        init();
    }
    
    private void init() {
        
        dalpRequest = new DALP_Request__c();
        
        String lenderId = System.currentPageReference().getParameters().get(StringConstants.PARAM_LENDER);
        if(!String.isBlank(lenderId)) {
            conLender = [SELECT Id, Name, Work_Phone__c, Email, FirstName, 
                LastName, MailingStreet, MailingCity, MailingState, MailingCountry, 
                MailingPostalCode, AccountId, Account.Name, BMR_Certified__c, 
                DALP_Certified__c, MCC_Certified__c
                FROM Contact WHERE Id =: lenderId LIMIT 1];
        }
        
        List<Housing_Application__c> lHousingApps = [Select Id, Name, Application_Status__c, 
            Property_of_Interest__c, Property_of_Interest__r.Property_Address_Marketing__c
            FROM Housing_Application__c 
            WHERE OwnerId =: Userinfo.getUserId()
            ORDER BY CreatedDate DESC];
            
        lHousingAppWraps = new List<HousingApplicationWrapper>();
        for(Housing_Application__c ha : lHousingApps) {
            lHousingAppWraps.add(new HousingApplicationWrapper(false, ha));
        }
    }
        
    public List<SelectOption> getRequestTypes() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption(Label.REQUEST_BMR,Label.REQUEST_BMR)); 
        options.add(new SelectOption(Label.REQUEST_MCC_BMR,Label.REQUEST_MCC_BMR));
        options.add(new SelectOption(Label.REQUEST_MCC_NONMOHCD,Label.REQUEST_MCC_NONMOHCD));
        return options;
    }
        
    public class HousingApplicationWrapper {
        public Boolean isSelected {get; set;}
        public Housing_Application__c ha {get; set;}
        
        public HousingApplicationWrapper(Boolean isSelected , Housing_Application__c ha) {
            this.isSelected = isSelected;
            this.ha = ha;    
        }
    }
    
    public PageReference submitFinancialProgramRequest() {
        
        try {        
            //Configure object to be inserted
            if(conLender != null && conLender.Id != null) {
                dalpRequest.Lender__c = conLender.Id;
            } else {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,Label.ERROR_SELECT_LENDER));
                return null;
            }
            
            dalpRequest.Requested_By__c = [SELECT ContactId FROM User WHERE Id =: Userinfo.getUserId() LIMIT 1].ContactId;
            
            List<Housing_Application__c> lSelectedHousingApps = new List<Housing_Application__c>();
            
            for(HousingApplicationWrapper haWrap : lHousingAppWraps) {
                if(haWrap.isSelected) {
                    lSelectedHousingApps.add(haWrap.ha);
                }
            }
            if(lSelectedHousingApps.size() > 1) {
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR,Label.ERROR_ONE_APP));
                return null;
            } else if(lSelectedHousingApps.size() == 1) {
                dalpRequest.HousingApp__c = lSelectedHousingApps[0].Id;            
            }
            
            try {
                //insert object           
                insert dalpRequest;
                
                dalpRequest = [SELECT Id, Name, Housing_Type__c FROM DALP_Request__c WHERe Id =: dalpRequest.Id];
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, Label.SUCCESS_DOWN_PAY_REQUEST +' '+ '<b>' + dalpRequest.Name + '</b>'));
                
                //temporary
                User userLender = [SELECT Id, Name FROM User WHERE Id = '005110000023Vhz'];
                
                //User userLender = [SELECT Id, Name FROM User WHERE User.ContactId =: conLender.Id];
                
                User currentUser = [SELECT name, Id, ContactID FROM User WHERE ID =: UserInfo.getUserId()];
                Contact currentUserContact = [SELECT AccountID, OwnerId FROM Contact WHERE ID =: currentUser.ContactID];
                
                Task task = new Task(WhatId = lSelectedHousingApps[0].Id, 
                    Subject = dalpRequest.Housing_Type__c, OwnerId = userLender.Id, 
                    Status = 'Not Started', Priority = 'High', Type = 'Other', WhoId = currentUserContact.Id);
                    
                insert task;
                
            } catch (Exception e) {
                System.debug(e.getMessage());
            }
            
            //reinitialize or set all previous choices after insert
            dalpRequest = new DALP_Request__c();            
            bIsSubmitted = true;
            
            init();
        
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }
}