src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <type>Picklist</type>
        <valueSet>
            <controllingField>Head_of_Household2__c</controllingField>
            <valueSetDefinition>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Registered Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Parent</fullName>
                </value>
                <value>
                    <fullName>Child</fullName>
                </value>
                <value>
                    <fullName>Sibling</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Great Grandparent</fullName>
                </value>
                <value>
                    <fullName>In-Law</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprgramsContactTriggerTest.cls
@isTest
private class SfmohprgramsContactTriggerTest {
	
	private static List<Account> accts = new List<Account>();
    private static List<Contact> cons = new List<Contact>();

	static testMethod void testContactOnUpdate() {

		Id rtId = Schema.SObjectType.Account.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        accts.add(CS_TestDataSetup.createTestAccount('Test Account', '1234512345', 'IT Software', rtId));
        accts.add(CS_TestDataSetup.createTestAccount('Test Account 2', '1234512345', 'IT Software', rtId));
        accts.add(CS_TestDataSetup.createTestAccount('Test Account 3', '1234512345', 'IT Software', rtId));
        insert accts;
        
        Id hConRTId = Schema.SObjectType.Contact.getRecordTypeInfosByName().get('Household').getRecordTypeId();
        cons.add(CS_TestDataSetup.createTestContact(accts[0].Id, 'Contact01', 'Test01', 'test@mail01.com', hConRTId));
        cons.add(CS_TestDataSetup.createTestContact(accts[1].Id, 'Contact02', 'Test02', 'test@mail02.com', hConRTId));
        cons.add(CS_TestDataSetup.createTestContact(accts[2].Id, 'Contact03', 'Test03', 'test@mail03.com', hConRTId));
        insert cons;   

        cons[0].Relationship_to_Head_of_Household__c = 'Self';
        cons[0].City__c = 'Manila';
		cons[1].Relationship_to_Head_of_Household__c = 'Self';

       	Test.startTest();
        	update cons;
        Test.stopTest();
        
		cons = new List<Contact>([SELECT City__c,Account.City__c FROM Contact WHERE Id = :cons[0].Id]);            
		System.assert(cons[0].Account.City__c == cons[0].City__c);
    }
}