src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Apt_Unit__c</fullName>
        <label>Apt./Unit #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
                <value>
                    <fullName>Nevada</fullName>
                </value>
                <value>
                    <fullName>New Hampshire</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Type__c</fullName>
        <label>Street Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>[Not Applicable]</fullName>
                </value>
                <value>
                    <fullName>Alley</fullName>
                </value>
                <value>
                    <fullName>Avenue</fullName>
                </value>
                <value>
                    <fullName>Boulevard</fullName>
                </value>
                <value>
                    <fullName>Circle</fullName>
                </value>
                <value>
                    <fullName>Court</fullName>
                </value>
                <value>
                    <fullName>Drive</fullName>
                </value>
                <value>
                    <fullName>Highway</fullName>
                </value>
                <value>
                    <fullName>Lane</fullName>
                </value>
                <value>
                    <fullName>Loop</fullName>
                </value>
                <value>
                    <fullName>Park</fullName>
                </value>
                <value>
                    <fullName>Place</fullName>
                </value>
                <value>
                    <fullName>Plaza</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
                <value>
                    <fullName>Row</fullName>
                </value>
                <value>
                    <fullName>Square</fullName>
                </value>
                <value>
                    <fullName>Street</fullName>
                </value>
                <value>
                    <fullName>Terrace</fullName>
                </value>
                <value>
                    <fullName>Walk</fullName>
                </value>
                <value>
                    <fullName>Way</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_MOHCDUpdateContactCX.cls
/**
 * An apex page controller that updates the information of User, Contact, and Account
 * Author: Crissar D. Ibarra
 * History: 
 *          7/14/14 - created - crissar ibarra
 */
 
public with sharing class CS_MOHCDUpdateContactCX{
    
    public String userFirstName{get; set;}
    public String userLastName{get; set;}
    public String updatePhone{get; set;}
    public String updateMobilePhone {get; set;}
    public String updateWorkPhone {get; set;}
    public String updateEmail {get; set;}
    public String updateStreetNumber{get; set;}
    public String updateStreetName{get; set;}
    public String updateStreetType{get; set;}
    public String updateAptUnit{get; set;}
    public String updateCity{get; set;}
    public String updateState{get; set;}
    public String updateZipCode{get; set;}
    public String contactID{get; set;}
    
    public User currentUser{get;set;}
    public Contact currentUserContact{get; set;}
    public Account currentUserContactAccount{get; set;}
    
    public string userID = UserInfo.getuserId();
        
    // Code we will invoke on page load
    public CS_MOHCDUpdateContactCX(){ 
        userID = UserInfo.getuserId();      
        userInfo();
    }
      
    // Code we will invoke on page load
    public CS_MOHCDUpdateContactCX(ApexPages.StandardController controller){ 
        
        currentUser = (User)controller.getRecord();      
        userInfo();
    }    
    
    // Method for getting the informations of the User (constructor)
    public void userInfo(){
        
        currentUser = [SELECT firstName,
                              lastName,                                                      
                              ContactID FROM User WHERE ID =: userID];
               
        this.userFirstName = currentUser.firstName;
        this.userLastName = currentUser.lastName;
        
        currentUserContact = [SELECT Work_Phone__c,
                                     Phone,
                                     MobilePhone,
                                     Email,
                                     Street_Number__c,
                                     Street_Name__c,
                                     Street_Type__c,
                                     Apt_Unit__c,
                                     City__c,
                                     State__c,
                                     Zip_Code__c,
                                     MailingCountry,
                                     HomePhone,
                                     AccountID FROM Contact WHERE ID =: currentUser.ContactID];
        
        this.updateWorkPhone = currentUserContact.Work_Phone__c;
        this.updatePhone = currentUserContact.HomePhone;
        this.updateMobilePhone = currentUserContact.MobilePhone;
        this.updateEmail = currentUserContact.Email;
        this.updateStreetNumber = currentUserContact.Street_Number__c;
        this.updateStreetName = currentUserContact.Street_Name__c;
        this.updateStreetType = currentUserContact.Street_Type__c;
        this.updateAptUnit = currentUserContact.Apt_Unit__c;
        this.updateCity = currentUserContact.City__c;
        this.updateZipCode = currentUserContact.Zip_Code__c;
        currentUserContact.MailingCountry = 'United States';
        
        currentUserContactAccount = [SELECT Work_Phone__c,
                                            Mobile_Phone__c,
                                            Phone,
                                            Zip_Code__c,
                                            City__c,                                            
                                            Street_Name__c,
                                            Street_Number__c,
                                            Street_Type__c,
                                            Apt_Unit__c,
                                            State__c,
                                            Email__c,
                                            BillingCountry FROM Account WHERE ID =: currentUserContact.AccountID];
        this.updateState = currentUserContactAccount.State__c;
        currentUserContactAccount.BillingCountry = 'United States';
    }    
    
    
    /*
    * @author : Cloud Sherpas Inc.
    * @date : 03/07/2014
    * @description : Apex method for updating the information of the contact
    * @parameters : Nothing
    * @returns : Nothing
    */  
    // Method for getting the informations of the Account
    public void accountInfo(){
        
        currentUserContactAccount.Work_Phone__c = currentUserContact.Work_Phone__c;                                   
        currentUserContactAccount.Mobile_Phone__c = currentUserContact.MobilePhone;
        currentUserContactAccount.Phone = currentUserContact.Phone;
        currentUserContactAccount.Email__c = currentUserContact.Email;
        currentUserContactAccount.Street_Name__c = currentUserContact.Street_Name__c;
        currentUserContactAccount.Street_Number__c = currentUserContact.Street_Number__c; 
        currentUserContactAccount.Street_Type__c = currentUserContact.Street_Type__c;
        currentUserContactAccount.Apt_Unit__c = currentUserContact.Apt_Unit__c ; 
        currentUserContactAccount.City__c = currentUserContact.City__c;       
        currentUserContactAccount.Zip_Code__c = currentUserContact.Zip_Code__c;
    }
    
    /*
    * @auther : Cloud Sherpas Inc.
    * @date : 03/07/2014
    * @description : Apex method that will update the informations upon being called
    * @parameters : Nothing
    * @returns : the pageReference for '/housingprograms/mohcdHome'
    */  

    public PageReference updateInfo(){   
        accountInfo();
        //currentUserContact.State__c = currentUserContactAccount.State__c;
          
        try {
            Boolean isError = false;
            ApexPages.Message msg;
            
            if(currentUserContact.Phone!=null && !Pattern.matches('\\(?\\b[0-9]{3}\\)?[-/\\s]?[0-9]{3}[-. ]?[0-9]{4}\\b',currentUserContact.Phone)){
                msg = new ApexPages.Message(ApexPages.severity.ERROR,'Invalid Format for Home Phone');                    
                isError = true;  
            }
            
            if(currentUserContact.Work_Phone__c!=null && !Pattern.matches('\\(?\\b[0-9]{3}\\)?[-/\\s]?[0-9]{3}[-. ]?[0-9]{4}\\b',currentUserContact.Work_Phone__c)){
                msg = new ApexPages.Message(ApexPages.severity.ERROR,'Invalid Format for Work Phone');                                  
                isError = true;  
            }
            
            if(currentUserContact.MobilePhone!=null && !Pattern.matches('\\(?\\b[0-9]{3}\\)?[-/\\s]?[0-9]{3}[-. ]?[0-9]{4}\\b',currentUserContact.MobilePhone)){
                msg = new ApexPages.Message(ApexPages.severity.ERROR,'Invalid Format for Mobile Phone');                      
                isError = true;  
            }
            
            if(isError){
                ApexPages.AddMessage(msg);                                
            }else{
                update currentUserContact;
                
                PageReference newPage = new PageReference('/housingprograms/mohcdHome');
                newPage.setRedirect(true);
                return newPage;
            }
        } catch (Exception e) {
            System.debug('error encountered contact ::: ' + e.getMessage());
            ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.ERROR, e.getMessage());
            ApexPages.AddMessage(msg);
        }
        /*
        try {
            update currentUserContactAccount;
        } catch (Exception e) {
            System.debug('error encountered account ::: ' + e.getMessage());
            ApexPages.Message msg = new ApexPages.Message(ApexPages.severity.ERROR, e.getMessage());
            ApexPages.AddMessage(msg);
        }
        */
        
        return null;
    }
}