src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Household</fullName>
        <active>true</active>
        <description>General Household member</description>
        <label>Household</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Application_Status__c</fullName>
        <label>Application Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Housing Applications</relationshipLabel>
        <relationshipName>Housing_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Housing_Application_Member__c</fullName>
        <label>Housing Application Member</label>
        <referenceTo>Housing_Application_Member__c</referenceTo>
        <relationshipLabel>Housing Application Assets for this Member</relationshipLabel>
        <relationshipName>Housing_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application - Member Assets</relationshipLabel>
        <relationshipName>Housing_Application_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application Asset</label>
    <nameField>
        <displayFormat>HAA-{YY}-{0}</displayFormat>
        <label>HA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Housing_Application_Member__c</fullName>
        <label>Housing Application Member</label>
        <referenceTo>Housing_Application_Member__c</referenceTo>
        <relationshipLabel>Housing Application Incomes for this Member</relationshipLabel>
        <relationshipName>Housing_Application_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application - Member Incomes</relationshipLabel>
        <relationshipName>Housing_Application_Incomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application Income</label>
    <nameField>
        <displayFormat>HAI-{YY}-{0}</displayFormat>
        <label>HA-Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Members</relationshipLabel>
        <relationshipName>Housing_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>Final_Monthly_HOA_Amount_With_Parking__c</fullName>
        <label>Final Monthly HOA Amount With Parking</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Final_Monthly_HOA_Amount_Without_Parking__c</fullName>
        <label>Final Monthly HOA Amount Without Parking</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>MLS_Listing_Link__c</fullName>
        <label>MLS Listing Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>MLS__c</fullName>
        <label>MLS #</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Maximum_AMI__c</fullName>
        <label>Maximum AMI % Allowed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Minimum_Monthly_Household_Income_Needed__c</fullName>
        <label>Minimum Monthly Household Income Needed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_HOA_Dues__c</fullName>
        <label>Monthly HOA Dues</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Monthly_Rent__c</fullName>
        <label>Monthly Rent</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Number_of_Parking_Spaces__c</fullName>
        <label>Number of Parking Spaces</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Parent_Property_Name__c</fullName>
        <formula>Parent_Property__r.Property_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Property Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parking_Price_for_Rental_Units__c</fullName>
        <label>Parking Price (for Rental Units)</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Parking_Space_Price_Inclusion_Sales__c</fullName>
        <label>Parking Space Price Inclusion-OWN ONLY</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Included in Sales Price</fullName>
                </value>
                <value>
                    <fullName>Sold/Leased Separately</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Price_With_Parking__c</fullName>
        <label>Price With Parking</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price_Without_Parking__c</fullName>
        <label>Price Without Parking</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Name__c</fullName>
        <description>Name of a Property within a Development</description>
        <inlineHelpText>Name of a Property within a Development</inlineHelpText>
        <label>Property Name</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Required_Deposit_Amount__c</fullName>
        <label>Required Deposit Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Square_Footage__c</fullName>
        <label>Unit Square Footage</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Bathrooms__c</fullName>
        <label># of Bathrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Bedrooms__c</fullName>
        <label># of Bedrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <recordTypes>
        <fullName>Unit</fullName>
        <active>true</active>
        <description>Unit level details for a property (Apt. #, Sq. Ft., # of Bedrooms, etc.)</description>
        <label>Unit</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_MOHCDViewListingCC.cls
/*
* @auther : Cloud Sherpas Inc.
* @date : 09/23/2014
* @description : An apex page controller for mohcdViewListing VF Page.
*/  
public class CS_MOHCDViewListingCC {
    
    String radio = '0';        //for radiobuttons
    public List<Properties__c> lUnits {get; set;}         //For List of Units
    public Properties__c prop {get;set;}
    public Boolean isSubmitted {get;set;}

    public CS_MOHCDViewListingCC(ApexPages.StandardController controller) {
        prop = (Properties__c)controller.getRecord();
        isSubmitted = false;
        prop = [SELECT Id, Property_Name__c FROM Properties__c WHERE Id = : prop.Id];
        System.debug(' ~~ id : ' + prop.Id);
        System.debug(' ~~ parentPropName : ' + prop.Property_Name__c);
        
        lUnits = [SELECT Id, Name, Unit_Number__c, of_Bedrooms__c, of_Bathrooms__c, Unit_Square_Footage__c, Price_With_Parking__c,
            Price_Without_Parking__c, Maximum_AMI__c, Final_Monthly_HOA_Amount_Without_Parking__c, Final_Monthly_HOA_Amount_With_Parking__c,
            MLS__c, MLS_Listing_Link__c, Monthly_Rent__c, Minimum_Monthly_Household_Income_Needed__c, Required_Deposit_Amount__c, Parking_Price_for_Rental_Units__c,
            Monthly_HOA_Dues__c, Parking_Space_Price_Inclusion_Sales__c, Number_of_Parking_Spaces__c, Parent_Property_Name__c, Price__c
            FROM Properties__c WHERE RecordType.Name = : 'Unit' AND Parent_Property_Name__c = : prop.Property_Name__c];
        
        System.debug(' ~~ list size : ' + lUnits.size());
    }
    
    public PageReference checkPoint(){
        if(Userinfo.getUserType().equals('Guest')){
           PageReference pref = new PageReference('/housingprograms/mohcdLoginDirect?propid='+prop.Id);
           pref.setRedirect(true);
           return pref;
        }else{
           List<User> users = new List<User>([SELECT ContactId FROM User WHERE Id =:Userinfo.getUserId()]);
           List<Contact> contacts = [Select AccountId FROM Contact WHERE Id = :users[0].ContactId];            
           List<Housing_Application__c> hApps = new List<Housing_Application__c>([SELECT Id FROM Housing_Application__c WHERE Household_Account__c =: contacts[0].AccountId AND Application_Status__c = 'Submitted']);
            
           if(hApps.size()!=0){
               isSubmitted = true;
           }else{
               PageReference pref = new PageReference('/housingprograms/mohcdHousingApp?pid='+prop.Id);
               pref.setRedirect(true);
               return pref;       
           }  
           //PageReference pref = new PageReference('/housingprograms/mohcdHousingApp?pid='+prop.Id);
               //pref.setRedirect(true);
               //return pref;           
           return null;
        }
    }
    //for radiobuttons in popup window
    public List<SelectOption> getItems() {
        List<SelectOption> options = new List<SelectOption>(); 
        options.add(new SelectOption('0','Pre-fill my household information'));  
        options.add(new SelectOption('1','Start over with a blank Housing Application')); return options; 
    }
    
    public void closePopUp(){
        isSubmitted = false;
    }
    
    public String getRadio() {
        return radio;
    }
                    
    public void setRadio(String radio) { this.radio = radio; }
    
    public PageReference onNext(){
        try{
            if(radio=='0'){
                prefillHousingApp();
                PageReference pref = new PageReference('/housingprograms/mohcdHousingApp?pid='+prop.Id+'&copy=1');
                pref.setRedirect(true);
                return pref; 
            }else{
                clearHousingApp();
                PageReference pref = new PageReference('/housingprograms/mohcdHousingApp?pid='+prop.Id);
                pref.setRedirect(true);
                return pref; 
            }        
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }
    
    public void prefillHousingApp(){
        Contact fetchCont = SFMOHCD_DAO.getUserContDet();
        System.debug('***cont'+ fetchCont);

        Account contAccount = SFMOHCD_DAO.getUserAccount();
        System.debug('***account'+ contAccount);


        Housing_Application__c housingApp = SFMOHCD_DAO.createHousingApp(contAccount.Id, prop.Id, fetchCont.Id);
        System.debug('****housingapp'+ housingApp);
        insert housingApp;

        List<Housing_Application_Member__c> housingAppMem = SFMOHCD_DAO.createhAppMem(housingApp.Id, contAccount.Id);
        System.debug('****housingAppMem'+ housingAppMem);
        
        insert housingAppMem;

        List<Housing_Application_Asset__c> houseAppAsset = SFMOHCD_DAO.createhAppAsset(contAccount.Id, housingApp.Id);
        System.debug('****houseAppAsset'+ houseAppAsset);
        insert houseAppAsset;
        

        List<Housing_Application_Income__c> houseAppIncome = SFMOHCD_DAO.createhAppIncome(contAccount.Id, housingApp.Id);

        insert houseAppIncome;

    }
    
    public void clearHousingApp(){
        Contact fetchCont = SFMOHCD_DAO.getUserContDet();
        System.debug('***cont'+ fetchCont);

        Account contAccount = SFMOHCD_DAO.getUserAccount();
        System.debug('***account'+ contAccount);


        Housing_Application__c housingApp = SFMOHCD_DAO.createHousingApp(contAccount.Id, prop.Id, fetchCont.Id);
        System.debug('****housingapp'+ housingApp);
        insert housingApp;    
    }
  }