src/objects/Financial_Application__c.object
<CustomObject>
    <description>Financial Applications for MOHCD Homeownership Programs</description>
    <fields>
        <fullName>Copy_Existing_Info__c</fullName>
        <defaultValue>true</defaultValue>
        <inlineHelpText>Do you want to copy existing information from the Household account and application? Check to copy, uncheck to start a blank application.</inlineHelpText>
        <label>Copy Existing Information ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Development_Name__c</fullName>
        <label>Development Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.RecordTypeId</field>
                <operation>equals</operation>
                <value>Household</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <lookupFilter>
            <active>false</active>
            <filterItems>
                <field>Housing_Application__c.Household_Account__c</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Financial Applications</relationshipLabel>
        <relationshipName>Program_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <label>Property Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>of_Bathrooms__c</fullName>
        <label># of Bathrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Bedrooms__c</fullName>
        <label># of Bedrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Financial Application</label>
    <nameField>
        <displayFormat>FA-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Financial_Application_Member__c</fullName>
        <label>Financial Application Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Application_Member__c.Financial_Application__c</field>
                <operation>equals</operation>
                <valueField>$Source.Financial_Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Application_Member__c</referenceTo>
        <relationshipLabel>Financial Application Assets for this Member</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application - Member Assets</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application Asset</label>
    <nameField>
        <displayFormat>FAA-{YY}-{0}</displayFormat>
        <label>FA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Financial_Application_Member__c</fullName>
        <label>Financial Application Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Application_Member__c.Financial_Application__c</field>
                <operation>equals</operation>
                <valueField>$Source.Financial_Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Application_Member__c</referenceTo>
        <relationshipLabel>Financial Application Incomes for this Member</relationshipLabel>
        <relationshipName>Financial_Application_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application - Member Incomes</relationshipLabel>
        <relationshipName>Financial_Application_Incomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application Income</label>
    <nameField>
        <displayFormat>FAI-{YY}-{0}</displayFormat>
        <label>FA-Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application Members</relationshipLabel>
        <relationshipName>Financial_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Application Member</label>
    <nameField>
        <displayFormat>MEM-{000000}</displayFormat>
        <label>Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Development_Name__c</fullName>
        <formula>Property_of_Interest__r.Development_Name__c</formula>
        <label>Development Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Housing Applications</relationshipLabel>
        <relationshipName>Housing_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Property_Address__c</fullName>
        <formula>Property_of_Interest__r.Property_Address_Marketing__c</formula>
        <label>Property Address</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_of_Interest__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Property/Unit of Interest that is associated with this Housing Application.</description>
        <inlineHelpText>The Property/Unit of Interest that is associated with this Housing Application.</inlineHelpText>
        <label>Property of Interest</label>
        <referenceTo>Properties__c</referenceTo>
        <relationshipLabel>Housing Applications</relationshipLabel>
        <relationshipName>Housing_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>Development_Name__c</fullName>
        <label>Development Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parent_Development_Name__c</fullName>
        <formula>Parent_Development__r.Development_Name__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Parent Development Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>of_Bathrooms__c</fullName>
        <label># of Bathrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Bedrooms__c</fullName>
        <label># of Bedrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SfmohprogramsFinAppTriggerHelper.cls
public with sharing class SfmohprogramsFinAppTriggerHelper {
	
	public void populateFields(List<Financial_Application__c> finApp){

        Housing_Application__c hApp = new Housing_Application__c();
        Housing_Application__c hAppVal = new Housing_Application__c();
        Properties__c propVal = new Properties__c();

        for(Financial_Application__c fa : finApp){
            if(fa.Copy_Existing_Info__c){
                hApp.Id = fa.Housing_Application__c;                
            }
        }


        if(happ.Id != null){
             hAppVal = [SELECT Household_Account__c,
                                                     Property_of_Interest__c,
                                                     Property_Address__c,
                                                     Development_Name__c
                                                     FROM Housing_Application__c WHERE id =: hApp.Id];
            propVal = [SELECT of_Bathrooms__c,
                                            of_Bedrooms__c,
                                            Parent_Development_Name__c
                                            FROM Properties__c
                                            WHERE id = :hAppVal.Property_of_Interest__c];

        
                                             


            for(Financial_Application__c fa : finApp){
                fa.Household_Account__c = hAppVal.Household_Account__c;
                //fa.Property_Address__c = hAppVal.Property_Address__c;
                if(hAppVal.Development_Name__c == null){
                    fa.Development_Name__c = propVal.Parent_Development_Name__c;
                }else{                    
                    fa.Development_Name__c = hAppVal.Development_Name__c;
                }
                fa.of_Bathrooms__c = propVal.of_Bathrooms__c;
                fa.of_Bedrooms__c = propVal.of_Bedrooms__c;

            }
        }
    }

    public void createMemAssetIncome(List<Financial_Application__c> finApp){
        Account hHoldAccount = new Account();
        Financial_Application__c finAppId = new Financial_Application__c();

        for(Financial_Application__c fa : finApp){
            if(fa.Copy_Existing_Info__c){
                hHoldAccount.Id = fa.Household_Account__c;
                finAppId.Id = fa.Id;                
            }
        }

        if(hHoldAccount.Id !=null){
            List<Financial_Application_Member__c> finAppMem = SFMOHCD_DAO.createfinAppMem(finAppId.Id, hHoldAccount.Id);

            if(finAppMem.size() > 0 && !finAppMem.isEmpty()){
                insert finAppMem;
            }

            List<Financial_Application_Asset__c> finAppAsset = SFMOHCD_DAO.createfinAppAsset(hHoldAccount.Id, finAppId.Id);

            if(finAppAsset.size() > 0 && !finAppAsset.isEmpty()){
                insert finAppAsset;
            }

            List<Financial_Application_Income__c> finAppIncome = SFMOHCD_DAO.createfinAppIncome(hHoldAccount.Id, finAppId.Id);

            if(finAppIncome.size() > 0 && !finAppIncome.isEmpty()){
                insert finAppIncome;
            }   

        }
    }

}