src/objects/Financial_Application__c.object
<CustomObject>
    <description>Financial Applications for MOHCD Homeownership Programs</description>
    <label>Financial Application</label>
    <nameField>
        <displayFormat>FA-{YYYY}{MM}-{0}</displayFormat>
        <label>Financial Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Financial_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Financial_Application_Member__c</fullName>
        <label>Financial Application Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Financial_Application_Member__c.Financial_Application__c</field>
                <operation>equals</operation>
                <valueField>$Source.Financial_Application__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Financial_Application_Member__c</referenceTo>
        <relationshipLabel>Financial Application Assets for this Member</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application - Member Assets</relationshipLabel>
        <relationshipName>Financial_Application_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Financial Application Asset</label>
    <nameField>
        <displayFormat>FAA-{YY}-{0}</displayFormat>
        <label>FA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Financial_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Financial_Application__c</fullName>
        <label>Financial Application</label>
        <referenceTo>Financial_Application__c</referenceTo>
        <relationshipLabel>Financial Application Members</relationshipLabel>
        <relationshipName>Financial_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Financial Application Member</label>
    <nameField>
        <displayFormat>MEM-{000000}</displayFormat>
        <label>Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Financial Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprogramsFinAppAssetTriggerHandler.cls
public with sharing class SfmohprogramsFinAppAssetTriggerHandler{

    public void beforeInsert(List<Financial_Application_Asset__c> finAppAsset) {

        Financial_Application_Member__c memId = new Financial_Application_Member__c();
        
        for(Financial_Application_Asset__c finAsset : finAppAsset){
            memId.Id = finAsset.Financial_Application_Member__c;
        }

        Financial_Application_Member__c fAppId = [SELECT Financial_Application__c FROM Financial_Application_Member__c WHERE Id =:memId.Id];
        
        Financial_Application__c fApp = [SELECT Id, Name FROM Financial_Application__c WHERE Id =: fAppId.Financial_Application__c];


        for(Financial_Application_Asset__c finAsset : finAppAsset){
            finAsset.Financial_Application__c = fApp.Id;
        }

    }

}