src/objects/Flagged_Record_Set__c.object
<CustomObject>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipName>Conflict</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Rule_Name__c</fullName>
        <description>This is auto-populated from the trigger Rule_Name__c</description>
        <label>Rule Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Flagged Record Set</label>
    <nameField>
        <displayFormat>FRS-{0000000000}</displayFormat>
        <label>Flagged Record Set</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flagged Record Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Listings</relationshipLabel>
        <relationshipName>Listings</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Lottery_Status__c</fullName>
        <label>Lottery Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Yet Run</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lottery Complete</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HOP_ApplicationReviewController.cls
// *****************************************************************************
// CLASS: HOP_ApplicationReviewController
// *****************************************************************************
//
// Author: Vertiba/Andu Andrei
// Date: 07/16
// Description: Controller class for the HOP_ApplicationReview page.
//
// *****************************************************************************

public without sharing class HOP_ApplicationReviewController extends HOP_ControllerBase {

	// The Flagged Record Set record that will be used on the page
	public Flagged_Record_Set__c flaggedRecordSet {get; set;}

	// Variable that indicates whether any ApexPages Messages (errors) have been generated.
    public Boolean hasErrors {get; set;}

    // Most HOP pages support a retUrl parameter that enables "Back" navigation to the previous page.
	public String retUrl {get; set;}

    // Helper method that queries a Flagged_Record_Set__c record by its Id
	private static Flagged_Record_Set__c getFlaggedRecordSetById(String paramFlaggedRecordSetId) {
		List<Flagged_Record_Set__c> flaggedRecordSets = [
			SELECT Id, Listing__r.Name, Listing__r.Account__c, Listing__r.Lottery_Status__c, Rule_Name__c
			FROM Flagged_Record_Set__c
			WHERE Id = :paramFlaggedRecordSetId
		];

		if (flaggedRecordSets.size() == 0) {
			return null;
		} else {
			return flaggedRecordSets[0];
		}
	}

	public HOP_ApplicationReviewController() {
		super();
		hasErrors = false;
		retUrl = ApexPages.currentPage().getParameters().get('retUrl');

		// The page expects a Flagged Record Set Id parameter. If not provided, display an error.
        String paramFlaggedRecordSetId = ApexPages.currentPage().getParameters().get('id');
		if (String.isBlank(paramFlaggedRecordSetId)) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, HOP_Constants.ERROR_ID_NOT_PROVIDED));
            hasErrors = true;
            return;
		}

		// Check to see if a Flagged Record Set with the provided Id exists. If not, display an error.
		flaggedRecordSet = getFlaggedRecordSetById(paramFlaggedRecordSetId);
		if (flaggedRecordSet == null) {
			ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, HOP_Constants.ERROR_FLAGGED_RECORD_SET_NOT_FOUND));
			hasErrors = true;
			return;
		}

		// Community users cannot access Flagged Record Sets associated with an Account other than their own.
        if (myUser.Profile.UserLicense.Name == HOP_Constants.COMMUNITY_LICENSE_NAME &&
        	flaggedRecordSet.Listing__r.Account__c != myUser.Contact.AccountId) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, HOP_Constants.ERROR_NO_ACCESS));
            hasErrors = true;
            return;
        }
	}

}