src/objects/Flagged_Application__c.object
<CustomObject>
    <fields>
        <fullName>DuplicateRecordItem__c</fullName>
        <externalId>true</externalId>
        <label>DuplicateRecordItem</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Flagged_Record_Set__c</fullName>
        <label>Flagged Record Set</label>
        <referenceTo>Flagged_Record_Set__c</referenceTo>
        <relationshipLabel>Flagged Applications</relationshipLabel>
        <relationshipName>Flagged_Applications</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Flagged Application</label>
    <nameField>
        <displayFormat>FLAG-{000000}</displayFormat>
        <label>Flagged Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flagged Applications</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Flagged_Record_Set__c.object
<CustomObject>
    <label>Flagged Record Set</label>
    <nameField>
        <displayFormat>FRS-{0000000000}</displayFormat>
        <label>Flagged Record Set</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flagged Record Set</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/deleteFlaggedRecordSet.cls
global class deleteFlaggedRecordSet implements Database.Batchable<sObject>{
    String query;
    List<Id> idList;
	
    global deleteFlaggedRecordSet(List<Id> idList) {
    	System.debug(idList);
        this.idList = idList;
    	query = 'Select id from Flagged_Application__c Where DuplicateRecordItem__c IN :idList';
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
    	return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<Flagged_Record_Set__c> scope) { 
       Database.delete(scope);
		System.debug(scope); 

		
	}
	
	global void finish(Database.BatchableContext BC) {
        System.debug('Completed');
	}
}