src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Development_Name__c</fullName>
        <formula>Property_of_Interest__r.Development_Name__c</formula>
        <label>Development Name</label>
        <type>Text</type>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type/ Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tax Return and W-2 Forms</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Income Tax Affidavit</fullName>
                </value>
                <value>
                    <fullName>Bank Statement</fullName>
                </value>
                <value>
                    <fullName>Retirement Account Statement</fullName>
                </value>
                <value>
                    <fullName>Verification of Employment Form</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Pay stub</fullName>
                </value>
                <value>
                    <fullName>Profit/Loss Statement</fullName>
                </value>
                <value>
                    <fullName>Schedule C</fullName>
                </value>
                <value>
                    <fullName>Self-employed Affidavit</fullName>
                </value>
                <value>
                    <fullName>Unemployed Affidavit</fullName>
                </value>
                <value>
                    <fullName>Gift Letter</fullName>
                </value>
                <value>
                    <fullName>Loan Pre-approval Letter</fullName>
                </value>
                <value>
                    <fullName>First Time Homebuyer Certificate</fullName>
                </value>
                <value>
                    <fullName>HomeownershipSF Consent Form</fullName>
                </value>
                <value>
                    <fullName>Lender’s Certificate of Borrower’s Eligibility</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Related To</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Attachments</relationshipLabel>
        <relationshipName>Housing_Application_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Housing Application Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing Application Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>Development_Name__c</fullName>
        <label>Development Name</label>
        <length>128</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Marketing_Company_Agent_Name__c</fullName>
        <label>Marketing Company Agent Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupancy_Type__c</fullName>
        <label>Occupancy Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ownership</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <label>Phone Number</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Property_Address_Marketing__c</fullName>
        <formula>Property_Address_Street_Number__c &amp; &quot; &quot; &amp; Property_Address_Street_Name__c &amp; &quot; &quot; &amp; TEXT(Property_Address_Street_Type__c) &amp; &quot; &quot; &amp; Apt_Unit__c &amp; BR() 
&amp; Property_Address_City__c &amp; &quot;, &quot; &amp; Property_Address_State__c &amp; &quot; &quot; &amp; Property_Address_Zip_Code__c</formula>
        <label>Property Address Marketing</label>
        <type>Text</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_MOHCDAttachFilesCC.cls
/**
 * @author:      Sumit Shingavi
 * @date:        07/11/2014
 * @description: Apex class for mohAttachFiles VF Page
 * @history:     06/10/2015 - Heidi Tang - Edited
*/ 
public with sharing class CS_MOHCDAttachFilesCC {
    
    //Public Variables
    public Properties__c propInstance {get; set;} 
    public String haId {get; set;}
    public String pId {get; set;}    
    public transient Blob fileAttachmentBody {get; set;}    
    public transient String fileAttachmentName {get; set;}
    public transient String fileAttachmentContentType {get; set;}
    public transient String fileAttachmentDescription {get; set;}
    public List<String> attachmentFileNames {get; set;}
    
    //Constructor
    public CS_MOHCDAttachfilesCC() {
        haId  = '';
        pId = '';
        
        haId = System.currentPageReference().getParameters().get('haId');
        pId = System.currentPageReference().getParameters().get('pId'); 
        propInstance = new Properties__c(); 
        if(!String.isBlank(pId)) {
            propInstance = [SELECT Id, Name, Development_Name__c, Property_Address_Marketing__c, 
                Marketing_Company_Agent_Name__c, Phone_Number__c, Email__c, Occupancy_Type__c 
                FROM Properties__c WHERE Id =: pId LIMIT 1];
        }
        fileAttachmentBody = null;
        fileAttachmentDescription = '';
        attachmentFileNames = new List<String>();        
    }
    
    /*
    * @auther : Cloud Sherpas Inc.
    * @date : 07/11/2014
    * @description : Apex method for adding attachments to allAttachments List variable
    * @parameters : Nothing
    * @returns : PageReference 
    */  
    Integer totalSize = 0;
    public PageReference addAttachment() {
    
        try{  
            
            if(!String.isBlank(fileAttachmentName)) {
                
                if(String.isBlank(fileAttachmentDescription)) {
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, Label.ERROR_ATTACHMENT_TYPE));
                    return null;
                }
                attachmentFileNames.add(fileAttachmentName);                
                Attachment myAttachment= new Attachment();
                myAttachment.Name = fileAttachmentName +'-'+ fileAttachmentDescription;
                myAttachment.Body = fileAttachmentBody;
                myAttachment.ContentType = fileAttachmentContentType;                         
                myAttachment.ParentId = haId;                
                myAttachment.Description = fileAttachmentDescription;
                insert myAttachment;
                
                Housing_Application_Attachment__c haAttachment = new Housing_Application_Attachment__c();
                haAttachment.Type__c = myAttachment.Id;
                haAttachment.Name = fileAttachmentName;
                haAttachment.Housing_Application__c = haId;
                haAttachment.Document_Type__c = fileAttachmentDescription; 
                 
                insert haAttachment;
                             
                ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, Label.SUCCESS_ATTACHMENT));
                
                myAttachment = new Attachment();                                
                fileAttachmentBody = null;
                fileAttachmentName = '';
                fileAttachmentContentType = '';                
                fileAttachmentDescription = '';
            }        
        }catch(Exception e){
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, e.getMessage()));
        }
        return null;
    }       
    
    /*
    * @auther : Cloud Sherpas Inc.
    * @date : 07/11/2014
    * @description : Apex method for adding attachments to Housing Application
    * @parameters : Nothing
    * @returns : PageReference 
    */
    public PageReference done() {
        PageReference pref = Page.mohcdHousingApp;
        pref.getParameters().put('pid', pid);
        pref.getParameters().put('t', '6');
        pref.setRedirect(true);
        return pref;
    }
    
    public List<SelectOption> getDocumentTypes() {
        List<SelectOption> options = new List<SelectOption>();
        if(propInstance.Occupancy_Type__c == StringConstants.PROP_RENTAL) {
            options.add(new SelectOption('',Label.SELECT_OPTION));
            options.add(new SelectOption(Label.DOC_TYPE_LIVE_PROOF,Label.DOC_TYPE_LIVE_PROOF_VALUE));
        } else
        if(propInstance.Occupancy_Type__c == StringConstants.PROP_OWNERSHIP) {
            options.add(new SelectOption('',Label.SELECT_OPTION));
            options.add(new SelectOption(Label.DOC_TYPE_TAX_RETURN,Label.DOC_TYPE_TAX_RETURN));
            options.add(new SelectOption(Label.DOC_TYPE_INCOME_TAX,Label.DOC_TYPE_INCOME_TAX));
            options.add(new SelectOption(Label.DOC_TYPE_BANK_STATEMENT,Label.DOC_TYPE_BANK_STATEMENT));
            options.add(new SelectOption(Label.DOC_TYPE_RETIREMENT,Label.DOC_TYPE_RETIREMENT));
            options.add(new SelectOption(Label.DOC_TYPE_VERIFICATION,Label.DOC_TYPE_VERIFICATION));
            options.add(new SelectOption(Label.DOC_TYPE_EMPLOYMENT_OFFER,Label.DOC_TYPE_EMPLOYMENT_OFFER));
            options.add(new SelectOption(Label.DOC_TYPE_PAY,Label.DOC_TYPE_PAY));
            options.add(new SelectOption(Label.DOC_TYPE_PROFIT,Label.DOC_TYPE_PROFIT));
            options.add(new SelectOption(Label.DOC_TYPE_SCHEDULE,Label.DOC_TYPE_SCHEDULE));
            options.add(new SelectOption(Label.DOC_TYPE_SELF_EMP,Label.DOC_TYPE_SELF_EMP));
            options.add(new SelectOption(Label.DOC_TYPE_UNEMPLOYED,Label.DOC_TYPE_UNEMPLOYED));
            options.add(new SelectOption(Label.DOC_TYPE_GIFT_LETTER,Label.DOC_TYPE_GIFT_LETTER));
            options.add(new SelectOption(Label.DOC_TYPE_LOAN,Label.DOC_TYPE_LOAN));
            options.add(new SelectOption(Label.DOC_TYPE_HOMEBUYER,Label.DOC_TYPE_HOMEBUYER));
            options.add(new SelectOption(Label.DOC_TYPE_CONSENT,Label.DOC_TYPE_CONSENT));
            options.add(new SelectOption(Label.DOC_TYPE_LENDER,Label.DOC_TYPE_LENDER));
            options.add(new SelectOption(Label.DOC_TYPE_OTHER,Label.DOC_TYPE_OTHER)); 
        }   
        return options;
    }

}