src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Housing Applications</relationshipLabel>
        <relationshipName>Housing_Applications</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Applicant_Role__c</fullName>
        <inlineHelpText>All Primary and Co-Applicants are non-dependent adults (18 yrs +) who will appear on Title. 

Dependent Adults must be dependents on an Applicant’s tax return. They are included here because their income/assets are counted.

Only one Primary allowed.</inlineHelpText>
        <label>Applicant Role</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Primary Applicant</fullName>
                </value>
                <value>
                    <fullName>Co-Applicant</fullName>
                </value>
                <value>
                    <fullName>Dependent Adult</fullName>
                </value>
                <value>
                    <fullName>Dependent Minor</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Apt_Unit__c</fullName>
        <label>Apt./Unit #</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cell_Phone__c</fullName>
        <label>Cell Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Home_Phone__c</fullName>
        <label>Home Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Members</relationshipLabel>
        <relationshipName>Housing_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Relationship_to_Head_of_Household__c</fullName>
        <label>Relationship to Head of Household</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Self</fullName>
                </value>
                <value>
                    <fullName>Spouse</fullName>
                </value>
                <value>
                    <fullName>Registered Domestic Partner</fullName>
                </value>
                <value>
                    <fullName>Daughter</fullName>
                </value>
                <value>
                    <fullName>Son</fullName>
                </value>
                <value>
                    <fullName>Step Daughter</fullName>
                </value>
                <value>
                    <fullName>Step Son</fullName>
                </value>
                <value>
                    <fullName>Sister</fullName>
                </value>
                <value>
                    <fullName>Brother</fullName>
                </value>
                <value>
                    <fullName>Step Sister</fullName>
                </value>
                <value>
                    <fullName>Step Brother</fullName>
                </value>
                <value>
                    <fullName>Cousin</fullName>
                </value>
                <value>
                    <fullName>Aunt</fullName>
                </value>
                <value>
                    <fullName>Uncle</fullName>
                </value>
                <value>
                    <fullName>Nephew</fullName>
                </value>
                <value>
                    <fullName>Niece</fullName>
                </value>
                <value>
                    <fullName>Grandparent</fullName>
                </value>
                <value>
                    <fullName>Great Grandparent</fullName>
                </value>
                <value>
                    <fullName>Brother-In-Law</fullName>
                </value>
                <value>
                    <fullName>Daughter-In-Law</fullName>
                </value>
                <value>
                    <fullName>Father-In-Law</fullName>
                </value>
                <value>
                    <fullName>Mother-In-Law</fullName>
                </value>
                <value>
                    <fullName>Sister-In-Law</fullName>
                </value>
                <value>
                    <fullName>Son-In-Law</fullName>
                </value>
                <value>
                    <fullName>Friend</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Number__c</fullName>
        <label>Street Number</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_Type__c</fullName>
        <label>Street Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>[Not Applicable]</fullName>
                </value>
                <value>
                    <fullName>Alley</fullName>
                </value>
                <value>
                    <fullName>Avenue</fullName>
                </value>
                <value>
                    <fullName>Boulevard</fullName>
                </value>
                <value>
                    <fullName>Circle</fullName>
                </value>
                <value>
                    <fullName>Court</fullName>
                </value>
                <value>
                    <fullName>Drive</fullName>
                </value>
                <value>
                    <fullName>Highway</fullName>
                </value>
                <value>
                    <fullName>Lane</fullName>
                </value>
                <value>
                    <fullName>Loop</fullName>
                </value>
                <value>
                    <fullName>Park</fullName>
                </value>
                <value>
                    <fullName>Place</fullName>
                </value>
                <value>
                    <fullName>Plaza</fullName>
                </value>
                <value>
                    <fullName>Road</fullName>
                </value>
                <value>
                    <fullName>Row</fullName>
                </value>
                <value>
                    <fullName>Square</fullName>
                </value>
                <value>
                    <fullName>Street</fullName>
                </value>
                <value>
                    <fullName>Terrace</fullName>
                </value>
                <value>
                    <fullName>Walk</fullName>
                </value>
                <value>
                    <fullName>Way</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Work_Phone__c</fullName>
        <label>Work Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprogramsHousingAppMemberTriggerHand.cls
/*****************************************************
 @author : Kingsley Tumaneng
 @date   : April 28, 2015
 @description : Class for Housing Application Member 
                Trigger
******************************************************/

public class SfmohprogramsHousingAppMemberTriggerHand{
    
    public void afterInsert(List<Housing_Application_Member__c> hoamList){
        List<Housing_Application_Member__c> housingMemList = new List<Housing_Application_Member__c>();
        Set<Id> setId = new Set<Id>();
        String homePhone;
        String cellPhone;
        String workPhone;
        String accEmail;
        String streetNum;
        String streetType;
        String streetName;
        String aptUnit;
        String city;
        String state;
        String zip;
        Id housingMemberId;
        
        for(Housing_Application_Member__c hoam : hoamList){
            setId.add(hoam.Housing_Application__c);
            housingMemberId = hoam.Id;
            
            system.debug('***housingMemberId = ' + hoam.Id);
        }
        
        for(Housing_Application__c housingApp : [SELECT Id, Household_Account__r.Phone, Household_Account__r.Mobile_Phone__c , 
                                                 Household_Account__r.Work_Phone__c, Household_Account__r.Email__c,
                                                 Household_Account__r.Street_Number__c , Household_Account__r.Street_Name__c ,
                                                 Household_Account__r.Street_Type__c , Household_Account__r.Apt_Unit__c ,
                                                 Household_Account__r.City__c, Household_Account__r.State__c ,
                                                 Household_Account__r.Zip_Code__c FROM Housing_Application__c WHERE Id IN : setId]){
                                                 
            homePhone = housingApp.Household_Account__r.Phone;
            cellPhone = housingApp.Household_Account__r.Mobile_Phone__c;
            workPhone = housingApp.Household_Account__r.Work_Phone__c;
            accEmail = housingApp.Household_Account__r.Email__c;
            streetNum = housingApp.Household_Account__r.Street_Number__c;
            streetType = housingApp.Household_Account__r.Street_Type__c;
            streetName = housingApp.Household_Account__r.Street_Name__c;
            aptUnit = housingApp.Household_Account__r.Apt_Unit__c;
            city = housingApp.Household_Account__r.City__c;
            state = housingApp.Household_Account__r.State__c;
            zip = housingApp.Household_Account__r.Zip_Code__c;
                                       
            system.debug('***Email = ' + housingApp.Household_Account__r.Email__c);
            system.debug('***Phone = ' + housingApp.Household_Account__r.Phone);
            system.debug('***Work Phone = ' + housingApp.Household_Account__r.Work_Phone__c);
            system.debug('***Mobile Phone = ' + housingApp.Household_Account__r.Mobile_Phone__c);
        }
        
        for(Housing_Application_Member__c hoam : [SELECT Id, Email_Address__c, Applicant_Role__c, Relationship_to_Head_of_Household__c, Cell_Phone__c, Home_Phone__c, Work_Phone__c,
                                                  Street_Name__c, Street_Number__c, Street_Type__c, Zip_Code__c, Apt_Unit__c, City__c, State__c 
                                                  FROM Housing_Application_Member__c WHERE Id =: housingMemberId]){
            if(hoam.Relationship_to_Head_of_Household__c == 'Self'){
                hoam.Applicant_Role__c = 'Primary Applicant';
                hoam.Home_Phone__c = homePhone;
                hoam.Work_Phone__c = workPhone;
                hoam.Cell_Phone__c = cellPhone;
                hoam.Email_Address__c = accEmail;
                hoam.Street_Name__c = streetName;
                hoam.Street_Number__c = streetNum;
                hoam.Street_Type__c = streetType;
                hoam.Zip_Code__c = zip;
                hoam.Apt_Unit__c = aptUnit;
                hoam.City__c = city;
                hoam.State__c = state;
                housingMemList.add(hoam);
                system.debug('***Home Phone = ' + hoam.Home_Phone__c);
                system.debug('***Cell Phone = ' + hoam.Cell_Phone__c);
                system.debug('***Work Phone = ' + hoam.Work_Phone__c);
            }
        }
        
        if(housingMemList.size() > 0){
            update housingMemList;
        }
    }
}