src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Head_of_Household__c</fullName>
        <formula>ISPICKVAL(Relationship_to_Head_of_Household__c,&quot;Self&quot;)</formula>
        <label>Head of Household</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Members</relationshipLabel>
        <relationshipName>Housing_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Member_Full_Name__c</fullName>
        <formula>TEXT(Salutation__c) &amp; &quot; &quot; &amp; First_Name__c &amp; &quot; &quot; &amp; Middle_Name__c &amp; &quot; &quot; &amp; Last_Name__c  &amp; &quot; &quot; &amp; TEXT(Suffix__c)</formula>
        <label>Member Full Name</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Occupation__c</fullName>
        <label>Occupation</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/relatedListPrototypeController.cls
public without sharing class relatedListPrototypeController 
{
    public List<Housing_Application_Member__c> housingAppMember;
    private Housing_Application__c housingApp;
    
    public relatedListPrototypeController(ApexPages.StandardController controller)
    {
    	this.housingApp = (Housing_Application__c)controller.getRecord();    	    
    }

    public List<Housing_Application_Member__c> gethousingAppMember()
    {    	
    	housingAppMember = [SELECT id, Housing_Application__c, Name, Member_Full_Name__c, Head_of_Household__c, Occupation__c FROM Housing_Application_Member__c WHERE Housing_Application__c = :housingApp.id];    	
system.debug('===MEMBER = ' + housingAppMember);    	
    	if(housingAppMember.size() != 0 )
    	{
    		return housingAppMember;
    	}else{
    		return null;
    	}    	    
    }
}