src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Attachment__c.object
<CustomObject>
    <fields>
        <fullName>Document_Type__c</fullName>
        <label>Document Type/ Purpose</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Tax Return and W-2 Forms</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Income Tax Affidavit</fullName>
                </value>
                <value>
                    <fullName>Bank Statement</fullName>
                </value>
                <value>
                    <fullName>Retirement Account Statement</fullName>
                </value>
                <value>
                    <fullName>Verification of Employment Form</fullName>
                </value>
                <value>
                    <fullName>Employment Offer Letter</fullName>
                </value>
                <value>
                    <fullName>Pay stub</fullName>
                </value>
                <value>
                    <fullName>Profit/Loss Statement</fullName>
                </value>
                <value>
                    <fullName>Schedule C</fullName>
                </value>
                <value>
                    <fullName>Self-employed Affidavit</fullName>
                </value>
                <value>
                    <fullName>Unemployed Affidavit</fullName>
                </value>
                <value>
                    <fullName>Gift Letter</fullName>
                </value>
                <value>
                    <fullName>Loan Pre-approval Letter</fullName>
                </value>
                <value>
                    <fullName>First Time Homebuyer Certificate</fullName>
                </value>
                <value>
                    <fullName>HomeownershipSF Consent Form</fullName>
                </value>
                <value>
                    <fullName>Lender’s Certificate of Borrower’s Eligibility</fullName>
                </value>
                <value>
                    <fullName>Other</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Related To</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Attachments</relationshipLabel>
        <relationshipName>Housing_Application_Attachments</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Housing Application Attachment</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Housing Application Attachments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_MOHCDHousingAttachments.cls
public class CS_MOHCDHousingAttachments {
    public Blob fileBody { get; set; }
    public String fileName { get; set; }
    public String financialId {get;set;}
    public Housing_Application_Attachment__c finAttachment {get;set;}
    public Housing_Application__c finApp {get;set;}
    
    public CS_MOHCDHousingAttachments(ApexPages.StandardController controller) {
        finApp = new Housing_Application__c();
        
        Housing_Application_Attachment__c attachedFinApp = (Housing_Application_Attachment__c) controller.getRecord();
        
        financialId = attachedFinApp.Housing_Application__c;
         
        if(financialId != null){
            finApp  = [SELECT Id, Name FROM Housing_Application__c WHERE Id = :financialId];
        }   
            
        finAttachment = new Housing_Application_Attachment__c();
    }
    
    public PageReference doCancel(){
        PageReference pageRef = new PageReference('/'+finApp.Id);
        pageRef.setRedirect(true);
        
        return pageRef;
    }
    
    public PageReference doSave(){
        if(fileBody == null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please provide a File.'));
            return null;            
        }else if(finAttachment.Document_Type__c == null){
            ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Please provide a document type.'));
            return null;
        }else{
            finAttachment.Name = this.fileName;
            finAttachment.Housing_Application__c = finApp.Id;
            
            Database.SaveResult result = Database.insert(finAttachment);
            
            if(result == null || !result.isSuccess()){
                ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Could not save attachment.'));
                return null;
            }else{
                Attachment attachment = new Attachment();
                attachment.Body = this.fileBody;
                attachment.Name = this.fileName;
                attachment.ParentId = finApp.Id;
                attachment.Description = finAttachment.Document_Type__c;
                
                Database.SaveResult attachResult = Database.insert(attachment);
                
                if(result == null || !result.isSuccess()){
                    ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR,'Could not save attachment.'));
                    return null;
                }else{
                    fileBody = Blob.valueOf('');
                    
                    finAttachment = [SELECT Id FROM Housing_Application_Attachment__c WHERE Id = :result.getId()];
                    finAttachment.Type__c = attachResult.getId();
                    
                    update finAttachment;
                    
                    PageReference pageRef = new PageReference('/'+finApp.Id);
                    pageRef.setRedirect(true);
                    return pageRef;
                }
            }
        }    
    }
}