src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Housing_Application_Member__c</fullName>
        <label>Housing Application Member</label>
        <referenceTo>Housing_Application_Member__c</referenceTo>
        <relationshipLabel>Housing Application Assets for this Member</relationshipLabel>
        <relationshipName>Housing_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application - Member Assets</relationshipLabel>
        <relationshipName>Housing_Application_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application Asset</label>
    <nameField>
        <displayFormat>HAA-{YY}-{0}</displayFormat>
        <label>HA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Members</relationshipLabel>
        <relationshipName>Housing_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprogramsHousingAppAssetTriggerHand.cls
public with sharing class SfmohprogramsHousingAppAssetTriggerHand{

    public void beforeInsert(List<Housing_Application_Asset__c> pHappAsset) {

        Housing_Application_Member__c memId = new Housing_Application_Member__c();
        
        for(Housing_Application_Asset__c pha : pHappAsset){
            memId.Id = pha.Housing_Application_Member__c;
        }

        Housing_Application_Member__c hAppId = [SELECT Housing_Application__c FROM Housing_Application_Member__c WHERE Id =:memId.Id];
        
        Housing_Application__c hApp = [SELECT Id, Name FROM Housing_Application__c WHERE Id =: hAppId.Housing_Application__c];


        for(Housing_Application_Asset__c pha : pHappAsset){
            pha.Housing_Application__c = hApp.Id;
        }

    }

}