src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Members</relationshipLabel>
        <relationshipName>Housing_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SfmohprogramsSelectedPropCont.cls
public with sharing class SfmohprogramsSelectedPropCont {

    private final Properties__c mysObject;
    public Properties__c selectedProperty {get; set;}
    // The extension constructor initializes the private member
    // variable mysObject by using the getRecord method from the standard
    // controller.
    public SfmohprogramsSelectedPropCont(ApexPages.StandardController stdController) {
        this.mysObject = (Properties__c)stdController.getRecord();
    }

    public PageReference applyProperty(){
        /*System.debug('***user**'+UserInfo.getName());

        Contact fetchCont = SFMOHCD_DAO.getUserContDet();
        Account contAccount = SFMOHCD_DAO.getUserAccount();

        Housing_Application__c housingApp = SFMOHCD_DAO.createHousingApp(contAccount.Id, mysObject.Id, fetchCont.Id);
        
        insert housingApp;

        List<Housing_Application_Member__c> housingAppMem = SFMOHCD_DAO.createhAppMem(housingApp.Id, contAccount.Id);
        
        insert housingAppMem;

        List<> housingAppAsset = SFMOHCD_DAO.createhAppAsset(String hAppMemId, String accId)
        
        if(UserInfo.getName() != 'Housing Programs Site Guest User'){
            PageReference page = new PageReference('/housingprograms/home/home.jsp?id='+ mysObject.id); 

            page.setRedirect(true);
            return page;
        }
       
        */
        


        return new PageReference('/housingprograms/login?id='+ mysObject.id);
    }
    

}