src/objects/Housing_Application_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Housing_Application_Member__c</fullName>
        <label>Housing Application Member</label>
        <referenceTo>Housing_Application_Member__c</referenceTo>
        <relationshipLabel>Housing Application Assets for this Member</relationshipLabel>
        <relationshipName>Housing_Application_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Application Asset</label>
    <nameField>
        <displayFormat>HAA-{YY}-{0}</displayFormat>
        <label>HA-Asset Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Housing_Application_Member__c</fullName>
        <label>Housing Application Member</label>
        <referenceTo>Housing_Application_Member__c</referenceTo>
        <relationshipLabel>Housing Application Incomes for this Member</relationshipLabel>
        <relationshipName>Housing_Application_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Application Income</label>
    <nameField>
        <displayFormat>HAI-{YY}-{0}</displayFormat>
        <label>HA-Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/CS_MOHCDHousingAppCCContainer.cls
/*
* @author : Cloud Sherpas Inc.
* @date : 09/17/2014
* @description : Apex class for CS_MOHCDHousingAppCC container
*/ 
public class CS_MOHCDHousingAppCCContainer{
    public Housing_Application_Member__c memberInstance {get; set;}
    public Housing_Application_Income__c memberIncomeInstance {get; set;}
    public Housing_Application_Asset__c memberAssetInstance {get; set;}
    
    public String errorMessage {get; set;}
    public Boolean error {get; set;}

    public CS_MOHCDHousingAppCCContainer(){
        memberIncomeInstance = new Housing_Application_Income__c();
    }
}