src/objects/Housing_Application__c.object
<CustomObject>
    <description>Housing Application Records</description>
    <label>Housing Application</label>
    <nameField>
        <displayFormat>HA-{YYYY}{MM}-{0}</displayFormat>
        <label>Housing Application Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Applications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Housing_Application_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Housing_Application_Member__c</fullName>
        <label>Housing Application Member</label>
        <referenceTo>Housing_Application_Member__c</referenceTo>
        <relationshipLabel>Housing Application Incomes for this Member</relationshipLabel>
        <relationshipName>Housing_Application_Incomes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application - Member Incomes</relationshipLabel>
        <relationshipName>Housing_Application_Incomes</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Housing Application Income</label>
    <nameField>
        <displayFormat>HAI-{YY}-{0}</displayFormat>
        <label>HA-Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Housing_Application_Member__c.object
<CustomObject>
    <description>Object to store member level details for entities such as Households, Lending Companies, Property Management Companies.</description>
    <fields>
        <fullName>Housing_Application__c</fullName>
        <label>Housing Application</label>
        <referenceTo>Housing_Application__c</referenceTo>
        <relationshipLabel>Housing Application Members</relationshipLabel>
        <relationshipName>Housing_Application_Members1</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Housing Application Member</label>
    <nameField>
        <displayFormat>HA-MEM-{000000}</displayFormat>
        <label>HA-Member Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Housing Application Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprogramsHousingAppIncomeTriggerHand.cls
public with sharing class SfmohprogramsHousingAppIncomeTriggerHand {
	
    public void beforeInsert(List<Housing_Application_Income__c> pHappIncome){
        Housing_Application_Member__c memId = new Housing_Application_Member__c();
        
        for(Housing_Application_Income__c phi : pHappIncome){
            memId.Id = phi.Housing_Application_Member__c;
        }

        Housing_Application_Member__c hAppId = [SELECT Housing_Application__c FROM Housing_Application_Member__c WHERE Id =:memId.Id];
        
        Housing_Application__c hApp = [SELECT Id, Name FROM Housing_Application__c WHERE Id =: hAppId.Housing_Application__c];


        for(Housing_Application_Income__c phi : pHappIncome){
            phi.Housing_Application__c = hApp.Id;
        }
        
    }
    
}