src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>Description of the Listing</description>
        <inlineHelpText>Description of the Listing</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pricing Request Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Marketing Plan Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lottery_Member__c.object
<CustomObject>
    <description>Lotttery Members. Will ultimately be a join of contacts and listings but initially it will just be a child of listings with information about the lottery results.</description>
    <fields>
        <fullName>Listing__c</fullName>
        <description>Listing which the lottery member is in.</description>
        <inlineHelpText>Listing which the lottery member is in.</inlineHelpText>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Lottery Members</relationshipLabel>
        <relationshipName>Lottery_Members</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Lottery_Number__c</fullName>
        <description>Lottery Number for the Specific Lottery Member.</description>
        <inlineHelpText>Lottery Number for the Specific Lottery Member.</inlineHelpText>
        <label>Lottery Number</label>
        <precision>8</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Rank__c</fullName>
        <description>Rank of the Lottery Member in the Lottery Results</description>
        <inlineHelpText>Rank of the Lottery Member in the Lottery Results</inlineHelpText>
        <label>Rank</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>Status of the Lottery Member for the given Lottery</description>
        <inlineHelpText>Status of the Lottery Member for the given Lottery</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Waiting on Lottery</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Winner</fullName>
                </value>
                <value>
                    <fullName>Not Selected</fullName>
                </value>
                <value>
                    <fullName>Not Eligible</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Lottery Member</label>
    <nameField>
        <displayFormat>LMN-{0000000}</displayFormat>
        <label>Lottery Member Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Lottery Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Enter the description of this preference</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of this preference</description>
        <inlineHelpText>Enter the current status of this preference</inlineHelpText>
        <label>XStatus</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Old</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ListingLotteryService.cls
global class ListingLotteryService {
    
    
     private static final String LOTTERY_PREFERENCE_QUERY = 'SELECT Id, Name, Description__c FROM Lottery_Preference__c ';
     private static final String LOTTERY_MEMBER_QUERY = 'SELECT Lottery_Number__c, Rank__c, Listing__c, Status__c FROM Lottery_Member__c where Status__c = \'Winner\'';  
     
    
    
    //*************************************
    // Lottery Preference
    //*************************************
    
    global static List<Lottery_Preference__c> getLotteryPreferenceByID(Id lpid){
    	List<Lottery_Preference__c> lps = new List<Lottery_Preference__c>();
    	string lquery = ListingLotteryService.LOTTERY_PREFERENCE_QUERY + ' WHERE Id = \'' + lpid + '\'';
    	try{
    		lps = database.query(lquery);
    	} catch (Exception e){
    		
    	}
    	return lps;
    }
    
    global static List<Lottery_Preference__c> getLotteryPreferenceByIDs(List<string> lpids){
    	List<Lottery_Preference__c> lps = new List<Lottery_Preference__c>();
    	string lquery = ListingLotteryService.LOTTERY_PREFERENCE_QUERY + ' WHERE Id in: lpids';
    	try{
    		lps = database.query(lquery);
    	} catch (Exception e){
    		
    	} 
    	return lps;
    }
    
    global static List<Lottery_Preference__c> getAllLotteryPreference(){
    	List<Lottery_Preference__c> lps = new List<Lottery_Preference__c>();
    	string lquery = ListingLotteryService.LOTTERY_PREFERENCE_QUERY;
    	try{
    		lps = database.query(lquery);
    	} catch (Exception e){
    		
    	}
    	
    	return lps;
    }
    
    //*************************************
    // Lottery Member
    //*************************************
    
    global static List<Lottery_Member__c> getLotteryMembersByListingID(Id lpid){
    	List<Lottery_Member__c> lms = new List<Lottery_Member__c>();
    	string lquery = ListingLotteryService.LOTTERY_MEMBER_QUERY + ' AND Listing__c = \'' + lpid + '\'';
    	try{
    		lms = database.query(lquery);
    	} catch (Exception e){
    		
    	}
    	return lms;
    }
    
    global static List<Lottery_Member__c> getLotteryMembersByListingIDs(List<string> lpids){
    	List<Lottery_Member__c> lms = new List<Lottery_Member__c>();
    	string lquery = ListingLotteryService.LOTTERY_MEMBER_QUERY + ' AND Listing__c in: lpids ';
    	try{
    		lms = database.query(lquery);
    	} catch (Exception e){
    		
    	}
    	return lms;
    }
    
    
}