src/objects/Listing__c.object
<CustomObject>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>BMR_Rent_Monthly__c</fullName>
        <description>Monthly Rent for BMR Unit</description>
        <inlineHelpText>Monthly Rent for BMR Unit</inlineHelpText>
        <label>Monthly rent (if $)</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>BMR_Rental_Minimum_Monthly_Income_Needed__c</fullName>
        <formula>Rent_Multiple__c  *  BMR_Rent_Monthly__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>BMR Rental Minimum Monthly Income Needed</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Number_of_Bathrooms__c</fullName>
        <label>Number of Bathrooms</label>
        <precision>3</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Other_Accessibility_Information__c</fullName>
        <description>Other Accessibility Information</description>
        <inlineHelpText>Other Accessibility Information</inlineHelpText>
        <label>Other Accessibility Information</label>
        <length>750</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Unit_Floor__c</fullName>
        <label>Unit Floor</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Square_Footage__c</fullName>
        <description>Square Footage of the Unit.</description>
        <inlineHelpText>Square Footage of the Unit.</inlineHelpText>
        <label>Unit Square Footage</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Description of units.</description>
        <inlineHelpText>Description of units.</inlineHelpText>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SRO</fullName>
                </value>
                <value>
                    <fullName>Studio</fullName>
                </value>
                <value>
                    <fullName>Large Studio</fullName>
                </value>
                <value>
                    <fullName>1 BR</fullName>
                </value>
                <value>
                    <fullName>2 BR</fullName>
                </value>
                <value>
                    <fullName>3 BR</fullName>
                </value>
                <value>
                    <fullName>4 BR</fullName>
                </value>
                <value>
                    <fullName>5 BR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>UID-{0000000}</displayFormat>
        <label>Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListingUnitApi.cls
//services/apexrest/Listing/Units
@RestResource(urlMapping='/Listing/Units/*')
global with sharing class ListingUnitApi {


    public class InvalidParamsException extends Exception {}
    
    public class NoRecordMatchException extends Exception {}

    @HttpGet
    global static List<Unit__C> doGet () {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        List<String> tokens =  req.requestURI.split('/');
       
        if (tokens.size()>3) {
        	return ListingService.getUnitsByListingID(tokens[3]);
        }
        if (req.params.containsKey('id')) {
            return ListingService.getUnitsByListingID(req.params.get('id'));
        }
       
     	throw new NoRecordMatchException();
       
    }
   
    
    /*
    global static List<Unit__c> getByListingID(String listingID)
    { 
       
        return [SELECT Unit_Type__c, BMR_Rent_Monthly__c, BMR_Rental_Minimum_Monthly_Income_Needed__c, Unit_Square_Footage__c,  Unit_Number__c, Unit_Floor__c, Other_Accessibility_Information__c,Number_of_Bathrooms__c FROM Unit__c where Listing__c = :listingID  ORDER BY Unit_Type__c ];
    } 
    */
  
   
}