src/objects/Listing__c.object
<CustomObject>
    <fields>
        <fullName>Max_Occupancy__c</fullName>
        <description>Field will ultimately be hidden from page layout and is based on max occupancy of max from all units in a given listing. Field is used to hold the maximum occupancy.</description>
        <inlineHelpText>Field will ultimately be hidden from page layout and is based on max occupancy of max from all units in a given listing. Field is used to hold the maximum occupancy.</inlineHelpText>
        <label>Max Occupancy</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Occupancy__c</fullName>
        <description>Field will ultimately be hidden from page layout and is automatically determined based on number of Bedrooms. Field is used to hold the minimum occupancy based on bedrooms.</description>
        <inlineHelpText>Field will ultimately be hidden from page layout and is automatically determined based on number of Bedrooms. Field is used to hold the minimum occupancy based on bedrooms.</inlineHelpText>
        <label>Min Occupancy</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Listing</label>
    <nameField>
        <label>Listing Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Listings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Unit__c.object
<CustomObject>
    <fields>
        <fullName>Listing__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Listing</label>
        <referenceTo>Listing__c</referenceTo>
        <relationshipLabel>Units</relationshipLabel>
        <relationshipName>Units</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Max_Occupancy__c</fullName>
        <formula>/* Change on 11/17 to account for special rules for SRO and Studio (0 bedroom) types 
(Number_of_bedrooms_formula__c * 2) + 1

IF(Number_of_bedrooms_formula__c = 0, 2, ((Number_of_bedrooms_formula__c * 2) + 1)) */

IF((Number_of_bedrooms_formula__c = 0) &amp;&amp; (ISPICKVAL(Unit_Type__c, &quot;SRO&quot;)), 1,
IF((Number_of_bedrooms_formula__c = 0) &amp;&amp; (NOT(ISPICKVAL(Unit_Type__c, &quot;SRO&quot;))), 2,
((Number_of_bedrooms_formula__c * 2) + 1)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Max Occupancy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Min_Occupancy__c</fullName>
        <description>Field will ultimately be hidden from page layout and is automatically determined based on number of Bedrooms. Field is used to hold the minimum occupancy based on bedrooms.</description>
        <formula>/*OLD FORMULA - Replaced 10/13. Pivotal story: https://www.pivotaltracker.com/story/show/131777421
/*IF (Number_of_Bedrooms__c &gt;1, Number_of_Bedrooms__c, 1)*/

IF(ISPICKVAL(Unit_Type__c,&apos;2 BR&apos;), 2, 
  IF(ISPICKVAL(Unit_Type__c,&apos;3 BR&apos;), 3,
    IF(ISPICKVAL(Unit_Type__c,&apos;4 BR&apos;), 4,
      IF(ISPICKVAL(Unit_Type__c,&apos;5 BR&apos;),5,
     1))))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Field is used to hold the minimum occupancy based on bedrooms.</inlineHelpText>
        <label>Min Occupancy</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Square_Footage__c</fullName>
        <description>Square Footage of the Unit.</description>
        <inlineHelpText>Square Footage of the Unit.</inlineHelpText>
        <label>Unit Square Footage</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Unit_Type__c</fullName>
        <description>Description of units.</description>
        <inlineHelpText>Description of units.</inlineHelpText>
        <label>Unit Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>SRO</fullName>
                </value>
                <value>
                    <fullName>Studio</fullName>
                </value>
                <value>
                    <fullName>Large Studio</fullName>
                </value>
                <value>
                    <fullName>1 BR</fullName>
                </value>
                <value>
                    <fullName>2 BR</fullName>
                </value>
                <value>
                    <fullName>3 BR</fullName>
                </value>
                <value>
                    <fullName>4 BR</fullName>
                </value>
                <value>
                    <fullName>5 BR</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Unit</label>
    <nameField>
        <displayFormat>UID-{0000000}</displayFormat>
        <label>Unit ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Units</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ListUnitSummaryApi.cls
//services/apexrest/Listing/UnitStats
@RestResource(urlMapping='/Listing/UnitStats/*')
global with sharing class ListUnitSummaryApi {


    public class InvalidParamsException extends Exception {}
    
    public class NoRecordMatchException extends Exception {}

    @HttpGet
    global static List<UnitStat> doGet () {
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        
        List<String> tokens =  req.requestURI.split('/');
       
        if (tokens.size()>3) {
            return getUnitByListingId(tokens[3]);
        }
        if (req.params.containsKey('id')) {
            return getUnitByListingId(req.params.get('id'));
        }
        
         //return getAll(req.params.get('id'));
       
     throw new NoRecordMatchException(); 
       
    }
   
    
   global class UnitStat{
        ID listingID;
        String unitType;
        Decimal totalUnits;
        Decimal minOccupancy;
        Decimal maxOccupancy;
        Decimal minSquareFt;
        Decimal maxSquareFt;
        public UnitStat (AggregateResult result) {
            listingID = (ID)result.get('Listing__c');
            unitType = (String)result.get('Unit_Type__c');
            totalUnits = (Decimal)result.get('Total');
            minOccupancy = (Decimal)result.get('Min_Occupancy');
            maxOccupancy = (Decimal)result.get('Max_Occupancy');
            minSquareFt = (Decimal)result.get('Sq_Footage_Min');
            maxSquareFt = (Decimal)result.get('Sq_Footage_Max');
        
                        
            
        }
        
    }
    
    global static List<UnitStat> getUnitByListingId(string listingID){
    	AggregateResult[] results=  [SELECT Listing__c, Unit_Type__c,count(id)Total, MIN(Min_Occupancy__c)Min_Occupancy, Max(Max_Occupancy__c)Max_Occupancy, MIN(Unit_Square_Footage__c)Sq_Footage_Min, MAX(Unit_Square_Footage__c)Sq_Footage_Max  FROM UNIT__C WHERE Listing__c =: listingID GROUP BY listing__C, Unit_Type__c ];
        List<UnitStat> stats = new List<UnitStat>();
        for (AggregateResult result : results ) {
            stats.add(new UnitStat(result));
        }
        return stats;
    }
    
    global static List<UnitStat> getAll(String listingID)
    { 
        AggregateResult[] results=  [SELECT Listing__c, Unit_Type__c,count(id)Total, MIN(Min_Occupancy__c)Min_Occupancy, Max(Max_Occupancy__c)Max_Occupancy, MIN(Unit_Square_Footage__c)Sq_Footage_Min, MAX(Unit_Square_Footage__c)Sq_Footage_Max  FROM UNIT__C GROUP BY listing__C, Unit_Type__c ];
        List<UnitStat> stats = new List<UnitStat>();
        for (AggregateResult result : results ) {
            stats.add(new UnitStat(result));
        }
        return stats;
    } 
    
  
   
}