src/objects/Lottery_Preference__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>Enter the description of this preference</inlineHelpText>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <label>Preference</label>
    <nameField>
        <label>Preference Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Preferences</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ListingLotteryPrefApiTest.cls
@isTest
public with sharing class ListingLotteryPrefApiTest {
     
    static id lotteryId; 
    
    static void setupTestData() {
    	Lottery_Preference__c lp = new Lottery_Preference__c();
    	lp.Name = 'test';
    	lp.Description__c = 'test';
    	insert lp;
    	lotteryId = lp.Id;
    }
    
    static testMethod void testGetAll() {
         setupTestData();
        RestRequest reqContext = new RestRequest();

        reqContext.requestURI = '/LotteryPreference/';
        System.RestContext.request =reqContext; 
        ListingLotteryPrefApi.doGet();
        
        
    }
    static testMethod void testGetByID() {
        setupTestData();
        RestRequest reqContext = new RestRequest();

        reqContext.requestURI = '/LotteryPreference/' + lotteryId;
        System.RestContext.request =reqContext; 
        ListingLotteryPrefApi.doGet();
        
        
    }
     static testMethod void testGetByIDs() {
        setupTestData();
        RestRequest reqContext = new RestRequest();

        reqContext.requestURI = '/LotteryPreference/Ids=' + lotteryId;
        System.RestContext.request =reqContext; 
        ListingLotteryPrefApi.doGet();
        
        
    }
}