src/objects/Personal_Income__c.object
<CustomObject>
    <description>Income Details for household members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Incomes for all Household Members</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Income</relationshipLabel>
        <relationshipName>Personal_Income</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Income</label>
    <nameField>
        <displayFormat>INC-{YY}-{0}</displayFormat>
        <label>Income Line Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Income</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprgramsPersonalIncomeTriggerHandler.cls
public with sharing class SfmohprgramsPersonalIncomeTriggerHandler {
    
    public void beforeInsert(List<Personal_Income__c> pIncome) {

        Contact contId = new Contact();
        
        for(Personal_Income__c pi : pIncome){
            contId.Id = pi.Household_Member__c;
        }

        List<Contact> accId = new List<Contact>([SELECT AccountId FROM Contact WHERE Id =:contId.Id LIMIT 1]);
        
        for(Personal_Income__c pi : pIncome){
            if(accId.size()>0){
                pi.Household_Account__c = accId[0].AccountId;
            }
        }

    }
}