src/objects/Personal_Asset__c.object
<CustomObject>
    <description>Personal Assets of Household Members</description>
    <fields>
        <fullName>Household_Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Household Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Personal Assets for all Household Members</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Household_Member__c</fullName>
        <label>Household Member</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Contact.Account.Id</field>
                <operation>equals</operation>
                <valueField>$Source.Household_Account__c</valueField>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Personal Assets</relationshipLabel>
        <relationshipName>Personal_Assets</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Personal Asset</label>
    <nameField>
        <displayFormat>HHMA-{YY}-{0}</displayFormat>
        <label>Asset Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Personal Assets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/SfmohprgramsPersonalAssetTriggerHandler.cls
public with sharing class SfmohprgramsPersonalAssetTriggerHandler {

    public void beforeInsert(List<Personal_Asset__c> pAsset) {

        Contact contId = new Contact();
        
        for(Personal_Asset__c pa : pAsset){
            contId.Id = pa.Household_Member__c;
        }

        Contact accId = [SELECT AccountId FROM Contact WHERE Id =:contId.Id];
        
        for(Personal_Asset__c pa : pAsset){
            pa.Household_Account__c = accId.AccountId;
        }

    }
}