src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>Area_Sq_Ft__c</fullName>
        <label>Area (Sq. Ft.)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Marketing_Plan_Approval_Status__c</fullName>
        <label>Marketing Plan Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Neighborhood__c</fullName>
        <label>Neighborhood</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bayview</fullName>
                </value>
                <value>
                    <fullName>Bernal Heights</fullName>
                </value>
                <value>
                    <fullName>Castro/Upper Market</fullName>
                </value>
                <value>
                    <fullName>Chinatown</fullName>
                </value>
                <value>
                    <fullName>Civic Center</fullName>
                </value>
                <value>
                    <fullName>Crocker Amazon</fullName>
                </value>
                <value>
                    <fullName>Diamond Heights</fullName>
                </value>
                <value>
                    <fullName>Embarcadero</fullName>
                </value>
                <value>
                    <fullName>Excelsior</fullName>
                </value>
                <value>
                    <fullName>Financial District</fullName>
                </value>
                <value>
                    <fullName>Glen Park</fullName>
                </value>
                <value>
                    <fullName>Golden Gate Park</fullName>
                </value>
                <value>
                    <fullName>Haight Ashbury</fullName>
                </value>
                <value>
                    <fullName>Inner Richmond</fullName>
                </value>
                <value>
                    <fullName>Inner Sunset</fullName>
                </value>
                <value>
                    <fullName>Lakeshore</fullName>
                </value>
                <value>
                    <fullName>Marina</fullName>
                </value>
                <value>
                    <fullName>Mission</fullName>
                </value>
                <value>
                    <fullName>Nob Hill</fullName>
                </value>
                <value>
                    <fullName>Noe Valley</fullName>
                </value>
                <value>
                    <fullName>North Beach</fullName>
                </value>
                <value>
                    <fullName>Ocean View</fullName>
                </value>
                <value>
                    <fullName>Outer Mission</fullName>
                </value>
                <value>
                    <fullName>Outer Richmond</fullName>
                </value>
                <value>
                    <fullName>Outer Sunset</fullName>
                </value>
                <value>
                    <fullName>Pacific Heights</fullName>
                </value>
                <value>
                    <fullName>Parkside</fullName>
                </value>
                <value>
                    <fullName>Potrero Hill</fullName>
                </value>
                <value>
                    <fullName>Presidio</fullName>
                </value>
                <value>
                    <fullName>Presidio Heights</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_or_Existing__c</fullName>
        <label>New or Existing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupancy_Type__c</fullName>
        <label>Occupancy Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ownership</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Photo_1_Caption__c</fullName>
        <label>Photo 1 Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Posting_Date__c</fullName>
        <label>Posting Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Posting_End_Date__c</fullName>
        <inlineHelpText>The property posting will be removed from the MOHCD website on this date.</inlineHelpText>
        <label>Posting End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Pricing_Request_Approval_Status__c</fullName>
        <label>Pricing Request Approval Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Yet Submitted</fullName>
                    <default>true</default>
                </value>
                <value>
                    <fullName>Submitted</fullName>
                </value>
                <value>
                    <fullName>Under Review</fullName>
                </value>
                <value>
                    <fullName>Additional Information Required</fullName>
                </value>
                <value>
                    <fullName>Pending Final Approval</fullName>
                </value>
                <value>
                    <fullName>Approved</fullName>
                </value>
                <value>
                    <fullName>Denied</fullName>
                </value>
                <value>
                    <fullName>Under Appeal</fullName>
                </value>
                <value>
                    <fullName>Cancelled</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Property_Address_Zip_Code__c</fullName>
        <inlineHelpText>Enter the zip code for this Property address. Property address information must match the information in the closing documents.</inlineHelpText>
        <label>Property Address Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Name__c</fullName>
        <description>Name of a Property within a Development</description>
        <inlineHelpText>Name of a Property within a Development</inlineHelpText>
        <label>Property Name</label>
        <length>128</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Property_Photo_1__c</fullName>
        <label>Property Photo 1</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Co-op</fullName>
                </value>
                <value>
                    <fullName>Single Family</fullName>
                </value>
                <value>
                    <fullName>Apartment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Search_Bathrooms__c</fullName>
        <label>Search Bathrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>1.5</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>2.5</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Search_Bedrooms__c</fullName>
        <label>Search Bedrooms</label>
        <type>MultiselectPicklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>0</fullName>
                </value>
                <value>
                    <fullName>1</fullName>
                </value>
                <value>
                    <fullName>2</fullName>
                </value>
                <value>
                    <fullName>3</fullName>
                </value>
                <value>
                    <fullName>4</fullName>
                </value>
                <value>
                    <fullName>5</fullName>
                </value>
                <value>
                    <fullName>6</fullName>
                </value>
                <value>
                    <fullName>7</fullName>
                </value>
                <value>
                    <fullName>8</fullName>
                </value>
                <value>
                    <fullName>9</fullName>
                </value>
                <value>
                    <fullName>10</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Search_Price_Max__c</fullName>
        <label>Search Price Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Search_Price_Min__c</fullName>
        <label>Search Price Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Search_Sq_Ft_Max__c</fullName>
        <label>Search Sq Ft Max</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Search_Sq_Ft_Min__c</fullName>
        <label>Search Sq Ft Min</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Street_Name__c</fullName>
        <label>Street Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>of_Bathrooms__c</fullName>
        <label># of Bathrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Bedrooms__c</fullName>
        <label># of Bedrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <recordTypes>
        <fullName>Property</fullName>
        <active>true</active>
        <description>Property level details (including the block and lot number)</description>
        <label>Property</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_MOHCDBrowseListingCC.cls
/**
 * @author:      Sumit Shingavi
 * @date:        07/03/2014
 * @description: An apex page controller for mohcdBrowseListings VF Page.
 * @history:     06/10/2015 - Heidi Tang - Edited
*/
public class CS_MOHCDBrowseListingCC {
    
    //Public Variables
    public List<Properties__c> lProperties {get; set;}    //For List of Properties        
    public List<Properties__c> lUnits {get; set;}         //For List of Units
    public String strSelectedOccupancyType {get; set;}    //For Filter of Occupancy Type
    public String strSelectedPropertyType {get; set;}     //For Filter of Property Type
    public String strSelectedNewOrExisting {get; set;}    //For Filter of New Or Existing
    public String strSelectedNeighborhood {get; set;}     //For Filter of Neighborhood   
    public Integer intMinPrice {get; set;}                //For Filter of Min Price
    public Integer intMaxPrice {get; set;}                //For Filter of Max Price    
    public String strMinBedrooms {get; set;}             //For Filter of Min Bedrooms
    public Integer intMaxBedrooms {get; set;}             //For Filter of Max Bedrooms    
    public Decimal dcMinBathrooms {get; set;}            //For Filter of Min Bathrooms
    public Decimal dcMaxBathrooms {get; set;}            //For Filter of Max Bathrooms    
    public Decimal dcMinArea {get; set;}                  //For Filter of Min Area
    public Decimal dcMaxArea {get; set;}                  //For Filter of Max Area
    public String strZipCode {get; set;}                  //For Filter of Zip code
    
    //Private variables
    private String unitSortDirection = Label.ASCENDING;
    private String unitSortExp = 'Name';
    
    private String propSortDirection = Label.ASCENDING;
    private String propSortExp = 'Name';
    
    //Constructor
    public CS_MOHCDBrowseListingCC() {
        lProperties = new List<Properties__c>();
        lUnits = new List<Properties__c>();
        strSelectedOccupancyType = Label.ALL;
        strSelectedPropertyType = Label.ALL;
        strSelectedNewOrExisting = Label.ALL;
        strSelectedNeighborhood = Label.ALL;
        strZipCode = '';
    }    
    
    public PageReference init() {
        //prepareUnitsList();
        preparePropertiesList();
        return null;
    }
    
    /*
    * @auther : Cloud Sherpas Inc.
    * @date : 03/07/2014
    * @description : Apex method for preparing Property List
    * @parameters : Nothing
    * @returns : Nothing
    */  
    public PageReference preparePropertiesList() {
    
        try {            
            String strSOQL = 'SELECT Id, Name, Price__c, Occupancy_Type__c, Zip_Code__c, of_Bathrooms__c, of_Bedrooms__c, '; 
            strSOQL += 'Photo_1_Caption__c, Property_Photo_1__c, Area_Sq_Ft__c, New_or_Existing__c, Street_Name__c, RecordType.Name, ';
            strSOQL += 'Search_Bedrooms__c, Search_Bathrooms__c, Search_Price_Max__c, Search_Price_Min__c, ';
            strSOQL += 'Search_Sq_Ft_Max__c, Search_Sq_Ft_Min__c, ';
            strSOQL += 'Neighborhood__c, Property_Type__c, Property_Name__c FROM Properties__c ';
            strSOQL += 'WHERE RecordType.Name = \'Property\' AND Posting_Date__c <= TODAY AND Posting_End_Date__c >= TODAY ';
            strSOQL += 'AND Marketing_Plan_Approval_Status__c = \'Approved\' AND Pricing_Request_Approval_Status__c = \'Approved\' ';
            
            if((!String.isBlank(strSelectedOccupancyType)) && strSelectedOccupancyType != Label.ALL) {                
                strSOQL += ' AND (Occupancy_Type__c =: strSelectedOccupancyType)';                
            }
            if((!String.isBlank(strSelectedPropertyType)) && strSelectedPropertyType != Label.ALL) {                
                strSOQL += ' AND (Property_Type__c =: strSelectedPropertyType)';                
            }
            
            if((!String.isBlank(strSelectedNewOrExisting)) && strSelectedNewOrExisting != Label.ALL) {                
                strSOQL += ' AND (New_or_Existing__c =: strSelectedNewOrExisting)';                
            }
                        
            if((!String.isBlank(strSelectedNeighborhood)) && strSelectedNeighborhood != Label.ALL) {                
                strSOQL += ' AND (Neighborhood__c =: strSelectedNeighborhood)';                
            }
            
            if((intMinPrice != null) && (intMinPrice != 0)) {
                 if((intMaxPrice == null) || (intMaxPrice == 0)) {
                     strSOQL += ' AND (Search_Price_Min__c >=: intMinPrice OR Search_Price_Max__c >=: intMinPrice)';
                 }                 
            }  
            if((intMaxPrice != null) && (intMaxPrice != 0)) {
                 if((intMinPrice != null) && (intMinPrice != 0)) {
                     //strSOQL += ' AND ((Search_Price_Min__c >=: intMinPrice OR (Search_Price_Min__c <=: intMinPrice AND Search_Price_Max__c >=: intMinPrice )) AND ((intMaxPrice >=: Search_Price_Min__c AND intMaxPrice <=: Search_Price_Max__c) OR (Search_Price_Max__c = null AND Search_Price_Min__c <=: intMaxPrice )))';
                     strSOQL += ' AND ((Search_Price_Min__c >=: intMinPrice OR (Search_Price_Min__c <=: intMinPrice AND Search_Price_Max__c >=: intMinPrice )) AND (Search_Price_Max__c <=: intMaxPrice OR (Search_Price_Max__c >=: intMaxPrice AND Search_Price_Min__c <=: intMaxPrice) OR (Search_Price_Max__c = null AND Search_Price_Min__c <=: intMaxPrice )))';
                 } else {
                     strSOQL += ' AND (Search_Price_Max__c <=: intMaxPrice OR  (Search_Price_Max__c = null AND Search_Price_Min__c <=: intMaxPrice ))';
                 }
                 
            }                        
            
            if((strMinBedrooms != null) && (!String.isBlank(strMinBedrooms))) {
                 if((intMaxBedrooms == null) || (intMaxBedrooms == 0)) {
                     strSOQL += ' AND (Search_Bedrooms__c includes(\'' + strMinBedrooms + '\'))';
                 }                     
            }  
            if((intMaxBedrooms != null) && (intMaxBedrooms != 0)) {
            
                 Integer maxBedrooms = intMaxBedrooms;
                 String maxBedroomsStr = 'Search_Bedrooms__c includes(\''+ maxBedrooms + '\')';
                 Integer minBedrooms = (strMinBedrooms != null) ? Integer.valueOf(strMinBedrooms) : 0;
                 
                 //include in query, counts between min and max
                 for (Integer i = maxBedrooms; i >= minBedrooms ; i--) {
                     maxBedroomsStr += ' OR Search_Bedrooms__c includes(\''+ i + '\')';
                 }
                                                                                     
                 strSOQL += ' AND (' + maxBedroomsStr + ')';
                 
            }
            
            if((dcMinBathrooms != null) && (dcMinBathrooms != 0)) {
                 if((dcMaxBathrooms == null) || (dcMaxBathrooms == 0)) {                     
                     strSOQL += ' AND (Search_Bathrooms__c includes(\'' + dcMinBathrooms + '\'))';
                 }

            }  
            if((dcMaxBathrooms != null) && (dcMaxBathrooms != 0)) {
            
                 Integer maxBathrooms = Integer.valueOf(dcMaxBathrooms);
                 String maxBathroomsStr = 'Search_Bathrooms__c includes(\''+ String.valueOf(maxBathrooms) + '\')';
                 //String maxBathroomsStr = '\''+ String.valueOf(maxBathrooms) + '\'';
                 Integer minBathrooms = dcMinBathrooms != null ? Integer.valueOf(dcMinBathrooms) : 0;
                 
                 //include in query, counts between min and max
                 for (Integer i = maxBathrooms; i >= minBathrooms ; i--) {
                     maxBathroomsStr += ' OR Search_Bathrooms__c includes(\''+ i + '\')';
                 }
                 if (dcMaxBathrooms >= 2 && (dcMinBathrooms != null && dcMinBathrooms < 2)) {
                     maxBathroomsStr += ' OR Search_Bathrooms__c includes(\''+ 1.5 + '\')';                     
                 }
                                                  
                 strSOQL += ' AND (' + maxBathroomsStr  + ')';
            }
            
            if((dcMinArea != null) && (dcMinArea != 0)) {
                 if ((dcMaxArea == null) || (dcMaxArea == 0)) {
                     strSOQL += ' AND (Search_Sq_Ft_Min__c >=: dcMinArea OR Search_Sq_Ft_Max__c >=: dcMinArea)';
                 }
            }
            
            if((dcMaxArea != null) && (dcMaxArea != 0)) {
                 if((dcMinArea != null) && (dcMinArea != 0)) {
                     strSOQL += ' AND ((Search_Sq_Ft_Min__c >=: dcMinArea OR (Search_Sq_Ft_Min__c <=: dcMinArea AND Search_Sq_Ft_Max__c >=: dcMinArea)) AND (Search_Sq_Ft_Max__c <=: dcMaxArea OR (Search_Sq_Ft_Max__c >=: dcMaxArea AND Search_Sq_Ft_Min__c <= : dcMaxArea) OR (Search_Sq_Ft_Max__c = null AND Search_Sq_Ft_Min__c <=: dcMaxArea )))';
                 } else {
                     strSOQL += ' AND (Search_Sq_Ft_Max__c <=: dcMaxArea OR (Search_Sq_Ft_Max__c = null AND Search_Sq_Ft_Min__c <=: dcMaxArea ))';
                 }                 
            }
            
            if(!String.isBlank(strZipCode)) {
                strSOQL += ' AND Property_Address_Zip_Code__c LIKE \''+String.escapeSingleQuotes(strZipCode)+'%\'';
            }
            
            string sortFullExp = ' ORDER BY '+ propSortExpression  + ' ' + propSortDirection;    
            strSOQL += sortFullExp + ' LIMIT 999';
            
            System.debug(LoggingLevel.INFO, '==strSOQL for Properties==' + strSOQL);
            
            lProperties = new List<Properties__c>();
            lProperties = Database.query(strSOQL);
                      
        } catch(Exception e) {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: '+e.getMessage()));             
        }  
        return null;      
    }    
    
    public String propSortExpression {    
        get{ return propSortExp; }
        set{    
            if(value == propSortExp) {
                propSortDirection = (propSortDirection == 'ASC')? 'DESC' : 'ASC';
            } else {
                propSortDirection = 'ASC';
            }
            propSortExp = value;
        }
    }
    
    public String getPropSortDirection() {        
        if(propSortExpression == null || propSortExpression == '') {
            return 'ASC';
        } else {
            return propSortDirection;
        }    
    }
    
    public void setPropSortDirection(String value) {  
        propSortDirection = value;
    }
    
    public String unitSortExpression {    
        get{ return unitSortExp; }
        set{    
            if(value == unitSortExp) {
                unitSortDirection = (unitSortDirection == 'ASC')? 'DESC' : 'ASC';
            } else {
                unitSortDirection = 'ASC';
            }
            unitSortExp = value;
        }
    }
    
    public String getUnitSortDirection() {        
        if(unitSortExpression == null || unitSortExpression == '') {
            return 'ASC';
        } else {
            return unitSortDirection;
        }    
    }
    
    public void setUnitSortDirection(String value) {  
        unitSortDirection = value;
    }
    
    //Returns Property Types
    public List<SelectOption> getPropertyTypes() {                
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Properties__c.Property_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption(Label.ALL,Label.ALL));
        for(Schema.PicklistEntry f : ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;               
    }
    
    //Returns New OR Existing Picklist values
    public List<SelectOption> getNewOrExisting() {       
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Properties__c.New_or_Existing__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption(Label.ALL,Label.ALL));
        for(Schema.PicklistEntry f : ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }            
    
    //Returns Neighborhood picklist values
    public List<SelectOption> getNeighborhoods() {       
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Properties__c.Neighborhood__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption(Label.ALL,Label.ALL));
        for(Schema.PicklistEntry f : ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;
    }
    
    //Returns Occupancy Types
    public List<SelectOption> getOccupancyTypes() {   
        List<SelectOption> options = new List<SelectOption>();
        Schema.DescribeFieldResult fieldResult = Properties__c.Occupancy_Type__c.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
        options.add(new SelectOption(Label.ALL,Label.ALL));
        for(Schema.PicklistEntry f : ple) {
            options.add(new SelectOption(f.getLabel(), f.getValue()));
        }
        return options;       
    }               
}