src/objects/Properties__c.object
<CustomObject>
    <description>Property data table with the development, property, and unit information.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Area_Sq_Ft__c</fullName>
        <label>Area (Sq. Ft.)</label>
        <precision>18</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Neighborhood__c</fullName>
        <label>Neighborhood</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Bayview</fullName>
                </value>
                <value>
                    <fullName>Bernal Heights</fullName>
                </value>
                <value>
                    <fullName>Castro/Upper Market</fullName>
                </value>
                <value>
                    <fullName>Chinatown</fullName>
                </value>
                <value>
                    <fullName>Civic Center</fullName>
                </value>
                <value>
                    <fullName>Crocker Amazon</fullName>
                </value>
                <value>
                    <fullName>Diamond Heights</fullName>
                </value>
                <value>
                    <fullName>Embarcadero</fullName>
                </value>
                <value>
                    <fullName>Excelsior</fullName>
                </value>
                <value>
                    <fullName>Financial District</fullName>
                </value>
                <value>
                    <fullName>Glen Park</fullName>
                </value>
                <value>
                    <fullName>Golden Gate Park</fullName>
                </value>
                <value>
                    <fullName>Haight Ashbury</fullName>
                </value>
                <value>
                    <fullName>Inner Richmond</fullName>
                </value>
                <value>
                    <fullName>Inner Sunset</fullName>
                </value>
                <value>
                    <fullName>Lakeshore</fullName>
                </value>
                <value>
                    <fullName>Marina</fullName>
                </value>
                <value>
                    <fullName>Mission</fullName>
                </value>
                <value>
                    <fullName>Nob Hill</fullName>
                </value>
                <value>
                    <fullName>Noe Valley</fullName>
                </value>
                <value>
                    <fullName>North Beach</fullName>
                </value>
                <value>
                    <fullName>Ocean View</fullName>
                </value>
                <value>
                    <fullName>Outer Mission</fullName>
                </value>
                <value>
                    <fullName>Outer Richmond</fullName>
                </value>
                <value>
                    <fullName>Outer Sunset</fullName>
                </value>
                <value>
                    <fullName>Pacific Heights</fullName>
                </value>
                <value>
                    <fullName>Parkside</fullName>
                </value>
                <value>
                    <fullName>Potrero Hill</fullName>
                </value>
                <value>
                    <fullName>Presidio</fullName>
                </value>
                <value>
                    <fullName>Presidio Heights</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>New_or_Existing__c</fullName>
        <label>New or Existing</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>New</fullName>
                </value>
                <value>
                    <fullName>Existing</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Occupancy_Type__c</fullName>
        <label>Occupancy Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Ownership</fullName>
                </value>
                <value>
                    <fullName>Rental</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Photo_1_Caption__c</fullName>
        <label>Photo 1 Caption</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <label>Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Property_Photo_1__c</fullName>
        <label>Property Photo 1</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Property_Type__c</fullName>
        <label>Property Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Condo</fullName>
                </value>
                <value>
                    <fullName>Townhouse</fullName>
                </value>
                <value>
                    <fullName>Co-op</fullName>
                </value>
                <value>
                    <fullName>Single Family</fullName>
                </value>
                <value>
                    <fullName>Apartment</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>of_Bathrooms__c</fullName>
        <label># of Bathrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>of_Bedrooms__c</fullName>
        <label># of Bedrooms</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>oldListing</label>
    <nameField>
        <label>Listing Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>oldListings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CS_MOHCDBrowseListingCCTest.cls
/**
 * @author:      Sumit Shingavi
 * @date:        07/28/2014
 * @description: Test class for CS_MOHCDBrowseListingCC
 * @history:     06/10/2015 - Heidi Tang - Edited
*/
@isTest
private class CS_MOHCDBrowseListingCCTest {
    
    private static List<Properties__c> lProperties;
    private static List<Properties__c> lUnits;
    
    static {

        lProperties = new List<Properties__c>();
        Id propRtId = Schema.SObjectType.Properties__c.getRecordTypeInfosByName().get(StringConstants.LISTING_PROPERTY).getRecordTypeId();
        lProperties.add(CS_TestDataSetup.createTestProperties(130000, StringConstants.PROP_RENTAL, 4.5, 2, 'New', 'Condo', 'Castro', propRtId));
        lProperties.add(CS_TestDataSetup.createTestProperties(130000, StringConstants.PROP_OWNERSHIP, 4.5, 2, 'New', 'Apartment', 'Castro', propRtId));
        insert lProperties;
        
        lUnits = new List<Properties__c>();
        Id unitRtId = Schema.SObjectType.Properties__c.getRecordTypeInfosByName().get(StringConstants.LISTING_UNIT).getRecordTypeId();
        lUnits.add(CS_TestDataSetup.createTestProperties(130000, StringConstants.PROP_RENTAL, 4.5, 2, 'Existing', 'Condo', 'Castro', unitRtId));
        lUnits.add(CS_TestDataSetup.createTestProperties(130000, StringConstants.PROP_OWNERSHIP, 4.5, 2, 'Existing', 'Apartment', 'Castro', unitRtId));
        insert lUnits;
    }
    
    static testMethod void testBrowseListingCC() {
    
        Test.startTest();
 
            CS_MOHCDBrowseListingCC controller = new CS_MOHCDBrowseListingCC();
            controller.getNeighborhoods();
            controller.getNewOrExisting();
            controller.getPropertyTypes();
            controller.getOccupancyTypes();
            controller.init();
            
            System.assertEquals(0, controller.lProperties.size());
            System.assertEquals(0, controller.lUnits.size());
            
            controller.unitSortExpression = 'New_or_Existing__c';
            controller.propSortExpression = 'New_or_Existing__c';
            controller.init();
                          
            controller.unitSortExpression = 'Neighborhood__c';
            controller.propSortExpression = 'Neighborhood__c';
            controller.init();
            
            controller.unitSortExpression = 'Neighborhood__c';
            controller.propSortExpression = 'Neighborhood__c';
            controller.init();
            
            controller.unitSortExpression = '';
            controller.propSortExpression = '';
            controller.init();
            
            controller.strSelectedOccupancyType = StringConstants.PROP_OWNERSHIP;
            controller.strSelectedPropertyType = 'Apartment';
            controller.strSelectedNewOrExisting = 'New';
            controller.strSelectedNeighborhood = 'Castro';
            controller.intMinPrice = 10;
            controller.intMaxPrice = 15000;
            controller.strMinBedrooms = '1';
            controller.intMaxBedrooms = 4;
            controller.dcMinBathrooms = 1.0;
            controller.dcMaxBathrooms = 3.0;
            controller.dcMinArea = 400.0;
            controller.dcMaxArea = 2400.0;
            controller.strZipCode = '12345';
            controller.init();
            
            controller.getPropSortDirection();
            controller.getUnitSortDirection();
            
            controller.setPropSortDirection(Label.DESCENDING);
            controller.setUnitSortDirection(Label.DESCENDING);
        
        Test.stopTest();            

        System.assertEquals(0, controller.lProperties.size());
        System.assertEquals(0, controller.lUnits.size());
    }

    static testMethod void testBrowseListingCCWithZeroMaxValues() {
    
        Test.startTest();
 
            CS_MOHCDBrowseListingCC controller = new CS_MOHCDBrowseListingCC();
            controller.getNeighborhoods();
            controller.getNewOrExisting();
            controller.getPropertyTypes();
            controller.getOccupancyTypes();
            controller.init();
            
            controller.unitSortExpression = 'New_or_Existing__c';
            controller.propSortExpression = 'New_or_Existing__c';
            controller.init();
                          
            controller.unitSortExpression = 'Neighborhood__c';
            controller.propSortExpression = 'Neighborhood__c';
            controller.init();
            
            controller.unitSortExpression = 'Neighborhood__c';
            controller.propSortExpression = 'Neighborhood__c';
            controller.init();
            
            controller.unitSortExpression = '';
            controller.propSortExpression = '';
            controller.init();
            
            controller.strSelectedOccupancyType = StringConstants.PROP_OWNERSHIP;
            controller.strSelectedPropertyType = 'Apartment';
            controller.strSelectedNewOrExisting = 'New';
            controller.strSelectedNeighborhood = 'Castro';
            controller.intMinPrice = 10;
            controller.intMaxPrice = 0;
            controller.strMinBedrooms = '1';
            controller.intMaxBedrooms = 0;
            controller.dcMinBathrooms = 1.0;
            controller.dcMaxBathrooms = 0;
            controller.dcMinArea = 400.0;
            controller.dcMaxArea = 0;
            controller.strZipCode = '12345';
            controller.init();

            controller.propSortExpression = Label.ASCENDING;
            controller.unitSortExpression = Label.ASCENDING;
            
            
            controller.getPropSortDirection();
            controller.getUnitSortDirection();
            
            controller.setPropSortDirection(Label.DESCENDING);
            controller.setUnitSortDirection(Label.DESCENDING);
        
        Test.stopTest();    

        System.assertEquals(0, controller.lProperties.size());
        System.assertEquals(0, controller.lUnits.size());
    }

    static testMethod void testBrowseListingCCWithZeroMinValues() {
    
        Test.startTest();
 
            CS_MOHCDBrowseListingCC controller = new CS_MOHCDBrowseListingCC();
            controller.getNeighborhoods();
            controller.getNewOrExisting();
            controller.getPropertyTypes();
            controller.getOccupancyTypes();
            controller.init();
            
            System.assertEquals(0, controller.lProperties.size());
            System.assertEquals(0, controller.lUnits.size());
            
            controller.unitSortExpression = 'New_or_Existing__c';
            controller.propSortExpression = 'New_or_Existing__c';
            controller.init();
                          
            controller.unitSortExpression = 'Neighborhood__c';
            controller.propSortExpression = 'Neighborhood__c';
            controller.init();
            
            controller.unitSortExpression = 'Neighborhood__c';
            controller.propSortExpression = 'Neighborhood__c';
            controller.init();
            
            controller.unitSortExpression = '';
            controller.propSortExpression = '';
            controller.init();
            
            controller.strSelectedOccupancyType = StringConstants.PROP_OWNERSHIP;
            controller.strSelectedPropertyType = 'Apartment';
            controller.strSelectedNewOrExisting = 'New';
            controller.strSelectedNeighborhood = 'Castro';
            controller.intMinPrice = 0;
            controller.intMaxPrice = 15000;
            controller.strMinBedrooms = '1';
            controller.intMaxBedrooms = 4;
            controller.dcMinBathrooms = 1.0;
            controller.dcMaxBathrooms = 3.0;
            controller.dcMinArea = 0;
            controller.dcMaxArea = 2400.0;
            controller.strZipCode = '12345';
            controller.init();
            
            controller.getPropSortDirection();
            controller.getUnitSortDirection();
            
            controller.setPropSortDirection(Label.DESCENDING);
            controller.setUnitSortDirection(Label.DESCENDING);
        
        Test.stopTest();    

        System.assertEquals(0, controller.lProperties.size());
        System.assertEquals(0, controller.lUnits.size());
    }

    static testMethod void searchProperty(){
        Test.startTest();
            SfmohPropertySearchController controller = new SfmohPropertySearchController();
            controller.closePopup();
            String soqlQuery = controller.debugSoql;
            System.assert(soqlQuery =='select Id, Name, Price__c, Occupancy_Type__c, Zip_Code__c, of_bathrooms__c, of_Bedrooms__c, Area_Sq_Ft__c, New_or_Existing__c, Neighborhood__c, Property_Type__c, Property_Photo_1__c, Photo_1_Caption__c from Properties__c where Active__c = true order by of_bathrooms__c asc limit 20',soqlQuery);


            PageReference pref = Page.SfmohprogramsSearchProperties; 
                pref.getParameters().put('rowLink',lProperties[0].Name);
                pref.getParameters().put('price_min','100000');
                pref.getParameters().put('price_max','200000');
                pref.getParameters().put('occupancyType','All');
                pref.getParameters().put('zipCode','12345');
                pref.getParameters().put('numBedroomsmin','1');
                pref.getParameters().put('numBedroomsmax','4');
                pref.getParameters().put('numBathroomsmin','1.0');
                pref.getParameters().put('numBathroomsmax','3.0');
                pref.getParameters().put('areaSqFtmin','0');
                pref.getParameters().put('areaSqFtmax','2400.0');
                pref.getParameters().put('buildingType','All');
                pref.getParameters().put('neighborhood','All');
                pref.getParameters().put('proptype','All');
            Test.setCurrentPage(pref);
            controller.showPopup();
            controller.sortDir = 'asc';
            controller.toggleSort();
            controller.leftSelected.add('String 1');
            controller.rightSelected.add('String 1');
            controller.rightSelected.add('String 2');
            controller.selectClick();
            controller.getSelectedValues();
            controller.rightSelected.add('String 1');
            controller.rightSelected.add('String 2');
            controller.unselectClick();
            controller.getunSelectedValues();
            controller.prop_detail = new Properties__c();

            List<SelectOption> occupancyTypeList = controller.OccupancyTypeList;
            System.assert(occupancyTypeList.size()==3,occupancyTypeList.size());

            List<SelectOption> propertyTypeList = controller.PropertyTypeList;
            System.assert(propertyTypeList.size()==6,propertyTypeList.size());

            List<SelectOption> neworExistingList = controller.NeworExistingList;
            System.assert(neworExistingList.size()==3,neworExistingList.size());

            List<SelectOption> neighborhoodList = controller.NeighborhoodList;
            System.assert(neighborhoodList.size()==39,neighborhoodList.size());

            controller.runSearch();

            pref = Page.SfmohprogramsSearchProperties; 
                pref.getParameters().put('rowLink',lProperties[0].Name);
                pref.getParameters().put('price_min','');
                pref.getParameters().put('price_max','');
                pref.getParameters().put('occupancyType','Onwership');
                pref.getParameters().put('zipCode','12345');
                pref.getParameters().put('numBedroomsmin','');
                pref.getParameters().put('numBedroomsmax','');
                pref.getParameters().put('numBathroomsmin','');
                pref.getParameters().put('numBathroomsmax','');
                pref.getParameters().put('areaSqFtmin','');
                pref.getParameters().put('areaSqFtmax','');
                pref.getParameters().put('buildingType','Not All');
                pref.getParameters().put('neighborhood','Castro');
                pref.getParameters().put('proptype','Apartment');
            Test.setCurrentPage(pref);

            controller.runSearch();
        Test.stopTest();
    }

    static testMethod void secondSearchProperty(){
        Test.startTest();
            PropertySearchController2 controller = new PropertySearchController2();
            controller.closePopup();
            String soqlQuery = controller.debugSoql;
            System.assert(soqlQuery =='select Id, Name, Price__c, Occupancy_Type__c, Zip_Code__c, of_bathrooms__c, of_Bedrooms__c, Area_Sq_Ft__c, New_or_Existing__c, Neighborhood__c, Property_Type__c, Property_Photo_1__c, Photo_1_Caption__c from Properties__c where Active__c = true order by of_bathrooms__c asc limit 20',soqlQuery);



            PageReference pref = Page.SfmohprogramsSearchProperties; 
                pref.getParameters().put('rowLink',lProperties[0].Name);
                pref.getParameters().put('price_min','100000');
                pref.getParameters().put('price_max','200000');
                pref.getParameters().put('occupancyType','All');
                pref.getParameters().put('zipCode','12345');
                pref.getParameters().put('numBedroomsmin','1');
                pref.getParameters().put('numBedroomsmax','4');
                pref.getParameters().put('numBathroomsmin','1.0');
                pref.getParameters().put('numBathroomsmax','3.0');
                pref.getParameters().put('areaSqFtmin','0');
                pref.getParameters().put('areaSqFtmax','2400.0');
                pref.getParameters().put('buildingType','All');
                pref.getParameters().put('neighborhood','All');
                pref.getParameters().put('proptype','All');
            Test.setCurrentPage(pref);
            controller.showPopup();
            controller.sortDir = 'asc';
            controller.toggleSort();
            controller.prop_detail = new Properties__c();

            controller.runSearch();

            pref = Page.SfmohprogramsSearchProperties; 
                pref.getParameters().put('rowLink',lProperties[0].Name);
                pref.getParameters().put('price_min','');
                pref.getParameters().put('price_max','');
                pref.getParameters().put('occupancyType','Onwership');
                pref.getParameters().put('zipCode','12345');
                pref.getParameters().put('numBedroomsmin','');
                pref.getParameters().put('numBedroomsmax','');
                pref.getParameters().put('numBathroomsmin','');
                pref.getParameters().put('numBathroomsmax','');
                pref.getParameters().put('areaSqFtmin','');
                pref.getParameters().put('areaSqFtmax','');
                pref.getParameters().put('buildingType','Not All');
                pref.getParameters().put('neighborhood','Castro');
                pref.getParameters().put('proptype','Apartment');
            Test.setCurrentPage(pref);

            controller.runSearch();
        Test.stopTest();
    }
}